/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * AccoRoomDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class AccoRoomDetail {
  @JsonProperty("Language")
  private String language = null;

  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("Longdesc")
  private String longdesc = null;

  @JsonProperty("Shortdesc")
  private String shortdesc = null;

  public AccoRoomDetail language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public AccoRoomDetail name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AccoRoomDetail longdesc(String longdesc) {
    this.longdesc = longdesc;
    return this;
  }

   /**
   * Get longdesc
   * @return longdesc
  **/
  @ApiModelProperty(value = "")
  public String getLongdesc() {
    return longdesc;
  }

  public void setLongdesc(String longdesc) {
    this.longdesc = longdesc;
  }

  public AccoRoomDetail shortdesc(String shortdesc) {
    this.shortdesc = shortdesc;
    return this;
  }

   /**
   * Get shortdesc
   * @return shortdesc
  **/
  @ApiModelProperty(value = "")
  public String getShortdesc() {
    return shortdesc;
  }

  public void setShortdesc(String shortdesc) {
    this.shortdesc = shortdesc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccoRoomDetail accoRoomDetail = (AccoRoomDetail) o;
    return Objects.equals(this.language, accoRoomDetail.language) &&
        Objects.equals(this.name, accoRoomDetail.name) &&
        Objects.equals(this.longdesc, accoRoomDetail.longdesc) &&
        Objects.equals(this.shortdesc, accoRoomDetail.shortdesc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, name, longdesc, shortdesc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccoRoomDetail {\n");
    
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    longdesc: ").append(toIndentedString(longdesc)).append("\n");
    sb.append("    shortdesc: ").append(toIndentedString(shortdesc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

