/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.hackthealps.codemates.staylocalpaylocal.opendata.model.AccoBookingChannel;
import it.hackthealps.codemates.staylocalpaylocal.opendata.model.AccoDetail;
import it.hackthealps.codemates.staylocalpaylocal.opendata.model.AccoFeature;
import it.hackthealps.codemates.staylocalpaylocal.opendata.model.ImageGallery;
import it.hackthealps.codemates.staylocalpaylocal.opendata.model.LocationInfo;
import it.hackthealps.codemates.staylocalpaylocal.opendata.model.MssResponseShort;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Accommodation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class Accommodation {
  @JsonProperty("Id")
  private String id = null;

  @JsonProperty("Active")
  private Boolean active = null;

  @JsonProperty("HgvId")
  private String hgvId = null;

  @JsonProperty("Shortname")
  private String shortname = null;

  @JsonProperty("Units")
  private Integer units = null;

  @JsonProperty("Beds")
  private Integer beds = null;

  @JsonProperty("HasApartment")
  private Boolean hasApartment = null;

  @JsonProperty("HasRoom")
  private Boolean hasRoom = null;

  @JsonProperty("IsCamping")
  private Boolean isCamping = null;

  @JsonProperty("IsGastronomy")
  private Boolean isGastronomy = null;

  @JsonProperty("IsBookable")
  private Boolean isBookable = null;

  @JsonProperty("IsAccommodation")
  private Boolean isAccommodation = null;

  @JsonProperty("SmgActive")
  private Boolean smgActive = null;

  @JsonProperty("TVMember")
  private Boolean tvMember = null;

  @JsonProperty("TourismVereinId")
  private String tourismVereinId = null;

  @JsonProperty("MainLanguage")
  private String mainLanguage = null;

  @JsonProperty("FirstImport")
  private OffsetDateTime firstImport = null;

  @JsonProperty("LastChange")
  private OffsetDateTime lastChange = null;

  @JsonProperty("Gpstype")
  private String gpstype = null;

  @JsonProperty("Latitude")
  private Double latitude = null;

  @JsonProperty("Longitude")
  private Double longitude = null;

  @JsonProperty("Altitude")
  private Double altitude = null;

  @JsonProperty("AltitudeUnitofMeasure")
  private String altitudeUnitofMeasure = null;

  @JsonProperty("AccoCategoryId")
  private String accoCategoryId = null;

  @JsonProperty("AccoTypeId")
  private String accoTypeId = null;

  @JsonProperty("DistrictId")
  private String districtId = null;

  @JsonProperty("BoardIds")
  private List<String> boardIds = null;

  @JsonProperty("MarketingGroupIds")
  private List<String> marketingGroupIds = null;

  @JsonProperty("Features")
  private List<AccoFeature> features = null;

  @JsonProperty("BadgeIds")
  private List<String> badgeIds = null;

  @JsonProperty("ThemeIds")
  private List<String> themeIds = null;

  @JsonProperty("SpecialFeaturesIds")
  private List<String> specialFeaturesIds = null;

  @JsonProperty("AccoDetail")
  private Map<String, AccoDetail> accoDetail = null;

  @JsonProperty("AccoBookingChannel")
  private List<AccoBookingChannel> accoBookingChannel = null;

  @JsonProperty("ImageGallery")
  private List<ImageGallery> imageGallery = null;

  @JsonProperty("LocationInfo")
  private LocationInfo locationInfo = null;

  @JsonProperty("GastronomyId")
  private String gastronomyId = null;

  @JsonProperty("SmgTags")
  private List<String> smgTags = null;

  @JsonProperty("HasLanguage")
  private List<String> hasLanguage = null;

  @JsonProperty("MssResponseShort")
  private List<MssResponseShort> mssResponseShort = null;

  @JsonProperty("TrustYouID")
  private String trustYouID = null;

  @JsonProperty("TrustYouScore")
  private Double trustYouScore = null;

  @JsonProperty("TrustYouResults")
  private Integer trustYouResults = null;

  public Accommodation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Accommodation active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Accommodation hgvId(String hgvId) {
    this.hgvId = hgvId;
    return this;
  }

   /**
   * Get hgvId
   * @return hgvId
  **/
  @ApiModelProperty(value = "")
  public String getHgvId() {
    return hgvId;
  }

  public void setHgvId(String hgvId) {
    this.hgvId = hgvId;
  }

  public Accommodation shortname(String shortname) {
    this.shortname = shortname;
    return this;
  }

   /**
   * Get shortname
   * @return shortname
  **/
  @ApiModelProperty(value = "")
  public String getShortname() {
    return shortname;
  }

  public void setShortname(String shortname) {
    this.shortname = shortname;
  }

  public Accommodation units(Integer units) {
    this.units = units;
    return this;
  }

   /**
   * Get units
   * @return units
  **/
  @ApiModelProperty(value = "")
  public Integer getUnits() {
    return units;
  }

  public void setUnits(Integer units) {
    this.units = units;
  }

  public Accommodation beds(Integer beds) {
    this.beds = beds;
    return this;
  }

   /**
   * Get beds
   * @return beds
  **/
  @ApiModelProperty(value = "")
  public Integer getBeds() {
    return beds;
  }

  public void setBeds(Integer beds) {
    this.beds = beds;
  }

  public Accommodation hasApartment(Boolean hasApartment) {
    this.hasApartment = hasApartment;
    return this;
  }

   /**
   * Get hasApartment
   * @return hasApartment
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasApartment() {
    return hasApartment;
  }

  public void setHasApartment(Boolean hasApartment) {
    this.hasApartment = hasApartment;
  }

  public Accommodation hasRoom(Boolean hasRoom) {
    this.hasRoom = hasRoom;
    return this;
  }

   /**
   * Get hasRoom
   * @return hasRoom
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasRoom() {
    return hasRoom;
  }

  public void setHasRoom(Boolean hasRoom) {
    this.hasRoom = hasRoom;
  }

  public Accommodation isCamping(Boolean isCamping) {
    this.isCamping = isCamping;
    return this;
  }

   /**
   * Get isCamping
   * @return isCamping
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsCamping() {
    return isCamping;
  }

  public void setIsCamping(Boolean isCamping) {
    this.isCamping = isCamping;
  }

  public Accommodation isGastronomy(Boolean isGastronomy) {
    this.isGastronomy = isGastronomy;
    return this;
  }

   /**
   * Get isGastronomy
   * @return isGastronomy
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsGastronomy() {
    return isGastronomy;
  }

  public void setIsGastronomy(Boolean isGastronomy) {
    this.isGastronomy = isGastronomy;
  }

  public Accommodation isBookable(Boolean isBookable) {
    this.isBookable = isBookable;
    return this;
  }

   /**
   * Get isBookable
   * @return isBookable
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsBookable() {
    return isBookable;
  }

  public void setIsBookable(Boolean isBookable) {
    this.isBookable = isBookable;
  }

  public Accommodation isAccommodation(Boolean isAccommodation) {
    this.isAccommodation = isAccommodation;
    return this;
  }

   /**
   * Get isAccommodation
   * @return isAccommodation
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsAccommodation() {
    return isAccommodation;
  }

  public void setIsAccommodation(Boolean isAccommodation) {
    this.isAccommodation = isAccommodation;
  }

  public Accommodation smgActive(Boolean smgActive) {
    this.smgActive = smgActive;
    return this;
  }

   /**
   * Get smgActive
   * @return smgActive
  **/
  @ApiModelProperty(value = "")
  public Boolean isSmgActive() {
    return smgActive;
  }

  public void setSmgActive(Boolean smgActive) {
    this.smgActive = smgActive;
  }

  public Accommodation tvMember(Boolean tvMember) {
    this.tvMember = tvMember;
    return this;
  }

   /**
   * Get tvMember
   * @return tvMember
  **/
  @ApiModelProperty(value = "")
  public Boolean isTvMember() {
    return tvMember;
  }

  public void setTvMember(Boolean tvMember) {
    this.tvMember = tvMember;
  }

  public Accommodation tourismVereinId(String tourismVereinId) {
    this.tourismVereinId = tourismVereinId;
    return this;
  }

   /**
   * Get tourismVereinId
   * @return tourismVereinId
  **/
  @ApiModelProperty(value = "")
  public String getTourismVereinId() {
    return tourismVereinId;
  }

  public void setTourismVereinId(String tourismVereinId) {
    this.tourismVereinId = tourismVereinId;
  }

  public Accommodation mainLanguage(String mainLanguage) {
    this.mainLanguage = mainLanguage;
    return this;
  }

   /**
   * Get mainLanguage
   * @return mainLanguage
  **/
  @ApiModelProperty(value = "")
  public String getMainLanguage() {
    return mainLanguage;
  }

  public void setMainLanguage(String mainLanguage) {
    this.mainLanguage = mainLanguage;
  }

  public Accommodation firstImport(OffsetDateTime firstImport) {
    this.firstImport = firstImport;
    return this;
  }

   /**
   * Get firstImport
   * @return firstImport
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getFirstImport() {
    return firstImport;
  }

  public void setFirstImport(OffsetDateTime firstImport) {
    this.firstImport = firstImport;
  }

  public Accommodation lastChange(OffsetDateTime lastChange) {
    this.lastChange = lastChange;
    return this;
  }

   /**
   * Get lastChange
   * @return lastChange
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastChange() {
    return lastChange;
  }

  public void setLastChange(OffsetDateTime lastChange) {
    this.lastChange = lastChange;
  }

  public Accommodation gpstype(String gpstype) {
    this.gpstype = gpstype;
    return this;
  }

   /**
   * Get gpstype
   * @return gpstype
  **/
  @ApiModelProperty(value = "")
  public String getGpstype() {
    return gpstype;
  }

  public void setGpstype(String gpstype) {
    this.gpstype = gpstype;
  }

  public Accommodation latitude(Double latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @ApiModelProperty(value = "")
  public Double getLatitude() {
    return latitude;
  }

  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }

  public Accommodation longitude(Double longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @ApiModelProperty(value = "")
  public Double getLongitude() {
    return longitude;
  }

  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }

  public Accommodation altitude(Double altitude) {
    this.altitude = altitude;
    return this;
  }

   /**
   * Get altitude
   * @return altitude
  **/
  @ApiModelProperty(value = "")
  public Double getAltitude() {
    return altitude;
  }

  public void setAltitude(Double altitude) {
    this.altitude = altitude;
  }

  public Accommodation altitudeUnitofMeasure(String altitudeUnitofMeasure) {
    this.altitudeUnitofMeasure = altitudeUnitofMeasure;
    return this;
  }

   /**
   * Get altitudeUnitofMeasure
   * @return altitudeUnitofMeasure
  **/
  @ApiModelProperty(value = "")
  public String getAltitudeUnitofMeasure() {
    return altitudeUnitofMeasure;
  }

  public void setAltitudeUnitofMeasure(String altitudeUnitofMeasure) {
    this.altitudeUnitofMeasure = altitudeUnitofMeasure;
  }

  public Accommodation accoCategoryId(String accoCategoryId) {
    this.accoCategoryId = accoCategoryId;
    return this;
  }

   /**
   * Get accoCategoryId
   * @return accoCategoryId
  **/
  @ApiModelProperty(value = "")
  public String getAccoCategoryId() {
    return accoCategoryId;
  }

  public void setAccoCategoryId(String accoCategoryId) {
    this.accoCategoryId = accoCategoryId;
  }

  public Accommodation accoTypeId(String accoTypeId) {
    this.accoTypeId = accoTypeId;
    return this;
  }

   /**
   * Get accoTypeId
   * @return accoTypeId
  **/
  @ApiModelProperty(value = "")
  public String getAccoTypeId() {
    return accoTypeId;
  }

  public void setAccoTypeId(String accoTypeId) {
    this.accoTypeId = accoTypeId;
  }

  public Accommodation districtId(String districtId) {
    this.districtId = districtId;
    return this;
  }

   /**
   * Get districtId
   * @return districtId
  **/
  @ApiModelProperty(value = "")
  public String getDistrictId() {
    return districtId;
  }

  public void setDistrictId(String districtId) {
    this.districtId = districtId;
  }

  public Accommodation boardIds(List<String> boardIds) {
    this.boardIds = boardIds;
    return this;
  }

  public Accommodation addBoardIdsItem(String boardIdsItem) {
    if (this.boardIds == null) {
      this.boardIds = new ArrayList<>();
    }
    this.boardIds.add(boardIdsItem);
    return this;
  }

   /**
   * Get boardIds
   * @return boardIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getBoardIds() {
    return boardIds;
  }

  public void setBoardIds(List<String> boardIds) {
    this.boardIds = boardIds;
  }

  public Accommodation marketingGroupIds(List<String> marketingGroupIds) {
    this.marketingGroupIds = marketingGroupIds;
    return this;
  }

  public Accommodation addMarketingGroupIdsItem(String marketingGroupIdsItem) {
    if (this.marketingGroupIds == null) {
      this.marketingGroupIds = new ArrayList<>();
    }
    this.marketingGroupIds.add(marketingGroupIdsItem);
    return this;
  }

   /**
   * Get marketingGroupIds
   * @return marketingGroupIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getMarketingGroupIds() {
    return marketingGroupIds;
  }

  public void setMarketingGroupIds(List<String> marketingGroupIds) {
    this.marketingGroupIds = marketingGroupIds;
  }

  public Accommodation features(List<AccoFeature> features) {
    this.features = features;
    return this;
  }

  public Accommodation addFeaturesItem(AccoFeature featuresItem) {
    if (this.features == null) {
      this.features = new ArrayList<>();
    }
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  @ApiModelProperty(value = "")
  public List<AccoFeature> getFeatures() {
    return features;
  }

  public void setFeatures(List<AccoFeature> features) {
    this.features = features;
  }

  public Accommodation badgeIds(List<String> badgeIds) {
    this.badgeIds = badgeIds;
    return this;
  }

  public Accommodation addBadgeIdsItem(String badgeIdsItem) {
    if (this.badgeIds == null) {
      this.badgeIds = new ArrayList<>();
    }
    this.badgeIds.add(badgeIdsItem);
    return this;
  }

   /**
   * Get badgeIds
   * @return badgeIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getBadgeIds() {
    return badgeIds;
  }

  public void setBadgeIds(List<String> badgeIds) {
    this.badgeIds = badgeIds;
  }

  public Accommodation themeIds(List<String> themeIds) {
    this.themeIds = themeIds;
    return this;
  }

  public Accommodation addThemeIdsItem(String themeIdsItem) {
    if (this.themeIds == null) {
      this.themeIds = new ArrayList<>();
    }
    this.themeIds.add(themeIdsItem);
    return this;
  }

   /**
   * Get themeIds
   * @return themeIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getThemeIds() {
    return themeIds;
  }

  public void setThemeIds(List<String> themeIds) {
    this.themeIds = themeIds;
  }

  public Accommodation specialFeaturesIds(List<String> specialFeaturesIds) {
    this.specialFeaturesIds = specialFeaturesIds;
    return this;
  }

  public Accommodation addSpecialFeaturesIdsItem(String specialFeaturesIdsItem) {
    if (this.specialFeaturesIds == null) {
      this.specialFeaturesIds = new ArrayList<>();
    }
    this.specialFeaturesIds.add(specialFeaturesIdsItem);
    return this;
  }

   /**
   * Get specialFeaturesIds
   * @return specialFeaturesIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getSpecialFeaturesIds() {
    return specialFeaturesIds;
  }

  public void setSpecialFeaturesIds(List<String> specialFeaturesIds) {
    this.specialFeaturesIds = specialFeaturesIds;
  }

  public Accommodation accoDetail(Map<String, AccoDetail> accoDetail) {
    this.accoDetail = accoDetail;
    return this;
  }

  public Accommodation putAccoDetailItem(String key, AccoDetail accoDetailItem) {
    if (this.accoDetail == null) {
      this.accoDetail = new HashMap<>();
    }
    this.accoDetail.put(key, accoDetailItem);
    return this;
  }

   /**
   * Get accoDetail
   * @return accoDetail
  **/
  @ApiModelProperty(value = "")
  public Map<String, AccoDetail> getAccoDetail() {
    return accoDetail;
  }

  public void setAccoDetail(Map<String, AccoDetail> accoDetail) {
    this.accoDetail = accoDetail;
  }

  public Accommodation accoBookingChannel(List<AccoBookingChannel> accoBookingChannel) {
    this.accoBookingChannel = accoBookingChannel;
    return this;
  }

  public Accommodation addAccoBookingChannelItem(AccoBookingChannel accoBookingChannelItem) {
    if (this.accoBookingChannel == null) {
      this.accoBookingChannel = new ArrayList<>();
    }
    this.accoBookingChannel.add(accoBookingChannelItem);
    return this;
  }

   /**
   * Get accoBookingChannel
   * @return accoBookingChannel
  **/
  @ApiModelProperty(value = "")
  public List<AccoBookingChannel> getAccoBookingChannel() {
    return accoBookingChannel;
  }

  public void setAccoBookingChannel(List<AccoBookingChannel> accoBookingChannel) {
    this.accoBookingChannel = accoBookingChannel;
  }

  public Accommodation imageGallery(List<ImageGallery> imageGallery) {
    this.imageGallery = imageGallery;
    return this;
  }

  public Accommodation addImageGalleryItem(ImageGallery imageGalleryItem) {
    if (this.imageGallery == null) {
      this.imageGallery = new ArrayList<>();
    }
    this.imageGallery.add(imageGalleryItem);
    return this;
  }

   /**
   * Get imageGallery
   * @return imageGallery
  **/
  @ApiModelProperty(value = "")
  public List<ImageGallery> getImageGallery() {
    return imageGallery;
  }

  public void setImageGallery(List<ImageGallery> imageGallery) {
    this.imageGallery = imageGallery;
  }

  public Accommodation locationInfo(LocationInfo locationInfo) {
    this.locationInfo = locationInfo;
    return this;
  }

   /**
   * Get locationInfo
   * @return locationInfo
  **/
  @ApiModelProperty(value = "")
  public LocationInfo getLocationInfo() {
    return locationInfo;
  }

  public void setLocationInfo(LocationInfo locationInfo) {
    this.locationInfo = locationInfo;
  }

  public Accommodation gastronomyId(String gastronomyId) {
    this.gastronomyId = gastronomyId;
    return this;
  }

   /**
   * Get gastronomyId
   * @return gastronomyId
  **/
  @ApiModelProperty(value = "")
  public String getGastronomyId() {
    return gastronomyId;
  }

  public void setGastronomyId(String gastronomyId) {
    this.gastronomyId = gastronomyId;
  }

  public Accommodation smgTags(List<String> smgTags) {
    this.smgTags = smgTags;
    return this;
  }

  public Accommodation addSmgTagsItem(String smgTagsItem) {
    if (this.smgTags == null) {
      this.smgTags = new ArrayList<>();
    }
    this.smgTags.add(smgTagsItem);
    return this;
  }

   /**
   * Get smgTags
   * @return smgTags
  **/
  @ApiModelProperty(value = "")
  public List<String> getSmgTags() {
    return smgTags;
  }

  public void setSmgTags(List<String> smgTags) {
    this.smgTags = smgTags;
  }

  public Accommodation hasLanguage(List<String> hasLanguage) {
    this.hasLanguage = hasLanguage;
    return this;
  }

  public Accommodation addHasLanguageItem(String hasLanguageItem) {
    if (this.hasLanguage == null) {
      this.hasLanguage = new ArrayList<>();
    }
    this.hasLanguage.add(hasLanguageItem);
    return this;
  }

   /**
   * Get hasLanguage
   * @return hasLanguage
  **/
  @ApiModelProperty(value = "")
  public List<String> getHasLanguage() {
    return hasLanguage;
  }

  public void setHasLanguage(List<String> hasLanguage) {
    this.hasLanguage = hasLanguage;
  }

  public Accommodation mssResponseShort(List<MssResponseShort> mssResponseShort) {
    this.mssResponseShort = mssResponseShort;
    return this;
  }

  public Accommodation addMssResponseShortItem(MssResponseShort mssResponseShortItem) {
    if (this.mssResponseShort == null) {
      this.mssResponseShort = new ArrayList<>();
    }
    this.mssResponseShort.add(mssResponseShortItem);
    return this;
  }

   /**
   * Get mssResponseShort
   * @return mssResponseShort
  **/
  @ApiModelProperty(value = "")
  public List<MssResponseShort> getMssResponseShort() {
    return mssResponseShort;
  }

  public void setMssResponseShort(List<MssResponseShort> mssResponseShort) {
    this.mssResponseShort = mssResponseShort;
  }

  public Accommodation trustYouID(String trustYouID) {
    this.trustYouID = trustYouID;
    return this;
  }

   /**
   * Get trustYouID
   * @return trustYouID
  **/
  @ApiModelProperty(value = "")
  public String getTrustYouID() {
    return trustYouID;
  }

  public void setTrustYouID(String trustYouID) {
    this.trustYouID = trustYouID;
  }

  public Accommodation trustYouScore(Double trustYouScore) {
    this.trustYouScore = trustYouScore;
    return this;
  }

   /**
   * Get trustYouScore
   * @return trustYouScore
  **/
  @ApiModelProperty(value = "")
  public Double getTrustYouScore() {
    return trustYouScore;
  }

  public void setTrustYouScore(Double trustYouScore) {
    this.trustYouScore = trustYouScore;
  }

  public Accommodation trustYouResults(Integer trustYouResults) {
    this.trustYouResults = trustYouResults;
    return this;
  }

   /**
   * Get trustYouResults
   * @return trustYouResults
  **/
  @ApiModelProperty(value = "")
  public Integer getTrustYouResults() {
    return trustYouResults;
  }

  public void setTrustYouResults(Integer trustYouResults) {
    this.trustYouResults = trustYouResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Accommodation accommodation = (Accommodation) o;
    return Objects.equals(this.id, accommodation.id) &&
        Objects.equals(this.active, accommodation.active) &&
        Objects.equals(this.hgvId, accommodation.hgvId) &&
        Objects.equals(this.shortname, accommodation.shortname) &&
        Objects.equals(this.units, accommodation.units) &&
        Objects.equals(this.beds, accommodation.beds) &&
        Objects.equals(this.hasApartment, accommodation.hasApartment) &&
        Objects.equals(this.hasRoom, accommodation.hasRoom) &&
        Objects.equals(this.isCamping, accommodation.isCamping) &&
        Objects.equals(this.isGastronomy, accommodation.isGastronomy) &&
        Objects.equals(this.isBookable, accommodation.isBookable) &&
        Objects.equals(this.isAccommodation, accommodation.isAccommodation) &&
        Objects.equals(this.smgActive, accommodation.smgActive) &&
        Objects.equals(this.tvMember, accommodation.tvMember) &&
        Objects.equals(this.tourismVereinId, accommodation.tourismVereinId) &&
        Objects.equals(this.mainLanguage, accommodation.mainLanguage) &&
        Objects.equals(this.firstImport, accommodation.firstImport) &&
        Objects.equals(this.lastChange, accommodation.lastChange) &&
        Objects.equals(this.gpstype, accommodation.gpstype) &&
        Objects.equals(this.latitude, accommodation.latitude) &&
        Objects.equals(this.longitude, accommodation.longitude) &&
        Objects.equals(this.altitude, accommodation.altitude) &&
        Objects.equals(this.altitudeUnitofMeasure, accommodation.altitudeUnitofMeasure) &&
        Objects.equals(this.accoCategoryId, accommodation.accoCategoryId) &&
        Objects.equals(this.accoTypeId, accommodation.accoTypeId) &&
        Objects.equals(this.districtId, accommodation.districtId) &&
        Objects.equals(this.boardIds, accommodation.boardIds) &&
        Objects.equals(this.marketingGroupIds, accommodation.marketingGroupIds) &&
        Objects.equals(this.features, accommodation.features) &&
        Objects.equals(this.badgeIds, accommodation.badgeIds) &&
        Objects.equals(this.themeIds, accommodation.themeIds) &&
        Objects.equals(this.specialFeaturesIds, accommodation.specialFeaturesIds) &&
        Objects.equals(this.accoDetail, accommodation.accoDetail) &&
        Objects.equals(this.accoBookingChannel, accommodation.accoBookingChannel) &&
        Objects.equals(this.imageGallery, accommodation.imageGallery) &&
        Objects.equals(this.locationInfo, accommodation.locationInfo) &&
        Objects.equals(this.gastronomyId, accommodation.gastronomyId) &&
        Objects.equals(this.smgTags, accommodation.smgTags) &&
        Objects.equals(this.hasLanguage, accommodation.hasLanguage) &&
        Objects.equals(this.mssResponseShort, accommodation.mssResponseShort) &&
        Objects.equals(this.trustYouID, accommodation.trustYouID) &&
        Objects.equals(this.trustYouScore, accommodation.trustYouScore) &&
        Objects.equals(this.trustYouResults, accommodation.trustYouResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, active, hgvId, shortname, units, beds, hasApartment, hasRoom, isCamping, isGastronomy, isBookable, isAccommodation, smgActive, tvMember, tourismVereinId, mainLanguage, firstImport, lastChange, gpstype, latitude, longitude, altitude, altitudeUnitofMeasure, accoCategoryId, accoTypeId, districtId, boardIds, marketingGroupIds, features, badgeIds, themeIds, specialFeaturesIds, accoDetail, accoBookingChannel, imageGallery, locationInfo, gastronomyId, smgTags, hasLanguage, mssResponseShort, trustYouID, trustYouScore, trustYouResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Accommodation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    hgvId: ").append(toIndentedString(hgvId)).append("\n");
    sb.append("    shortname: ").append(toIndentedString(shortname)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    beds: ").append(toIndentedString(beds)).append("\n");
    sb.append("    hasApartment: ").append(toIndentedString(hasApartment)).append("\n");
    sb.append("    hasRoom: ").append(toIndentedString(hasRoom)).append("\n");
    sb.append("    isCamping: ").append(toIndentedString(isCamping)).append("\n");
    sb.append("    isGastronomy: ").append(toIndentedString(isGastronomy)).append("\n");
    sb.append("    isBookable: ").append(toIndentedString(isBookable)).append("\n");
    sb.append("    isAccommodation: ").append(toIndentedString(isAccommodation)).append("\n");
    sb.append("    smgActive: ").append(toIndentedString(smgActive)).append("\n");
    sb.append("    tvMember: ").append(toIndentedString(tvMember)).append("\n");
    sb.append("    tourismVereinId: ").append(toIndentedString(tourismVereinId)).append("\n");
    sb.append("    mainLanguage: ").append(toIndentedString(mainLanguage)).append("\n");
    sb.append("    firstImport: ").append(toIndentedString(firstImport)).append("\n");
    sb.append("    lastChange: ").append(toIndentedString(lastChange)).append("\n");
    sb.append("    gpstype: ").append(toIndentedString(gpstype)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    altitude: ").append(toIndentedString(altitude)).append("\n");
    sb.append("    altitudeUnitofMeasure: ").append(toIndentedString(altitudeUnitofMeasure)).append("\n");
    sb.append("    accoCategoryId: ").append(toIndentedString(accoCategoryId)).append("\n");
    sb.append("    accoTypeId: ").append(toIndentedString(accoTypeId)).append("\n");
    sb.append("    districtId: ").append(toIndentedString(districtId)).append("\n");
    sb.append("    boardIds: ").append(toIndentedString(boardIds)).append("\n");
    sb.append("    marketingGroupIds: ").append(toIndentedString(marketingGroupIds)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    badgeIds: ").append(toIndentedString(badgeIds)).append("\n");
    sb.append("    themeIds: ").append(toIndentedString(themeIds)).append("\n");
    sb.append("    specialFeaturesIds: ").append(toIndentedString(specialFeaturesIds)).append("\n");
    sb.append("    accoDetail: ").append(toIndentedString(accoDetail)).append("\n");
    sb.append("    accoBookingChannel: ").append(toIndentedString(accoBookingChannel)).append("\n");
    sb.append("    imageGallery: ").append(toIndentedString(imageGallery)).append("\n");
    sb.append("    locationInfo: ").append(toIndentedString(locationInfo)).append("\n");
    sb.append("    gastronomyId: ").append(toIndentedString(gastronomyId)).append("\n");
    sb.append("    smgTags: ").append(toIndentedString(smgTags)).append("\n");
    sb.append("    hasLanguage: ").append(toIndentedString(hasLanguage)).append("\n");
    sb.append("    mssResponseShort: ").append(toIndentedString(mssResponseShort)).append("\n");
    sb.append("    trustYouID: ").append(toIndentedString(trustYouID)).append("\n");
    sb.append("    trustYouScore: ").append(toIndentedString(trustYouScore)).append("\n");
    sb.append("    trustYouResults: ").append(toIndentedString(trustYouResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

