/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * AdditionalArticleInfos
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class AdditionalArticleInfos {
  @JsonProperty("Language")
  private String language = null;

  @JsonProperty("Elements")
  private Map<String, String> elements = null;

  public AdditionalArticleInfos language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public AdditionalArticleInfos elements(Map<String, String> elements) {
    this.elements = elements;
    return this;
  }

  public AdditionalArticleInfos putElementsItem(String key, String elementsItem) {
    if (this.elements == null) {
      this.elements = new HashMap<>();
    }
    this.elements.put(key, elementsItem);
    return this;
  }

   /**
   * Get elements
   * @return elements
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getElements() {
    return elements;
  }

  public void setElements(Map<String, String> elements) {
    this.elements = elements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdditionalArticleInfos additionalArticleInfos = (AdditionalArticleInfos) o;
    return Objects.equals(this.language, additionalArticleInfos.language) &&
        Objects.equals(this.elements, additionalArticleInfos.elements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, elements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdditionalArticleInfos {\n");
    
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    elements: ").append(toIndentedString(elements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

