/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * Article
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class Article {
  @JsonProperty("Id")
  private String id = null;

  @JsonProperty("Active")
  private Boolean active = null;

  @JsonProperty("Shortname")
  private String shortname = null;

  @JsonProperty("Highlight")
  private Boolean highlight = null;

  @JsonProperty("Type")
  private String type = null;

  @JsonProperty("SubType")
  private String subType = null;

  @JsonProperty("FirstImport")
  private String firstImport = null;

  @JsonProperty("LastChange")
  private String lastChange = null;

  @JsonProperty("SmgActive")
  private Boolean smgActive = null;

  @JsonProperty("ArticleDate")
  private String articleDate = null;

  @JsonProperty("ArticleDateTo")
  private String articleDateTo = null;

  @JsonProperty("OperationSchedule")
  private List<OperationSchedule> operationSchedule = null;

  @JsonProperty("GpsInfo")
  private List<GpsInfo> gpsInfo = null;

  @JsonProperty("GpsTrack")
  private List<GpsTrack> gpsTrack = null;

  @JsonProperty("ImageGallery")
  private List<ImageGallery> imageGallery = null;

  @JsonProperty("Detail")
  private Map<String, Detail> detail = null;

  @JsonProperty("ContactInfos")
  private Map<String, ContactInfos> contactInfos = null;

  @JsonProperty("AdditionalArticleInfos")
  private Map<String, AdditionalArticleInfos> additionalArticleInfos = null;

  @JsonProperty("ArticleLinkInfo")
  private Map<String, ArticleLinkInfo> articleLinkInfo = null;

  @JsonProperty("SmgTags")
  private List<String> smgTags = null;

  @JsonProperty("HasLanguage")
  private List<String> hasLanguage = null;

  public Article id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Article active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Article shortname(String shortname) {
    this.shortname = shortname;
    return this;
  }

   /**
   * Get shortname
   * @return shortname
  **/
  @ApiModelProperty(value = "")
  public String getShortname() {
    return shortname;
  }

  public void setShortname(String shortname) {
    this.shortname = shortname;
  }

  public Article highlight(Boolean highlight) {
    this.highlight = highlight;
    return this;
  }

   /**
   * Get highlight
   * @return highlight
  **/
  @ApiModelProperty(value = "")
  public Boolean isHighlight() {
    return highlight;
  }

  public void setHighlight(Boolean highlight) {
    this.highlight = highlight;
  }

  public Article type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Article subType(String subType) {
    this.subType = subType;
    return this;
  }

   /**
   * Get subType
   * @return subType
  **/
  @ApiModelProperty(value = "")
  public String getSubType() {
    return subType;
  }

  public void setSubType(String subType) {
    this.subType = subType;
  }

  public Article firstImport(String firstImport) {
    this.firstImport = firstImport;
    return this;
  }

   /**
   * Get firstImport
   * @return firstImport
  **/
  @ApiModelProperty(value = "")
  public String getFirstImport() {
    return firstImport;
  }

  public void setFirstImport(String firstImport) {
    this.firstImport = firstImport;
  }

  public Article lastChange(String lastChange) {
    this.lastChange = lastChange;
    return this;
  }

   /**
   * Get lastChange
   * @return lastChange
  **/
  @ApiModelProperty(value = "")
  public String getLastChange() {
    return lastChange;
  }

  public void setLastChange(String lastChange) {
    this.lastChange = lastChange;
  }

  public Article smgActive(Boolean smgActive) {
    this.smgActive = smgActive;
    return this;
  }

   /**
   * Get smgActive
   * @return smgActive
  **/
  @ApiModelProperty(value = "")
  public Boolean isSmgActive() {
    return smgActive;
  }

  public void setSmgActive(Boolean smgActive) {
    this.smgActive = smgActive;
  }

  public Article articleDate(String articleDate) {
    this.articleDate = articleDate;
    return this;
  }

   /**
   * Get articleDate
   * @return articleDate
  **/
  @ApiModelProperty(value = "")
  public String getArticleDate() {
    return articleDate;
  }

  public void setArticleDate(String articleDate) {
    this.articleDate = articleDate;
  }

  public Article articleDateTo(String articleDateTo) {
    this.articleDateTo = articleDateTo;
    return this;
  }

   /**
   * Get articleDateTo
   * @return articleDateTo
  **/
  @ApiModelProperty(value = "")
  public String getArticleDateTo() {
    return articleDateTo;
  }

  public void setArticleDateTo(String articleDateTo) {
    this.articleDateTo = articleDateTo;
  }

  public Article operationSchedule(List<OperationSchedule> operationSchedule) {
    this.operationSchedule = operationSchedule;
    return this;
  }

  public Article addOperationScheduleItem(OperationSchedule operationScheduleItem) {
    if (this.operationSchedule == null) {
      this.operationSchedule = new ArrayList<>();
    }
    this.operationSchedule.add(operationScheduleItem);
    return this;
  }

   /**
   * Get operationSchedule
   * @return operationSchedule
  **/
  @ApiModelProperty(value = "")
  public List<OperationSchedule> getOperationSchedule() {
    return operationSchedule;
  }

  public void setOperationSchedule(List<OperationSchedule> operationSchedule) {
    this.operationSchedule = operationSchedule;
  }

  public Article gpsInfo(List<GpsInfo> gpsInfo) {
    this.gpsInfo = gpsInfo;
    return this;
  }

  public Article addGpsInfoItem(GpsInfo gpsInfoItem) {
    if (this.gpsInfo == null) {
      this.gpsInfo = new ArrayList<>();
    }
    this.gpsInfo.add(gpsInfoItem);
    return this;
  }

   /**
   * Get gpsInfo
   * @return gpsInfo
  **/
  @ApiModelProperty(value = "")
  public List<GpsInfo> getGpsInfo() {
    return gpsInfo;
  }

  public void setGpsInfo(List<GpsInfo> gpsInfo) {
    this.gpsInfo = gpsInfo;
  }

  public Article gpsTrack(List<GpsTrack> gpsTrack) {
    this.gpsTrack = gpsTrack;
    return this;
  }

  public Article addGpsTrackItem(GpsTrack gpsTrackItem) {
    if (this.gpsTrack == null) {
      this.gpsTrack = new ArrayList<>();
    }
    this.gpsTrack.add(gpsTrackItem);
    return this;
  }

   /**
   * Get gpsTrack
   * @return gpsTrack
  **/
  @ApiModelProperty(value = "")
  public List<GpsTrack> getGpsTrack() {
    return gpsTrack;
  }

  public void setGpsTrack(List<GpsTrack> gpsTrack) {
    this.gpsTrack = gpsTrack;
  }

  public Article imageGallery(List<ImageGallery> imageGallery) {
    this.imageGallery = imageGallery;
    return this;
  }

  public Article addImageGalleryItem(ImageGallery imageGalleryItem) {
    if (this.imageGallery == null) {
      this.imageGallery = new ArrayList<>();
    }
    this.imageGallery.add(imageGalleryItem);
    return this;
  }

   /**
   * Get imageGallery
   * @return imageGallery
  **/
  @ApiModelProperty(value = "")
  public List<ImageGallery> getImageGallery() {
    return imageGallery;
  }

  public void setImageGallery(List<ImageGallery> imageGallery) {
    this.imageGallery = imageGallery;
  }

  public Article detail(Map<String, Detail> detail) {
    this.detail = detail;
    return this;
  }

  public Article putDetailItem(String key, Detail detailItem) {
    if (this.detail == null) {
      this.detail = new HashMap<>();
    }
    this.detail.put(key, detailItem);
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @ApiModelProperty(value = "")
  public Map<String, Detail> getDetail() {
    return detail;
  }

  public void setDetail(Map<String, Detail> detail) {
    this.detail = detail;
  }

  public Article contactInfos(Map<String, ContactInfos> contactInfos) {
    this.contactInfos = contactInfos;
    return this;
  }

  public Article putContactInfosItem(String key, ContactInfos contactInfosItem) {
    if (this.contactInfos == null) {
      this.contactInfos = new HashMap<>();
    }
    this.contactInfos.put(key, contactInfosItem);
    return this;
  }

   /**
   * Get contactInfos
   * @return contactInfos
  **/
  @ApiModelProperty(value = "")
  public Map<String, ContactInfos> getContactInfos() {
    return contactInfos;
  }

  public void setContactInfos(Map<String, ContactInfos> contactInfos) {
    this.contactInfos = contactInfos;
  }

  public Article additionalArticleInfos(Map<String, AdditionalArticleInfos> additionalArticleInfos) {
    this.additionalArticleInfos = additionalArticleInfos;
    return this;
  }

  public Article putAdditionalArticleInfosItem(String key, AdditionalArticleInfos additionalArticleInfosItem) {
    if (this.additionalArticleInfos == null) {
      this.additionalArticleInfos = new HashMap<>();
    }
    this.additionalArticleInfos.put(key, additionalArticleInfosItem);
    return this;
  }

   /**
   * Get additionalArticleInfos
   * @return additionalArticleInfos
  **/
  @ApiModelProperty(value = "")
  public Map<String, AdditionalArticleInfos> getAdditionalArticleInfos() {
    return additionalArticleInfos;
  }

  public void setAdditionalArticleInfos(Map<String, AdditionalArticleInfos> additionalArticleInfos) {
    this.additionalArticleInfos = additionalArticleInfos;
  }

  public Article articleLinkInfo(Map<String, ArticleLinkInfo> articleLinkInfo) {
    this.articleLinkInfo = articleLinkInfo;
    return this;
  }

  public Article putArticleLinkInfoItem(String key, ArticleLinkInfo articleLinkInfoItem) {
    if (this.articleLinkInfo == null) {
      this.articleLinkInfo = new HashMap<>();
    }
    this.articleLinkInfo.put(key, articleLinkInfoItem);
    return this;
  }

   /**
   * Get articleLinkInfo
   * @return articleLinkInfo
  **/
  @ApiModelProperty(value = "")
  public Map<String, ArticleLinkInfo> getArticleLinkInfo() {
    return articleLinkInfo;
  }

  public void setArticleLinkInfo(Map<String, ArticleLinkInfo> articleLinkInfo) {
    this.articleLinkInfo = articleLinkInfo;
  }

  public Article smgTags(List<String> smgTags) {
    this.smgTags = smgTags;
    return this;
  }

  public Article addSmgTagsItem(String smgTagsItem) {
    if (this.smgTags == null) {
      this.smgTags = new ArrayList<>();
    }
    this.smgTags.add(smgTagsItem);
    return this;
  }

   /**
   * Get smgTags
   * @return smgTags
  **/
  @ApiModelProperty(value = "")
  public List<String> getSmgTags() {
    return smgTags;
  }

  public void setSmgTags(List<String> smgTags) {
    this.smgTags = smgTags;
  }

  public Article hasLanguage(List<String> hasLanguage) {
    this.hasLanguage = hasLanguage;
    return this;
  }

  public Article addHasLanguageItem(String hasLanguageItem) {
    if (this.hasLanguage == null) {
      this.hasLanguage = new ArrayList<>();
    }
    this.hasLanguage.add(hasLanguageItem);
    return this;
  }

   /**
   * Get hasLanguage
   * @return hasLanguage
  **/
  @ApiModelProperty(value = "")
  public List<String> getHasLanguage() {
    return hasLanguage;
  }

  public void setHasLanguage(List<String> hasLanguage) {
    this.hasLanguage = hasLanguage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Article article = (Article) o;
    return Objects.equals(this.id, article.id) &&
        Objects.equals(this.active, article.active) &&
        Objects.equals(this.shortname, article.shortname) &&
        Objects.equals(this.highlight, article.highlight) &&
        Objects.equals(this.type, article.type) &&
        Objects.equals(this.subType, article.subType) &&
        Objects.equals(this.firstImport, article.firstImport) &&
        Objects.equals(this.lastChange, article.lastChange) &&
        Objects.equals(this.smgActive, article.smgActive) &&
        Objects.equals(this.articleDate, article.articleDate) &&
        Objects.equals(this.articleDateTo, article.articleDateTo) &&
        Objects.equals(this.operationSchedule, article.operationSchedule) &&
        Objects.equals(this.gpsInfo, article.gpsInfo) &&
        Objects.equals(this.gpsTrack, article.gpsTrack) &&
        Objects.equals(this.imageGallery, article.imageGallery) &&
        Objects.equals(this.detail, article.detail) &&
        Objects.equals(this.contactInfos, article.contactInfos) &&
        Objects.equals(this.additionalArticleInfos, article.additionalArticleInfos) &&
        Objects.equals(this.articleLinkInfo, article.articleLinkInfo) &&
        Objects.equals(this.smgTags, article.smgTags) &&
        Objects.equals(this.hasLanguage, article.hasLanguage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, active, shortname, highlight, type, subType, firstImport, lastChange, smgActive, articleDate, articleDateTo, operationSchedule, gpsInfo, gpsTrack, imageGallery, detail, contactInfos, additionalArticleInfos, articleLinkInfo, smgTags, hasLanguage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Article {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    shortname: ").append(toIndentedString(shortname)).append("\n");
    sb.append("    highlight: ").append(toIndentedString(highlight)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    subType: ").append(toIndentedString(subType)).append("\n");
    sb.append("    firstImport: ").append(toIndentedString(firstImport)).append("\n");
    sb.append("    lastChange: ").append(toIndentedString(lastChange)).append("\n");
    sb.append("    smgActive: ").append(toIndentedString(smgActive)).append("\n");
    sb.append("    articleDate: ").append(toIndentedString(articleDate)).append("\n");
    sb.append("    articleDateTo: ").append(toIndentedString(articleDateTo)).append("\n");
    sb.append("    operationSchedule: ").append(toIndentedString(operationSchedule)).append("\n");
    sb.append("    gpsInfo: ").append(toIndentedString(gpsInfo)).append("\n");
    sb.append("    gpsTrack: ").append(toIndentedString(gpsTrack)).append("\n");
    sb.append("    imageGallery: ").append(toIndentedString(imageGallery)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    contactInfos: ").append(toIndentedString(contactInfos)).append("\n");
    sb.append("    additionalArticleInfos: ").append(toIndentedString(additionalArticleInfos)).append("\n");
    sb.append("    articleLinkInfo: ").append(toIndentedString(articleLinkInfo)).append("\n");
    sb.append("    smgTags: ").append(toIndentedString(smgTags)).append("\n");
    sb.append("    hasLanguage: ").append(toIndentedString(hasLanguage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

