/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.hackthealps.codemates.staylocalpaylocal.opendata.model.BezirksForecast;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * BezirksWeather
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class BezirksWeather {
  @JsonProperty("Id")
  private Integer id = null;

  @JsonProperty("DistrictName")
  private String districtName = null;

  @JsonProperty("date")
  private OffsetDateTime date = null;

  @JsonProperty("TourismVereinIds")
  private List<String> tourismVereinIds = null;

  @JsonProperty("BezirksForecast")
  private List<BezirksForecast> bezirksForecast = null;

  public BezirksWeather id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public BezirksWeather districtName(String districtName) {
    this.districtName = districtName;
    return this;
  }

   /**
   * Get districtName
   * @return districtName
  **/
  @ApiModelProperty(value = "")
  public String getDistrictName() {
    return districtName;
  }

  public void setDistrictName(String districtName) {
    this.districtName = districtName;
  }

  public BezirksWeather date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public BezirksWeather tourismVereinIds(List<String> tourismVereinIds) {
    this.tourismVereinIds = tourismVereinIds;
    return this;
  }

  public BezirksWeather addTourismVereinIdsItem(String tourismVereinIdsItem) {
    if (this.tourismVereinIds == null) {
      this.tourismVereinIds = new ArrayList<>();
    }
    this.tourismVereinIds.add(tourismVereinIdsItem);
    return this;
  }

   /**
   * Get tourismVereinIds
   * @return tourismVereinIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getTourismVereinIds() {
    return tourismVereinIds;
  }

  public void setTourismVereinIds(List<String> tourismVereinIds) {
    this.tourismVereinIds = tourismVereinIds;
  }

  public BezirksWeather bezirksForecast(List<BezirksForecast> bezirksForecast) {
    this.bezirksForecast = bezirksForecast;
    return this;
  }

  public BezirksWeather addBezirksForecastItem(BezirksForecast bezirksForecastItem) {
    if (this.bezirksForecast == null) {
      this.bezirksForecast = new ArrayList<>();
    }
    this.bezirksForecast.add(bezirksForecastItem);
    return this;
  }

   /**
   * Get bezirksForecast
   * @return bezirksForecast
  **/
  @ApiModelProperty(value = "")
  public List<BezirksForecast> getBezirksForecast() {
    return bezirksForecast;
  }

  public void setBezirksForecast(List<BezirksForecast> bezirksForecast) {
    this.bezirksForecast = bezirksForecast;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BezirksWeather bezirksWeather = (BezirksWeather) o;
    return Objects.equals(this.id, bezirksWeather.id) &&
        Objects.equals(this.districtName, bezirksWeather.districtName) &&
        Objects.equals(this.date, bezirksWeather.date) &&
        Objects.equals(this.tourismVereinIds, bezirksWeather.tourismVereinIds) &&
        Objects.equals(this.bezirksForecast, bezirksWeather.bezirksForecast);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, districtName, date, tourismVereinIds, bezirksForecast);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BezirksWeather {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    districtName: ").append(toIndentedString(districtName)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    tourismVereinIds: ").append(toIndentedString(tourismVereinIds)).append("\n");
    sb.append("    bezirksForecast: ").append(toIndentedString(bezirksForecast)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

