/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * EventTypes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class EventTypes {
  @JsonProperty("Id")
  private String id = null;

  @JsonProperty("Bitmask")
  private Integer bitmask = null;

  @JsonProperty("Type")
  private String type = null;

  @JsonProperty("TypeDesc")
  private Map<String, String> typeDesc = null;

  public EventTypes id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EventTypes bitmask(Integer bitmask) {
    this.bitmask = bitmask;
    return this;
  }

   /**
   * Get bitmask
   * @return bitmask
  **/
  @ApiModelProperty(value = "")
  public Integer getBitmask() {
    return bitmask;
  }

  public void setBitmask(Integer bitmask) {
    this.bitmask = bitmask;
  }

  public EventTypes type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public EventTypes typeDesc(Map<String, String> typeDesc) {
    this.typeDesc = typeDesc;
    return this;
  }

  public EventTypes putTypeDescItem(String key, String typeDescItem) {
    if (this.typeDesc == null) {
      this.typeDesc = new HashMap<>();
    }
    this.typeDesc.put(key, typeDescItem);
    return this;
  }

   /**
   * Get typeDesc
   * @return typeDesc
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getTypeDesc() {
    return typeDesc;
  }

  public void setTypeDesc(Map<String, String> typeDesc) {
    this.typeDesc = typeDesc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventTypes eventTypes = (EventTypes) o;
    return Objects.equals(this.id, eventTypes.id) &&
        Objects.equals(this.bitmask, eventTypes.bitmask) &&
        Objects.equals(this.type, eventTypes.type) &&
        Objects.equals(this.typeDesc, eventTypes.typeDesc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, bitmask, type, typeDesc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventTypes {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bitmask: ").append(toIndentedString(bitmask)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    typeDesc: ").append(toIndentedString(typeDesc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

