/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * EventShort
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class EventShort {
  @JsonProperty("Id")
  private String id = null;

  @JsonProperty("Source")
  private String source = null;

  @JsonProperty("EventLocation")
  private String eventLocation = null;

  @JsonProperty("EventId")
  private Integer eventId = null;

  @JsonProperty("EventDescription")
  private String eventDescription = null;

  @JsonProperty("EventDescriptionDE")
  private String eventDescriptionDE = null;

  @JsonProperty("EventDescriptionIT")
  private String eventDescriptionIT = null;

  @JsonProperty("EventDescriptionEN")
  private String eventDescriptionEN = null;

  @JsonProperty("AnchorVenue")
  private String anchorVenue = null;

  @JsonProperty("AnchorVenueShort")
  private String anchorVenueShort = null;

  @JsonProperty("ChangedOn")
  private String changedOn = null;

  @JsonProperty("StartDate")
  private String startDate = null;

  @JsonProperty("EndDate")
  private String endDate = null;

  @JsonProperty("StartDateUTC")
  private Double startDateUTC = null;

  @JsonProperty("EndDateUTC")
  private Double endDateUTC = null;

  @JsonProperty("WebAddress")
  private String webAddress = null;

  @JsonProperty("Display1")
  private String display1 = null;

  @JsonProperty("Display2")
  private String display2 = null;

  @JsonProperty("Display3")
  private String display3 = null;

  @JsonProperty("Display4")
  private String display4 = null;

  @JsonProperty("Display5")
  private String display5 = null;

  @JsonProperty("Display6")
  private String display6 = null;

  @JsonProperty("Display7")
  private String display7 = null;

  @JsonProperty("Display8")
  private String display8 = null;

  @JsonProperty("Display9")
  private String display9 = null;

  @JsonProperty("CompanyName")
  private String companyName = null;

  @JsonProperty("CompanyId")
  private String companyId = null;

  @JsonProperty("CompanyAddressLine1")
  private String companyAddressLine1 = null;

  @JsonProperty("CompanyAddressLine2")
  private String companyAddressLine2 = null;

  @JsonProperty("CompanyAddressLine3")
  private String companyAddressLine3 = null;

  @JsonProperty("CompanyPostalCode")
  private String companyPostalCode = null;

  @JsonProperty("CompanyCity")
  private String companyCity = null;

  @JsonProperty("CompanyCountry")
  private String companyCountry = null;

  @JsonProperty("CompanyPhone")
  private String companyPhone = null;

  @JsonProperty("CompanyFax")
  private String companyFax = null;

  @JsonProperty("CompanyMail")
  private String companyMail = null;

  @JsonProperty("CompanyUrl")
  private String companyUrl = null;

  @JsonProperty("ContactCode")
  private String contactCode = null;

  @JsonProperty("ContactFirstName")
  private String contactFirstName = null;

  @JsonProperty("ContactLastName")
  private String contactLastName = null;

  @JsonProperty("ContactPhone")
  private String contactPhone = null;

  @JsonProperty("ContactCell")
  private String contactCell = null;

  @JsonProperty("ContactFax")
  private String contactFax = null;

  @JsonProperty("ContactEmail")
  private String contactEmail = null;

  @JsonProperty("ContactAddressLine1")
  private String contactAddressLine1 = null;

  @JsonProperty("ContactAddressLine2")
  private String contactAddressLine2 = null;

  @JsonProperty("ContactAddressLine3")
  private String contactAddressLine3 = null;

  @JsonProperty("ContactPostalCode")
  private String contactPostalCode = null;

  @JsonProperty("ContactCity")
  private String contactCity = null;

  @JsonProperty("ContactCountry")
  private String contactCountry = null;

  @JsonProperty("RoomBooked")
  private List<RoomBooked> roomBooked = null;

  public EventShort id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EventShort source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @ApiModelProperty(value = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public EventShort eventLocation(String eventLocation) {
    this.eventLocation = eventLocation;
    return this;
  }

   /**
   * Get eventLocation
   * @return eventLocation
  **/
  @ApiModelProperty(value = "")
  public String getEventLocation() {
    return eventLocation;
  }

  public void setEventLocation(String eventLocation) {
    this.eventLocation = eventLocation;
  }

  public EventShort eventId(Integer eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @ApiModelProperty(value = "")
  public Integer getEventId() {
    return eventId;
  }

  public void setEventId(Integer eventId) {
    this.eventId = eventId;
  }

  public EventShort eventDescription(String eventDescription) {
    this.eventDescription = eventDescription;
    return this;
  }

   /**
   * Get eventDescription
   * @return eventDescription
  **/
  @ApiModelProperty(value = "")
  public String getEventDescription() {
    return eventDescription;
  }

  public void setEventDescription(String eventDescription) {
    this.eventDescription = eventDescription;
  }

  public EventShort eventDescriptionDE(String eventDescriptionDE) {
    this.eventDescriptionDE = eventDescriptionDE;
    return this;
  }

   /**
   * Get eventDescriptionDE
   * @return eventDescriptionDE
  **/
  @ApiModelProperty(value = "")
  public String getEventDescriptionDE() {
    return eventDescriptionDE;
  }

  public void setEventDescriptionDE(String eventDescriptionDE) {
    this.eventDescriptionDE = eventDescriptionDE;
  }

  public EventShort eventDescriptionIT(String eventDescriptionIT) {
    this.eventDescriptionIT = eventDescriptionIT;
    return this;
  }

   /**
   * Get eventDescriptionIT
   * @return eventDescriptionIT
  **/
  @ApiModelProperty(value = "")
  public String getEventDescriptionIT() {
    return eventDescriptionIT;
  }

  public void setEventDescriptionIT(String eventDescriptionIT) {
    this.eventDescriptionIT = eventDescriptionIT;
  }

  public EventShort eventDescriptionEN(String eventDescriptionEN) {
    this.eventDescriptionEN = eventDescriptionEN;
    return this;
  }

   /**
   * Get eventDescriptionEN
   * @return eventDescriptionEN
  **/
  @ApiModelProperty(value = "")
  public String getEventDescriptionEN() {
    return eventDescriptionEN;
  }

  public void setEventDescriptionEN(String eventDescriptionEN) {
    this.eventDescriptionEN = eventDescriptionEN;
  }

  public EventShort anchorVenue(String anchorVenue) {
    this.anchorVenue = anchorVenue;
    return this;
  }

   /**
   * Get anchorVenue
   * @return anchorVenue
  **/
  @ApiModelProperty(value = "")
  public String getAnchorVenue() {
    return anchorVenue;
  }

  public void setAnchorVenue(String anchorVenue) {
    this.anchorVenue = anchorVenue;
  }

  public EventShort anchorVenueShort(String anchorVenueShort) {
    this.anchorVenueShort = anchorVenueShort;
    return this;
  }

   /**
   * Get anchorVenueShort
   * @return anchorVenueShort
  **/
  @ApiModelProperty(value = "")
  public String getAnchorVenueShort() {
    return anchorVenueShort;
  }

  public void setAnchorVenueShort(String anchorVenueShort) {
    this.anchorVenueShort = anchorVenueShort;
  }

  public EventShort changedOn(String changedOn) {
    this.changedOn = changedOn;
    return this;
  }

   /**
   * Get changedOn
   * @return changedOn
  **/
  @ApiModelProperty(value = "")
  public String getChangedOn() {
    return changedOn;
  }

  public void setChangedOn(String changedOn) {
    this.changedOn = changedOn;
  }

  public EventShort startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public EventShort endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(value = "")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public EventShort startDateUTC(Double startDateUTC) {
    this.startDateUTC = startDateUTC;
    return this;
  }

   /**
   * Get startDateUTC
   * @return startDateUTC
  **/
  @ApiModelProperty(value = "")
  public Double getStartDateUTC() {
    return startDateUTC;
  }

  public void setStartDateUTC(Double startDateUTC) {
    this.startDateUTC = startDateUTC;
  }

  public EventShort endDateUTC(Double endDateUTC) {
    this.endDateUTC = endDateUTC;
    return this;
  }

   /**
   * Get endDateUTC
   * @return endDateUTC
  **/
  @ApiModelProperty(value = "")
  public Double getEndDateUTC() {
    return endDateUTC;
  }

  public void setEndDateUTC(Double endDateUTC) {
    this.endDateUTC = endDateUTC;
  }

  public EventShort webAddress(String webAddress) {
    this.webAddress = webAddress;
    return this;
  }

   /**
   * Get webAddress
   * @return webAddress
  **/
  @ApiModelProperty(value = "")
  public String getWebAddress() {
    return webAddress;
  }

  public void setWebAddress(String webAddress) {
    this.webAddress = webAddress;
  }

  public EventShort display1(String display1) {
    this.display1 = display1;
    return this;
  }

   /**
   * Get display1
   * @return display1
  **/
  @ApiModelProperty(value = "")
  public String getDisplay1() {
    return display1;
  }

  public void setDisplay1(String display1) {
    this.display1 = display1;
  }

  public EventShort display2(String display2) {
    this.display2 = display2;
    return this;
  }

   /**
   * Get display2
   * @return display2
  **/
  @ApiModelProperty(value = "")
  public String getDisplay2() {
    return display2;
  }

  public void setDisplay2(String display2) {
    this.display2 = display2;
  }

  public EventShort display3(String display3) {
    this.display3 = display3;
    return this;
  }

   /**
   * Get display3
   * @return display3
  **/
  @ApiModelProperty(value = "")
  public String getDisplay3() {
    return display3;
  }

  public void setDisplay3(String display3) {
    this.display3 = display3;
  }

  public EventShort display4(String display4) {
    this.display4 = display4;
    return this;
  }

   /**
   * Get display4
   * @return display4
  **/
  @ApiModelProperty(value = "")
  public String getDisplay4() {
    return display4;
  }

  public void setDisplay4(String display4) {
    this.display4 = display4;
  }

  public EventShort display5(String display5) {
    this.display5 = display5;
    return this;
  }

   /**
   * Get display5
   * @return display5
  **/
  @ApiModelProperty(value = "")
  public String getDisplay5() {
    return display5;
  }

  public void setDisplay5(String display5) {
    this.display5 = display5;
  }

  public EventShort display6(String display6) {
    this.display6 = display6;
    return this;
  }

   /**
   * Get display6
   * @return display6
  **/
  @ApiModelProperty(value = "")
  public String getDisplay6() {
    return display6;
  }

  public void setDisplay6(String display6) {
    this.display6 = display6;
  }

  public EventShort display7(String display7) {
    this.display7 = display7;
    return this;
  }

   /**
   * Get display7
   * @return display7
  **/
  @ApiModelProperty(value = "")
  public String getDisplay7() {
    return display7;
  }

  public void setDisplay7(String display7) {
    this.display7 = display7;
  }

  public EventShort display8(String display8) {
    this.display8 = display8;
    return this;
  }

   /**
   * Get display8
   * @return display8
  **/
  @ApiModelProperty(value = "")
  public String getDisplay8() {
    return display8;
  }

  public void setDisplay8(String display8) {
    this.display8 = display8;
  }

  public EventShort display9(String display9) {
    this.display9 = display9;
    return this;
  }

   /**
   * Get display9
   * @return display9
  **/
  @ApiModelProperty(value = "")
  public String getDisplay9() {
    return display9;
  }

  public void setDisplay9(String display9) {
    this.display9 = display9;
  }

  public EventShort companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @ApiModelProperty(value = "")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public EventShort companyId(String companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  @ApiModelProperty(value = "")
  public String getCompanyId() {
    return companyId;
  }

  public void setCompanyId(String companyId) {
    this.companyId = companyId;
  }

  public EventShort companyAddressLine1(String companyAddressLine1) {
    this.companyAddressLine1 = companyAddressLine1;
    return this;
  }

   /**
   * Get companyAddressLine1
   * @return companyAddressLine1
  **/
  @ApiModelProperty(value = "")
  public String getCompanyAddressLine1() {
    return companyAddressLine1;
  }

  public void setCompanyAddressLine1(String companyAddressLine1) {
    this.companyAddressLine1 = companyAddressLine1;
  }

  public EventShort companyAddressLine2(String companyAddressLine2) {
    this.companyAddressLine2 = companyAddressLine2;
    return this;
  }

   /**
   * Get companyAddressLine2
   * @return companyAddressLine2
  **/
  @ApiModelProperty(value = "")
  public String getCompanyAddressLine2() {
    return companyAddressLine2;
  }

  public void setCompanyAddressLine2(String companyAddressLine2) {
    this.companyAddressLine2 = companyAddressLine2;
  }

  public EventShort companyAddressLine3(String companyAddressLine3) {
    this.companyAddressLine3 = companyAddressLine3;
    return this;
  }

   /**
   * Get companyAddressLine3
   * @return companyAddressLine3
  **/
  @ApiModelProperty(value = "")
  public String getCompanyAddressLine3() {
    return companyAddressLine3;
  }

  public void setCompanyAddressLine3(String companyAddressLine3) {
    this.companyAddressLine3 = companyAddressLine3;
  }

  public EventShort companyPostalCode(String companyPostalCode) {
    this.companyPostalCode = companyPostalCode;
    return this;
  }

   /**
   * Get companyPostalCode
   * @return companyPostalCode
  **/
  @ApiModelProperty(value = "")
  public String getCompanyPostalCode() {
    return companyPostalCode;
  }

  public void setCompanyPostalCode(String companyPostalCode) {
    this.companyPostalCode = companyPostalCode;
  }

  public EventShort companyCity(String companyCity) {
    this.companyCity = companyCity;
    return this;
  }

   /**
   * Get companyCity
   * @return companyCity
  **/
  @ApiModelProperty(value = "")
  public String getCompanyCity() {
    return companyCity;
  }

  public void setCompanyCity(String companyCity) {
    this.companyCity = companyCity;
  }

  public EventShort companyCountry(String companyCountry) {
    this.companyCountry = companyCountry;
    return this;
  }

   /**
   * Get companyCountry
   * @return companyCountry
  **/
  @ApiModelProperty(value = "")
  public String getCompanyCountry() {
    return companyCountry;
  }

  public void setCompanyCountry(String companyCountry) {
    this.companyCountry = companyCountry;
  }

  public EventShort companyPhone(String companyPhone) {
    this.companyPhone = companyPhone;
    return this;
  }

   /**
   * Get companyPhone
   * @return companyPhone
  **/
  @ApiModelProperty(value = "")
  public String getCompanyPhone() {
    return companyPhone;
  }

  public void setCompanyPhone(String companyPhone) {
    this.companyPhone = companyPhone;
  }

  public EventShort companyFax(String companyFax) {
    this.companyFax = companyFax;
    return this;
  }

   /**
   * Get companyFax
   * @return companyFax
  **/
  @ApiModelProperty(value = "")
  public String getCompanyFax() {
    return companyFax;
  }

  public void setCompanyFax(String companyFax) {
    this.companyFax = companyFax;
  }

  public EventShort companyMail(String companyMail) {
    this.companyMail = companyMail;
    return this;
  }

   /**
   * Get companyMail
   * @return companyMail
  **/
  @ApiModelProperty(value = "")
  public String getCompanyMail() {
    return companyMail;
  }

  public void setCompanyMail(String companyMail) {
    this.companyMail = companyMail;
  }

  public EventShort companyUrl(String companyUrl) {
    this.companyUrl = companyUrl;
    return this;
  }

   /**
   * Get companyUrl
   * @return companyUrl
  **/
  @ApiModelProperty(value = "")
  public String getCompanyUrl() {
    return companyUrl;
  }

  public void setCompanyUrl(String companyUrl) {
    this.companyUrl = companyUrl;
  }

  public EventShort contactCode(String contactCode) {
    this.contactCode = contactCode;
    return this;
  }

   /**
   * Get contactCode
   * @return contactCode
  **/
  @ApiModelProperty(value = "")
  public String getContactCode() {
    return contactCode;
  }

  public void setContactCode(String contactCode) {
    this.contactCode = contactCode;
  }

  public EventShort contactFirstName(String contactFirstName) {
    this.contactFirstName = contactFirstName;
    return this;
  }

   /**
   * Get contactFirstName
   * @return contactFirstName
  **/
  @ApiModelProperty(value = "")
  public String getContactFirstName() {
    return contactFirstName;
  }

  public void setContactFirstName(String contactFirstName) {
    this.contactFirstName = contactFirstName;
  }

  public EventShort contactLastName(String contactLastName) {
    this.contactLastName = contactLastName;
    return this;
  }

   /**
   * Get contactLastName
   * @return contactLastName
  **/
  @ApiModelProperty(value = "")
  public String getContactLastName() {
    return contactLastName;
  }

  public void setContactLastName(String contactLastName) {
    this.contactLastName = contactLastName;
  }

  public EventShort contactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
    return this;
  }

   /**
   * Get contactPhone
   * @return contactPhone
  **/
  @ApiModelProperty(value = "")
  public String getContactPhone() {
    return contactPhone;
  }

  public void setContactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
  }

  public EventShort contactCell(String contactCell) {
    this.contactCell = contactCell;
    return this;
  }

   /**
   * Get contactCell
   * @return contactCell
  **/
  @ApiModelProperty(value = "")
  public String getContactCell() {
    return contactCell;
  }

  public void setContactCell(String contactCell) {
    this.contactCell = contactCell;
  }

  public EventShort contactFax(String contactFax) {
    this.contactFax = contactFax;
    return this;
  }

   /**
   * Get contactFax
   * @return contactFax
  **/
  @ApiModelProperty(value = "")
  public String getContactFax() {
    return contactFax;
  }

  public void setContactFax(String contactFax) {
    this.contactFax = contactFax;
  }

  public EventShort contactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

   /**
   * Get contactEmail
   * @return contactEmail
  **/
  @ApiModelProperty(value = "")
  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public EventShort contactAddressLine1(String contactAddressLine1) {
    this.contactAddressLine1 = contactAddressLine1;
    return this;
  }

   /**
   * Get contactAddressLine1
   * @return contactAddressLine1
  **/
  @ApiModelProperty(value = "")
  public String getContactAddressLine1() {
    return contactAddressLine1;
  }

  public void setContactAddressLine1(String contactAddressLine1) {
    this.contactAddressLine1 = contactAddressLine1;
  }

  public EventShort contactAddressLine2(String contactAddressLine2) {
    this.contactAddressLine2 = contactAddressLine2;
    return this;
  }

   /**
   * Get contactAddressLine2
   * @return contactAddressLine2
  **/
  @ApiModelProperty(value = "")
  public String getContactAddressLine2() {
    return contactAddressLine2;
  }

  public void setContactAddressLine2(String contactAddressLine2) {
    this.contactAddressLine2 = contactAddressLine2;
  }

  public EventShort contactAddressLine3(String contactAddressLine3) {
    this.contactAddressLine3 = contactAddressLine3;
    return this;
  }

   /**
   * Get contactAddressLine3
   * @return contactAddressLine3
  **/
  @ApiModelProperty(value = "")
  public String getContactAddressLine3() {
    return contactAddressLine3;
  }

  public void setContactAddressLine3(String contactAddressLine3) {
    this.contactAddressLine3 = contactAddressLine3;
  }

  public EventShort contactPostalCode(String contactPostalCode) {
    this.contactPostalCode = contactPostalCode;
    return this;
  }

   /**
   * Get contactPostalCode
   * @return contactPostalCode
  **/
  @ApiModelProperty(value = "")
  public String getContactPostalCode() {
    return contactPostalCode;
  }

  public void setContactPostalCode(String contactPostalCode) {
    this.contactPostalCode = contactPostalCode;
  }

  public EventShort contactCity(String contactCity) {
    this.contactCity = contactCity;
    return this;
  }

   /**
   * Get contactCity
   * @return contactCity
  **/
  @ApiModelProperty(value = "")
  public String getContactCity() {
    return contactCity;
  }

  public void setContactCity(String contactCity) {
    this.contactCity = contactCity;
  }

  public EventShort contactCountry(String contactCountry) {
    this.contactCountry = contactCountry;
    return this;
  }

   /**
   * Get contactCountry
   * @return contactCountry
  **/
  @ApiModelProperty(value = "")
  public String getContactCountry() {
    return contactCountry;
  }

  public void setContactCountry(String contactCountry) {
    this.contactCountry = contactCountry;
  }

  public EventShort roomBooked(List<RoomBooked> roomBooked) {
    this.roomBooked = roomBooked;
    return this;
  }

  public EventShort addRoomBookedItem(RoomBooked roomBookedItem) {
    if (this.roomBooked == null) {
      this.roomBooked = new ArrayList<>();
    }
    this.roomBooked.add(roomBookedItem);
    return this;
  }

   /**
   * Get roomBooked
   * @return roomBooked
  **/
  @ApiModelProperty(value = "")
  public List<RoomBooked> getRoomBooked() {
    return roomBooked;
  }

  public void setRoomBooked(List<RoomBooked> roomBooked) {
    this.roomBooked = roomBooked;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventShort eventShort = (EventShort) o;
    return Objects.equals(this.id, eventShort.id) &&
        Objects.equals(this.source, eventShort.source) &&
        Objects.equals(this.eventLocation, eventShort.eventLocation) &&
        Objects.equals(this.eventId, eventShort.eventId) &&
        Objects.equals(this.eventDescription, eventShort.eventDescription) &&
        Objects.equals(this.eventDescriptionDE, eventShort.eventDescriptionDE) &&
        Objects.equals(this.eventDescriptionIT, eventShort.eventDescriptionIT) &&
        Objects.equals(this.eventDescriptionEN, eventShort.eventDescriptionEN) &&
        Objects.equals(this.anchorVenue, eventShort.anchorVenue) &&
        Objects.equals(this.anchorVenueShort, eventShort.anchorVenueShort) &&
        Objects.equals(this.changedOn, eventShort.changedOn) &&
        Objects.equals(this.startDate, eventShort.startDate) &&
        Objects.equals(this.endDate, eventShort.endDate) &&
        Objects.equals(this.startDateUTC, eventShort.startDateUTC) &&
        Objects.equals(this.endDateUTC, eventShort.endDateUTC) &&
        Objects.equals(this.webAddress, eventShort.webAddress) &&
        Objects.equals(this.display1, eventShort.display1) &&
        Objects.equals(this.display2, eventShort.display2) &&
        Objects.equals(this.display3, eventShort.display3) &&
        Objects.equals(this.display4, eventShort.display4) &&
        Objects.equals(this.display5, eventShort.display5) &&
        Objects.equals(this.display6, eventShort.display6) &&
        Objects.equals(this.display7, eventShort.display7) &&
        Objects.equals(this.display8, eventShort.display8) &&
        Objects.equals(this.display9, eventShort.display9) &&
        Objects.equals(this.companyName, eventShort.companyName) &&
        Objects.equals(this.companyId, eventShort.companyId) &&
        Objects.equals(this.companyAddressLine1, eventShort.companyAddressLine1) &&
        Objects.equals(this.companyAddressLine2, eventShort.companyAddressLine2) &&
        Objects.equals(this.companyAddressLine3, eventShort.companyAddressLine3) &&
        Objects.equals(this.companyPostalCode, eventShort.companyPostalCode) &&
        Objects.equals(this.companyCity, eventShort.companyCity) &&
        Objects.equals(this.companyCountry, eventShort.companyCountry) &&
        Objects.equals(this.companyPhone, eventShort.companyPhone) &&
        Objects.equals(this.companyFax, eventShort.companyFax) &&
        Objects.equals(this.companyMail, eventShort.companyMail) &&
        Objects.equals(this.companyUrl, eventShort.companyUrl) &&
        Objects.equals(this.contactCode, eventShort.contactCode) &&
        Objects.equals(this.contactFirstName, eventShort.contactFirstName) &&
        Objects.equals(this.contactLastName, eventShort.contactLastName) &&
        Objects.equals(this.contactPhone, eventShort.contactPhone) &&
        Objects.equals(this.contactCell, eventShort.contactCell) &&
        Objects.equals(this.contactFax, eventShort.contactFax) &&
        Objects.equals(this.contactEmail, eventShort.contactEmail) &&
        Objects.equals(this.contactAddressLine1, eventShort.contactAddressLine1) &&
        Objects.equals(this.contactAddressLine2, eventShort.contactAddressLine2) &&
        Objects.equals(this.contactAddressLine3, eventShort.contactAddressLine3) &&
        Objects.equals(this.contactPostalCode, eventShort.contactPostalCode) &&
        Objects.equals(this.contactCity, eventShort.contactCity) &&
        Objects.equals(this.contactCountry, eventShort.contactCountry) &&
        Objects.equals(this.roomBooked, eventShort.roomBooked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, source, eventLocation, eventId, eventDescription, eventDescriptionDE, eventDescriptionIT, eventDescriptionEN, anchorVenue, anchorVenueShort, changedOn, startDate, endDate, startDateUTC, endDateUTC, webAddress, display1, display2, display3, display4, display5, display6, display7, display8, display9, companyName, companyId, companyAddressLine1, companyAddressLine2, companyAddressLine3, companyPostalCode, companyCity, companyCountry, companyPhone, companyFax, companyMail, companyUrl, contactCode, contactFirstName, contactLastName, contactPhone, contactCell, contactFax, contactEmail, contactAddressLine1, contactAddressLine2, contactAddressLine3, contactPostalCode, contactCity, contactCountry, roomBooked);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventShort {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    eventLocation: ").append(toIndentedString(eventLocation)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    eventDescription: ").append(toIndentedString(eventDescription)).append("\n");
    sb.append("    eventDescriptionDE: ").append(toIndentedString(eventDescriptionDE)).append("\n");
    sb.append("    eventDescriptionIT: ").append(toIndentedString(eventDescriptionIT)).append("\n");
    sb.append("    eventDescriptionEN: ").append(toIndentedString(eventDescriptionEN)).append("\n");
    sb.append("    anchorVenue: ").append(toIndentedString(anchorVenue)).append("\n");
    sb.append("    anchorVenueShort: ").append(toIndentedString(anchorVenueShort)).append("\n");
    sb.append("    changedOn: ").append(toIndentedString(changedOn)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    startDateUTC: ").append(toIndentedString(startDateUTC)).append("\n");
    sb.append("    endDateUTC: ").append(toIndentedString(endDateUTC)).append("\n");
    sb.append("    webAddress: ").append(toIndentedString(webAddress)).append("\n");
    sb.append("    display1: ").append(toIndentedString(display1)).append("\n");
    sb.append("    display2: ").append(toIndentedString(display2)).append("\n");
    sb.append("    display3: ").append(toIndentedString(display3)).append("\n");
    sb.append("    display4: ").append(toIndentedString(display4)).append("\n");
    sb.append("    display5: ").append(toIndentedString(display5)).append("\n");
    sb.append("    display6: ").append(toIndentedString(display6)).append("\n");
    sb.append("    display7: ").append(toIndentedString(display7)).append("\n");
    sb.append("    display8: ").append(toIndentedString(display8)).append("\n");
    sb.append("    display9: ").append(toIndentedString(display9)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    companyAddressLine1: ").append(toIndentedString(companyAddressLine1)).append("\n");
    sb.append("    companyAddressLine2: ").append(toIndentedString(companyAddressLine2)).append("\n");
    sb.append("    companyAddressLine3: ").append(toIndentedString(companyAddressLine3)).append("\n");
    sb.append("    companyPostalCode: ").append(toIndentedString(companyPostalCode)).append("\n");
    sb.append("    companyCity: ").append(toIndentedString(companyCity)).append("\n");
    sb.append("    companyCountry: ").append(toIndentedString(companyCountry)).append("\n");
    sb.append("    companyPhone: ").append(toIndentedString(companyPhone)).append("\n");
    sb.append("    companyFax: ").append(toIndentedString(companyFax)).append("\n");
    sb.append("    companyMail: ").append(toIndentedString(companyMail)).append("\n");
    sb.append("    companyUrl: ").append(toIndentedString(companyUrl)).append("\n");
    sb.append("    contactCode: ").append(toIndentedString(contactCode)).append("\n");
    sb.append("    contactFirstName: ").append(toIndentedString(contactFirstName)).append("\n");
    sb.append("    contactLastName: ").append(toIndentedString(contactLastName)).append("\n");
    sb.append("    contactPhone: ").append(toIndentedString(contactPhone)).append("\n");
    sb.append("    contactCell: ").append(toIndentedString(contactCell)).append("\n");
    sb.append("    contactFax: ").append(toIndentedString(contactFax)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    contactAddressLine1: ").append(toIndentedString(contactAddressLine1)).append("\n");
    sb.append("    contactAddressLine2: ").append(toIndentedString(contactAddressLine2)).append("\n");
    sb.append("    contactAddressLine3: ").append(toIndentedString(contactAddressLine3)).append("\n");
    sb.append("    contactPostalCode: ").append(toIndentedString(contactPostalCode)).append("\n");
    sb.append("    contactCity: ").append(toIndentedString(contactCity)).append("\n");
    sb.append("    contactCountry: ").append(toIndentedString(contactCountry)).append("\n");
    sb.append("    roomBooked: ").append(toIndentedString(roomBooked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

