/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * EventShortByRoom
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class EventShortByRoom {
  @JsonProperty("SpaceDescList")
  private List<String> spaceDescList = null;

  @JsonProperty("SpaceDesc")
  private String spaceDesc = null;

  @JsonProperty("SpaceType")
  private String spaceType = null;

  @JsonProperty("Subtitle")
  private String subtitle = null;

  @JsonProperty("RoomStartDate")
  private OffsetDateTime roomStartDate = null;

  @JsonProperty("RoomEndDate")
  private OffsetDateTime roomEndDate = null;

  @JsonProperty("RoomStartDateUTC")
  private Double roomStartDateUTC = null;

  @JsonProperty("RoomEndDateUTC")
  private Double roomEndDateUTC = null;

  @JsonProperty("EventId")
  private Integer eventId = null;

  @JsonProperty("EventDescription")
  private Map<String, String> eventDescription = null;

  @JsonProperty("EventDescriptionDE")
  private String eventDescriptionDE = null;

  @JsonProperty("EventDescriptionIT")
  private String eventDescriptionIT = null;

  @JsonProperty("EventDescriptionEN")
  private String eventDescriptionEN = null;

  @JsonProperty("EventAnchorVenue")
  private String eventAnchorVenue = null;

  @JsonProperty("EventAnchorVenueShort")
  private String eventAnchorVenueShort = null;

  @JsonProperty("EventStartDate")
  private OffsetDateTime eventStartDate = null;

  @JsonProperty("EventEndDate")
  private OffsetDateTime eventEndDate = null;

  @JsonProperty("EventStartDateUTC")
  private Double eventStartDateUTC = null;

  @JsonProperty("EventEndDateUTC")
  private Double eventEndDateUTC = null;

  @JsonProperty("EventWebAddress")
  private String eventWebAddress = null;

  @JsonProperty("Id")
  private String id = null;

  @JsonProperty("EventSource")
  private String eventSource = null;

  @JsonProperty("EventLocation")
  private String eventLocation = null;

  @JsonProperty("CompanyName")
  private String companyName = null;

  public EventShortByRoom spaceDescList(List<String> spaceDescList) {
    this.spaceDescList = spaceDescList;
    return this;
  }

  public EventShortByRoom addSpaceDescListItem(String spaceDescListItem) {
    if (this.spaceDescList == null) {
      this.spaceDescList = new ArrayList<>();
    }
    this.spaceDescList.add(spaceDescListItem);
    return this;
  }

   /**
   * Get spaceDescList
   * @return spaceDescList
  **/
  @ApiModelProperty(value = "")
  public List<String> getSpaceDescList() {
    return spaceDescList;
  }

  public void setSpaceDescList(List<String> spaceDescList) {
    this.spaceDescList = spaceDescList;
  }

  public EventShortByRoom spaceDesc(String spaceDesc) {
    this.spaceDesc = spaceDesc;
    return this;
  }

   /**
   * Get spaceDesc
   * @return spaceDesc
  **/
  @ApiModelProperty(value = "")
  public String getSpaceDesc() {
    return spaceDesc;
  }

  public void setSpaceDesc(String spaceDesc) {
    this.spaceDesc = spaceDesc;
  }

  public EventShortByRoom spaceType(String spaceType) {
    this.spaceType = spaceType;
    return this;
  }

   /**
   * Get spaceType
   * @return spaceType
  **/
  @ApiModelProperty(value = "")
  public String getSpaceType() {
    return spaceType;
  }

  public void setSpaceType(String spaceType) {
    this.spaceType = spaceType;
  }

  public EventShortByRoom subtitle(String subtitle) {
    this.subtitle = subtitle;
    return this;
  }

   /**
   * Get subtitle
   * @return subtitle
  **/
  @ApiModelProperty(value = "")
  public String getSubtitle() {
    return subtitle;
  }

  public void setSubtitle(String subtitle) {
    this.subtitle = subtitle;
  }

  public EventShortByRoom roomStartDate(OffsetDateTime roomStartDate) {
    this.roomStartDate = roomStartDate;
    return this;
  }

   /**
   * Get roomStartDate
   * @return roomStartDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getRoomStartDate() {
    return roomStartDate;
  }

  public void setRoomStartDate(OffsetDateTime roomStartDate) {
    this.roomStartDate = roomStartDate;
  }

  public EventShortByRoom roomEndDate(OffsetDateTime roomEndDate) {
    this.roomEndDate = roomEndDate;
    return this;
  }

   /**
   * Get roomEndDate
   * @return roomEndDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getRoomEndDate() {
    return roomEndDate;
  }

  public void setRoomEndDate(OffsetDateTime roomEndDate) {
    this.roomEndDate = roomEndDate;
  }

  public EventShortByRoom roomStartDateUTC(Double roomStartDateUTC) {
    this.roomStartDateUTC = roomStartDateUTC;
    return this;
  }

   /**
   * Get roomStartDateUTC
   * @return roomStartDateUTC
  **/
  @ApiModelProperty(value = "")
  public Double getRoomStartDateUTC() {
    return roomStartDateUTC;
  }

  public void setRoomStartDateUTC(Double roomStartDateUTC) {
    this.roomStartDateUTC = roomStartDateUTC;
  }

  public EventShortByRoom roomEndDateUTC(Double roomEndDateUTC) {
    this.roomEndDateUTC = roomEndDateUTC;
    return this;
  }

   /**
   * Get roomEndDateUTC
   * @return roomEndDateUTC
  **/
  @ApiModelProperty(value = "")
  public Double getRoomEndDateUTC() {
    return roomEndDateUTC;
  }

  public void setRoomEndDateUTC(Double roomEndDateUTC) {
    this.roomEndDateUTC = roomEndDateUTC;
  }

  public EventShortByRoom eventId(Integer eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @ApiModelProperty(value = "")
  public Integer getEventId() {
    return eventId;
  }

  public void setEventId(Integer eventId) {
    this.eventId = eventId;
  }

  public EventShortByRoom eventDescription(Map<String, String> eventDescription) {
    this.eventDescription = eventDescription;
    return this;
  }

  public EventShortByRoom putEventDescriptionItem(String key, String eventDescriptionItem) {
    if (this.eventDescription == null) {
      this.eventDescription = new HashMap<>();
    }
    this.eventDescription.put(key, eventDescriptionItem);
    return this;
  }

   /**
   * Get eventDescription
   * @return eventDescription
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getEventDescription() {
    return eventDescription;
  }

  public void setEventDescription(Map<String, String> eventDescription) {
    this.eventDescription = eventDescription;
  }

  public EventShortByRoom eventDescriptionDE(String eventDescriptionDE) {
    this.eventDescriptionDE = eventDescriptionDE;
    return this;
  }

   /**
   * Get eventDescriptionDE
   * @return eventDescriptionDE
  **/
  @ApiModelProperty(value = "")
  public String getEventDescriptionDE() {
    return eventDescriptionDE;
  }

  public void setEventDescriptionDE(String eventDescriptionDE) {
    this.eventDescriptionDE = eventDescriptionDE;
  }

  public EventShortByRoom eventDescriptionIT(String eventDescriptionIT) {
    this.eventDescriptionIT = eventDescriptionIT;
    return this;
  }

   /**
   * Get eventDescriptionIT
   * @return eventDescriptionIT
  **/
  @ApiModelProperty(value = "")
  public String getEventDescriptionIT() {
    return eventDescriptionIT;
  }

  public void setEventDescriptionIT(String eventDescriptionIT) {
    this.eventDescriptionIT = eventDescriptionIT;
  }

  public EventShortByRoom eventDescriptionEN(String eventDescriptionEN) {
    this.eventDescriptionEN = eventDescriptionEN;
    return this;
  }

   /**
   * Get eventDescriptionEN
   * @return eventDescriptionEN
  **/
  @ApiModelProperty(value = "")
  public String getEventDescriptionEN() {
    return eventDescriptionEN;
  }

  public void setEventDescriptionEN(String eventDescriptionEN) {
    this.eventDescriptionEN = eventDescriptionEN;
  }

  public EventShortByRoom eventAnchorVenue(String eventAnchorVenue) {
    this.eventAnchorVenue = eventAnchorVenue;
    return this;
  }

   /**
   * Get eventAnchorVenue
   * @return eventAnchorVenue
  **/
  @ApiModelProperty(value = "")
  public String getEventAnchorVenue() {
    return eventAnchorVenue;
  }

  public void setEventAnchorVenue(String eventAnchorVenue) {
    this.eventAnchorVenue = eventAnchorVenue;
  }

  public EventShortByRoom eventAnchorVenueShort(String eventAnchorVenueShort) {
    this.eventAnchorVenueShort = eventAnchorVenueShort;
    return this;
  }

   /**
   * Get eventAnchorVenueShort
   * @return eventAnchorVenueShort
  **/
  @ApiModelProperty(value = "")
  public String getEventAnchorVenueShort() {
    return eventAnchorVenueShort;
  }

  public void setEventAnchorVenueShort(String eventAnchorVenueShort) {
    this.eventAnchorVenueShort = eventAnchorVenueShort;
  }

  public EventShortByRoom eventStartDate(OffsetDateTime eventStartDate) {
    this.eventStartDate = eventStartDate;
    return this;
  }

   /**
   * Get eventStartDate
   * @return eventStartDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEventStartDate() {
    return eventStartDate;
  }

  public void setEventStartDate(OffsetDateTime eventStartDate) {
    this.eventStartDate = eventStartDate;
  }

  public EventShortByRoom eventEndDate(OffsetDateTime eventEndDate) {
    this.eventEndDate = eventEndDate;
    return this;
  }

   /**
   * Get eventEndDate
   * @return eventEndDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEventEndDate() {
    return eventEndDate;
  }

  public void setEventEndDate(OffsetDateTime eventEndDate) {
    this.eventEndDate = eventEndDate;
  }

  public EventShortByRoom eventStartDateUTC(Double eventStartDateUTC) {
    this.eventStartDateUTC = eventStartDateUTC;
    return this;
  }

   /**
   * Get eventStartDateUTC
   * @return eventStartDateUTC
  **/
  @ApiModelProperty(value = "")
  public Double getEventStartDateUTC() {
    return eventStartDateUTC;
  }

  public void setEventStartDateUTC(Double eventStartDateUTC) {
    this.eventStartDateUTC = eventStartDateUTC;
  }

  public EventShortByRoom eventEndDateUTC(Double eventEndDateUTC) {
    this.eventEndDateUTC = eventEndDateUTC;
    return this;
  }

   /**
   * Get eventEndDateUTC
   * @return eventEndDateUTC
  **/
  @ApiModelProperty(value = "")
  public Double getEventEndDateUTC() {
    return eventEndDateUTC;
  }

  public void setEventEndDateUTC(Double eventEndDateUTC) {
    this.eventEndDateUTC = eventEndDateUTC;
  }

  public EventShortByRoom eventWebAddress(String eventWebAddress) {
    this.eventWebAddress = eventWebAddress;
    return this;
  }

   /**
   * Get eventWebAddress
   * @return eventWebAddress
  **/
  @ApiModelProperty(value = "")
  public String getEventWebAddress() {
    return eventWebAddress;
  }

  public void setEventWebAddress(String eventWebAddress) {
    this.eventWebAddress = eventWebAddress;
  }

  public EventShortByRoom id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EventShortByRoom eventSource(String eventSource) {
    this.eventSource = eventSource;
    return this;
  }

   /**
   * Get eventSource
   * @return eventSource
  **/
  @ApiModelProperty(value = "")
  public String getEventSource() {
    return eventSource;
  }

  public void setEventSource(String eventSource) {
    this.eventSource = eventSource;
  }

  public EventShortByRoom eventLocation(String eventLocation) {
    this.eventLocation = eventLocation;
    return this;
  }

   /**
   * Get eventLocation
   * @return eventLocation
  **/
  @ApiModelProperty(value = "")
  public String getEventLocation() {
    return eventLocation;
  }

  public void setEventLocation(String eventLocation) {
    this.eventLocation = eventLocation;
  }

  public EventShortByRoom companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @ApiModelProperty(value = "")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventShortByRoom eventShortByRoom = (EventShortByRoom) o;
    return Objects.equals(this.spaceDescList, eventShortByRoom.spaceDescList) &&
        Objects.equals(this.spaceDesc, eventShortByRoom.spaceDesc) &&
        Objects.equals(this.spaceType, eventShortByRoom.spaceType) &&
        Objects.equals(this.subtitle, eventShortByRoom.subtitle) &&
        Objects.equals(this.roomStartDate, eventShortByRoom.roomStartDate) &&
        Objects.equals(this.roomEndDate, eventShortByRoom.roomEndDate) &&
        Objects.equals(this.roomStartDateUTC, eventShortByRoom.roomStartDateUTC) &&
        Objects.equals(this.roomEndDateUTC, eventShortByRoom.roomEndDateUTC) &&
        Objects.equals(this.eventId, eventShortByRoom.eventId) &&
        Objects.equals(this.eventDescription, eventShortByRoom.eventDescription) &&
        Objects.equals(this.eventDescriptionDE, eventShortByRoom.eventDescriptionDE) &&
        Objects.equals(this.eventDescriptionIT, eventShortByRoom.eventDescriptionIT) &&
        Objects.equals(this.eventDescriptionEN, eventShortByRoom.eventDescriptionEN) &&
        Objects.equals(this.eventAnchorVenue, eventShortByRoom.eventAnchorVenue) &&
        Objects.equals(this.eventAnchorVenueShort, eventShortByRoom.eventAnchorVenueShort) &&
        Objects.equals(this.eventStartDate, eventShortByRoom.eventStartDate) &&
        Objects.equals(this.eventEndDate, eventShortByRoom.eventEndDate) &&
        Objects.equals(this.eventStartDateUTC, eventShortByRoom.eventStartDateUTC) &&
        Objects.equals(this.eventEndDateUTC, eventShortByRoom.eventEndDateUTC) &&
        Objects.equals(this.eventWebAddress, eventShortByRoom.eventWebAddress) &&
        Objects.equals(this.id, eventShortByRoom.id) &&
        Objects.equals(this.eventSource, eventShortByRoom.eventSource) &&
        Objects.equals(this.eventLocation, eventShortByRoom.eventLocation) &&
        Objects.equals(this.companyName, eventShortByRoom.companyName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(spaceDescList, spaceDesc, spaceType, subtitle, roomStartDate, roomEndDate, roomStartDateUTC, roomEndDateUTC, eventId, eventDescription, eventDescriptionDE, eventDescriptionIT, eventDescriptionEN, eventAnchorVenue, eventAnchorVenueShort, eventStartDate, eventEndDate, eventStartDateUTC, eventEndDateUTC, eventWebAddress, id, eventSource, eventLocation, companyName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventShortByRoom {\n");
    
    sb.append("    spaceDescList: ").append(toIndentedString(spaceDescList)).append("\n");
    sb.append("    spaceDesc: ").append(toIndentedString(spaceDesc)).append("\n");
    sb.append("    spaceType: ").append(toIndentedString(spaceType)).append("\n");
    sb.append("    subtitle: ").append(toIndentedString(subtitle)).append("\n");
    sb.append("    roomStartDate: ").append(toIndentedString(roomStartDate)).append("\n");
    sb.append("    roomEndDate: ").append(toIndentedString(roomEndDate)).append("\n");
    sb.append("    roomStartDateUTC: ").append(toIndentedString(roomStartDateUTC)).append("\n");
    sb.append("    roomEndDateUTC: ").append(toIndentedString(roomEndDateUTC)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    eventDescription: ").append(toIndentedString(eventDescription)).append("\n");
    sb.append("    eventDescriptionDE: ").append(toIndentedString(eventDescriptionDE)).append("\n");
    sb.append("    eventDescriptionIT: ").append(toIndentedString(eventDescriptionIT)).append("\n");
    sb.append("    eventDescriptionEN: ").append(toIndentedString(eventDescriptionEN)).append("\n");
    sb.append("    eventAnchorVenue: ").append(toIndentedString(eventAnchorVenue)).append("\n");
    sb.append("    eventAnchorVenueShort: ").append(toIndentedString(eventAnchorVenueShort)).append("\n");
    sb.append("    eventStartDate: ").append(toIndentedString(eventStartDate)).append("\n");
    sb.append("    eventEndDate: ").append(toIndentedString(eventEndDate)).append("\n");
    sb.append("    eventStartDateUTC: ").append(toIndentedString(eventStartDateUTC)).append("\n");
    sb.append("    eventEndDateUTC: ").append(toIndentedString(eventEndDateUTC)).append("\n");
    sb.append("    eventWebAddress: ").append(toIndentedString(eventWebAddress)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    eventSource: ").append(toIndentedString(eventSource)).append("\n");
    sb.append("    eventLocation: ").append(toIndentedString(eventLocation)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

