/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * Forecast
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class Forecast {
  @JsonProperty("date")
  private OffsetDateTime date = null;

  @JsonProperty("TempMaxmax")
  private Integer tempMaxmax = null;

  @JsonProperty("TempMaxmin")
  private Integer tempMaxmin = null;

  @JsonProperty("TempMinmax")
  private Integer tempMinmax = null;

  @JsonProperty("TempMinmin")
  private Integer tempMinmin = null;

  @JsonProperty("Weatherdesc")
  private String weatherdesc = null;

  @JsonProperty("Weathercode")
  private String weathercode = null;

  @JsonProperty("WeatherImgurl")
  private String weatherImgurl = null;

  @JsonProperty("Reliability")
  private String reliability = null;

  public Forecast date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public Forecast tempMaxmax(Integer tempMaxmax) {
    this.tempMaxmax = tempMaxmax;
    return this;
  }

   /**
   * Get tempMaxmax
   * @return tempMaxmax
  **/
  @ApiModelProperty(value = "")
  public Integer getTempMaxmax() {
    return tempMaxmax;
  }

  public void setTempMaxmax(Integer tempMaxmax) {
    this.tempMaxmax = tempMaxmax;
  }

  public Forecast tempMaxmin(Integer tempMaxmin) {
    this.tempMaxmin = tempMaxmin;
    return this;
  }

   /**
   * Get tempMaxmin
   * @return tempMaxmin
  **/
  @ApiModelProperty(value = "")
  public Integer getTempMaxmin() {
    return tempMaxmin;
  }

  public void setTempMaxmin(Integer tempMaxmin) {
    this.tempMaxmin = tempMaxmin;
  }

  public Forecast tempMinmax(Integer tempMinmax) {
    this.tempMinmax = tempMinmax;
    return this;
  }

   /**
   * Get tempMinmax
   * @return tempMinmax
  **/
  @ApiModelProperty(value = "")
  public Integer getTempMinmax() {
    return tempMinmax;
  }

  public void setTempMinmax(Integer tempMinmax) {
    this.tempMinmax = tempMinmax;
  }

  public Forecast tempMinmin(Integer tempMinmin) {
    this.tempMinmin = tempMinmin;
    return this;
  }

   /**
   * Get tempMinmin
   * @return tempMinmin
  **/
  @ApiModelProperty(value = "")
  public Integer getTempMinmin() {
    return tempMinmin;
  }

  public void setTempMinmin(Integer tempMinmin) {
    this.tempMinmin = tempMinmin;
  }

  public Forecast weatherdesc(String weatherdesc) {
    this.weatherdesc = weatherdesc;
    return this;
  }

   /**
   * Get weatherdesc
   * @return weatherdesc
  **/
  @ApiModelProperty(value = "")
  public String getWeatherdesc() {
    return weatherdesc;
  }

  public void setWeatherdesc(String weatherdesc) {
    this.weatherdesc = weatherdesc;
  }

  public Forecast weathercode(String weathercode) {
    this.weathercode = weathercode;
    return this;
  }

   /**
   * Get weathercode
   * @return weathercode
  **/
  @ApiModelProperty(value = "")
  public String getWeathercode() {
    return weathercode;
  }

  public void setWeathercode(String weathercode) {
    this.weathercode = weathercode;
  }

  public Forecast weatherImgurl(String weatherImgurl) {
    this.weatherImgurl = weatherImgurl;
    return this;
  }

   /**
   * Get weatherImgurl
   * @return weatherImgurl
  **/
  @ApiModelProperty(value = "")
  public String getWeatherImgurl() {
    return weatherImgurl;
  }

  public void setWeatherImgurl(String weatherImgurl) {
    this.weatherImgurl = weatherImgurl;
  }

  public Forecast reliability(String reliability) {
    this.reliability = reliability;
    return this;
  }

   /**
   * Get reliability
   * @return reliability
  **/
  @ApiModelProperty(value = "")
  public String getReliability() {
    return reliability;
  }

  public void setReliability(String reliability) {
    this.reliability = reliability;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Forecast forecast = (Forecast) o;
    return Objects.equals(this.date, forecast.date) &&
        Objects.equals(this.tempMaxmax, forecast.tempMaxmax) &&
        Objects.equals(this.tempMaxmin, forecast.tempMaxmin) &&
        Objects.equals(this.tempMinmax, forecast.tempMinmax) &&
        Objects.equals(this.tempMinmin, forecast.tempMinmin) &&
        Objects.equals(this.weatherdesc, forecast.weatherdesc) &&
        Objects.equals(this.weathercode, forecast.weathercode) &&
        Objects.equals(this.weatherImgurl, forecast.weatherImgurl) &&
        Objects.equals(this.reliability, forecast.reliability);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, tempMaxmax, tempMaxmin, tempMinmax, tempMinmin, weatherdesc, weathercode, weatherImgurl, reliability);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Forecast {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    tempMaxmax: ").append(toIndentedString(tempMaxmax)).append("\n");
    sb.append("    tempMaxmin: ").append(toIndentedString(tempMaxmin)).append("\n");
    sb.append("    tempMinmax: ").append(toIndentedString(tempMinmax)).append("\n");
    sb.append("    tempMinmin: ").append(toIndentedString(tempMinmin)).append("\n");
    sb.append("    weatherdesc: ").append(toIndentedString(weatherdesc)).append("\n");
    sb.append("    weathercode: ").append(toIndentedString(weathercode)).append("\n");
    sb.append("    weatherImgurl: ").append(toIndentedString(weatherImgurl)).append("\n");
    sb.append("    reliability: ").append(toIndentedString(reliability)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

