/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * GBLTSActivityPoiLocalized
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class GBLTSActivityPoiLocalized {
  @JsonProperty("GpsPoints")
  private Map<String, GpsInfo> gpsPoints = null;

  @JsonProperty("LTSTags")
  private List<LTSTagsLocalized> ltSTags = null;

  @JsonProperty("Id")
  private String id = null;

  @JsonProperty("Active")
  private Boolean active = null;

  @JsonProperty("Shortname")
  private String shortname = null;

  @JsonProperty("SmgId")
  private String smgId = null;

  @JsonProperty("Highlight")
  private Boolean highlight = null;

  @JsonProperty("Difficulty")
  private String difficulty = null;

  @JsonProperty("Type")
  private String type = null;

  @JsonProperty("SubType")
  private String subType = null;

  @JsonProperty("FirstImport")
  private String firstImport = null;

  @JsonProperty("LastChange")
  private String lastChange = null;

  @JsonProperty("SmgActive")
  private Boolean smgActive = null;

  @JsonProperty("LocationInfo")
  private LocationInfoLocalized locationInfo = null;

  @JsonProperty("TourismorganizationId")
  private String tourismorganizationId = null;

  @JsonProperty("AreaId")
  private List<String> areaId = null;

  @JsonProperty("AltitudeDifference")
  private Double altitudeDifference = null;

  @JsonProperty("AltitudeHighestPoint")
  private Double altitudeHighestPoint = null;

  @JsonProperty("AltitudeLowestPoint")
  private Double altitudeLowestPoint = null;

  @JsonProperty("AltitudeSumUp")
  private Double altitudeSumUp = null;

  @JsonProperty("AltitudeSumDown")
  private Double altitudeSumDown = null;

  @JsonProperty("DistanceDuration")
  private Double distanceDuration = null;

  @JsonProperty("DistanceLength")
  private Double distanceLength = null;

  @JsonProperty("IsOpen")
  private Boolean isOpen = null;

  @JsonProperty("IsPrepared")
  private Boolean isPrepared = null;

  @JsonProperty("RunToValley")
  private Boolean runToValley = null;

  @JsonProperty("IsWithLigth")
  private Boolean isWithLigth = null;

  @JsonProperty("HasRentals")
  private Boolean hasRentals = null;

  @JsonProperty("HasFreeEntrance")
  private Boolean hasFreeEntrance = null;

  @JsonProperty("LiftAvailable")
  private Boolean liftAvailable = null;

  @JsonProperty("FeetClimb")
  private Boolean feetClimb = null;

  @JsonProperty("BikeTransport")
  private Boolean bikeTransport = null;

  @JsonProperty("OperationSchedule")
  private List<OperationSchedule> operationSchedule = null;

  @JsonProperty("GpsInfo")
  private List<GpsInfo> gpsInfo = null;

  @JsonProperty("GpsTrack")
  private List<GpsTrack> gpsTrack = null;

  @JsonProperty("ImageGallery")
  private List<ImageGalleryLocalized> imageGallery = null;

  @JsonProperty("Detail")
  private Detail detail = null;

  @JsonProperty("ContactInfos")
  private ContactInfos contactInfos = null;

  @JsonProperty("AdditionalPoiInfos")
  private AdditionalPoiInfos additionalPoiInfos = null;

  @JsonProperty("Ratings")
  private Ratings ratings = null;

  @JsonProperty("Exposition")
  private List<String> exposition = null;

  @JsonProperty("SmgTags")
  private List<String> smgTags = null;

  public GBLTSActivityPoiLocalized gpsPoints(Map<String, GpsInfo> gpsPoints) {
    this.gpsPoints = gpsPoints;
    return this;
  }

  public GBLTSActivityPoiLocalized putGpsPointsItem(String key, GpsInfo gpsPointsItem) {
    if (this.gpsPoints == null) {
      this.gpsPoints = new HashMap<>();
    }
    this.gpsPoints.put(key, gpsPointsItem);
    return this;
  }

   /**
   * Get gpsPoints
   * @return gpsPoints
  **/
  @ApiModelProperty(value = "")
  public Map<String, GpsInfo> getGpsPoints() {
    return gpsPoints;
  }

  public void setGpsPoints(Map<String, GpsInfo> gpsPoints) {
    this.gpsPoints = gpsPoints;
  }

  public GBLTSActivityPoiLocalized ltSTags(List<LTSTagsLocalized> ltSTags) {
    this.ltSTags = ltSTags;
    return this;
  }

  public GBLTSActivityPoiLocalized addLtSTagsItem(LTSTagsLocalized ltSTagsItem) {
    if (this.ltSTags == null) {
      this.ltSTags = new ArrayList<>();
    }
    this.ltSTags.add(ltSTagsItem);
    return this;
  }

   /**
   * Get ltSTags
   * @return ltSTags
  **/
  @ApiModelProperty(value = "")
  public List<LTSTagsLocalized> getLtSTags() {
    return ltSTags;
  }

  public void setLtSTags(List<LTSTagsLocalized> ltSTags) {
    this.ltSTags = ltSTags;
  }

  public GBLTSActivityPoiLocalized id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GBLTSActivityPoiLocalized active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public GBLTSActivityPoiLocalized shortname(String shortname) {
    this.shortname = shortname;
    return this;
  }

   /**
   * Get shortname
   * @return shortname
  **/
  @ApiModelProperty(value = "")
  public String getShortname() {
    return shortname;
  }

  public void setShortname(String shortname) {
    this.shortname = shortname;
  }

  public GBLTSActivityPoiLocalized smgId(String smgId) {
    this.smgId = smgId;
    return this;
  }

   /**
   * Get smgId
   * @return smgId
  **/
  @ApiModelProperty(value = "")
  public String getSmgId() {
    return smgId;
  }

  public void setSmgId(String smgId) {
    this.smgId = smgId;
  }

  public GBLTSActivityPoiLocalized highlight(Boolean highlight) {
    this.highlight = highlight;
    return this;
  }

   /**
   * Get highlight
   * @return highlight
  **/
  @ApiModelProperty(value = "")
  public Boolean isHighlight() {
    return highlight;
  }

  public void setHighlight(Boolean highlight) {
    this.highlight = highlight;
  }

  public GBLTSActivityPoiLocalized difficulty(String difficulty) {
    this.difficulty = difficulty;
    return this;
  }

   /**
   * Get difficulty
   * @return difficulty
  **/
  @ApiModelProperty(value = "")
  public String getDifficulty() {
    return difficulty;
  }

  public void setDifficulty(String difficulty) {
    this.difficulty = difficulty;
  }

  public GBLTSActivityPoiLocalized type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public GBLTSActivityPoiLocalized subType(String subType) {
    this.subType = subType;
    return this;
  }

   /**
   * Get subType
   * @return subType
  **/
  @ApiModelProperty(value = "")
  public String getSubType() {
    return subType;
  }

  public void setSubType(String subType) {
    this.subType = subType;
  }

  public GBLTSActivityPoiLocalized firstImport(String firstImport) {
    this.firstImport = firstImport;
    return this;
  }

   /**
   * Get firstImport
   * @return firstImport
  **/
  @ApiModelProperty(value = "")
  public String getFirstImport() {
    return firstImport;
  }

  public void setFirstImport(String firstImport) {
    this.firstImport = firstImport;
  }

  public GBLTSActivityPoiLocalized lastChange(String lastChange) {
    this.lastChange = lastChange;
    return this;
  }

   /**
   * Get lastChange
   * @return lastChange
  **/
  @ApiModelProperty(value = "")
  public String getLastChange() {
    return lastChange;
  }

  public void setLastChange(String lastChange) {
    this.lastChange = lastChange;
  }

  public GBLTSActivityPoiLocalized smgActive(Boolean smgActive) {
    this.smgActive = smgActive;
    return this;
  }

   /**
   * Get smgActive
   * @return smgActive
  **/
  @ApiModelProperty(value = "")
  public Boolean isSmgActive() {
    return smgActive;
  }

  public void setSmgActive(Boolean smgActive) {
    this.smgActive = smgActive;
  }

  public GBLTSActivityPoiLocalized locationInfo(LocationInfoLocalized locationInfo) {
    this.locationInfo = locationInfo;
    return this;
  }

   /**
   * Get locationInfo
   * @return locationInfo
  **/
  @ApiModelProperty(value = "")
  public LocationInfoLocalized getLocationInfo() {
    return locationInfo;
  }

  public void setLocationInfo(LocationInfoLocalized locationInfo) {
    this.locationInfo = locationInfo;
  }

  public GBLTSActivityPoiLocalized tourismorganizationId(String tourismorganizationId) {
    this.tourismorganizationId = tourismorganizationId;
    return this;
  }

   /**
   * Get tourismorganizationId
   * @return tourismorganizationId
  **/
  @ApiModelProperty(value = "")
  public String getTourismorganizationId() {
    return tourismorganizationId;
  }

  public void setTourismorganizationId(String tourismorganizationId) {
    this.tourismorganizationId = tourismorganizationId;
  }

  public GBLTSActivityPoiLocalized areaId(List<String> areaId) {
    this.areaId = areaId;
    return this;
  }

  public GBLTSActivityPoiLocalized addAreaIdItem(String areaIdItem) {
    if (this.areaId == null) {
      this.areaId = new ArrayList<>();
    }
    this.areaId.add(areaIdItem);
    return this;
  }

   /**
   * Get areaId
   * @return areaId
  **/
  @ApiModelProperty(value = "")
  public List<String> getAreaId() {
    return areaId;
  }

  public void setAreaId(List<String> areaId) {
    this.areaId = areaId;
  }

  public GBLTSActivityPoiLocalized altitudeDifference(Double altitudeDifference) {
    this.altitudeDifference = altitudeDifference;
    return this;
  }

   /**
   * Get altitudeDifference
   * @return altitudeDifference
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeDifference() {
    return altitudeDifference;
  }

  public void setAltitudeDifference(Double altitudeDifference) {
    this.altitudeDifference = altitudeDifference;
  }

  public GBLTSActivityPoiLocalized altitudeHighestPoint(Double altitudeHighestPoint) {
    this.altitudeHighestPoint = altitudeHighestPoint;
    return this;
  }

   /**
   * Get altitudeHighestPoint
   * @return altitudeHighestPoint
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeHighestPoint() {
    return altitudeHighestPoint;
  }

  public void setAltitudeHighestPoint(Double altitudeHighestPoint) {
    this.altitudeHighestPoint = altitudeHighestPoint;
  }

  public GBLTSActivityPoiLocalized altitudeLowestPoint(Double altitudeLowestPoint) {
    this.altitudeLowestPoint = altitudeLowestPoint;
    return this;
  }

   /**
   * Get altitudeLowestPoint
   * @return altitudeLowestPoint
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeLowestPoint() {
    return altitudeLowestPoint;
  }

  public void setAltitudeLowestPoint(Double altitudeLowestPoint) {
    this.altitudeLowestPoint = altitudeLowestPoint;
  }

  public GBLTSActivityPoiLocalized altitudeSumUp(Double altitudeSumUp) {
    this.altitudeSumUp = altitudeSumUp;
    return this;
  }

   /**
   * Get altitudeSumUp
   * @return altitudeSumUp
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeSumUp() {
    return altitudeSumUp;
  }

  public void setAltitudeSumUp(Double altitudeSumUp) {
    this.altitudeSumUp = altitudeSumUp;
  }

  public GBLTSActivityPoiLocalized altitudeSumDown(Double altitudeSumDown) {
    this.altitudeSumDown = altitudeSumDown;
    return this;
  }

   /**
   * Get altitudeSumDown
   * @return altitudeSumDown
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeSumDown() {
    return altitudeSumDown;
  }

  public void setAltitudeSumDown(Double altitudeSumDown) {
    this.altitudeSumDown = altitudeSumDown;
  }

  public GBLTSActivityPoiLocalized distanceDuration(Double distanceDuration) {
    this.distanceDuration = distanceDuration;
    return this;
  }

   /**
   * Get distanceDuration
   * @return distanceDuration
  **/
  @ApiModelProperty(value = "")
  public Double getDistanceDuration() {
    return distanceDuration;
  }

  public void setDistanceDuration(Double distanceDuration) {
    this.distanceDuration = distanceDuration;
  }

  public GBLTSActivityPoiLocalized distanceLength(Double distanceLength) {
    this.distanceLength = distanceLength;
    return this;
  }

   /**
   * Get distanceLength
   * @return distanceLength
  **/
  @ApiModelProperty(value = "")
  public Double getDistanceLength() {
    return distanceLength;
  }

  public void setDistanceLength(Double distanceLength) {
    this.distanceLength = distanceLength;
  }

  public GBLTSActivityPoiLocalized isOpen(Boolean isOpen) {
    this.isOpen = isOpen;
    return this;
  }

   /**
   * Get isOpen
   * @return isOpen
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsOpen() {
    return isOpen;
  }

  public void setIsOpen(Boolean isOpen) {
    this.isOpen = isOpen;
  }

  public GBLTSActivityPoiLocalized isPrepared(Boolean isPrepared) {
    this.isPrepared = isPrepared;
    return this;
  }

   /**
   * Get isPrepared
   * @return isPrepared
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPrepared() {
    return isPrepared;
  }

  public void setIsPrepared(Boolean isPrepared) {
    this.isPrepared = isPrepared;
  }

  public GBLTSActivityPoiLocalized runToValley(Boolean runToValley) {
    this.runToValley = runToValley;
    return this;
  }

   /**
   * Get runToValley
   * @return runToValley
  **/
  @ApiModelProperty(value = "")
  public Boolean isRunToValley() {
    return runToValley;
  }

  public void setRunToValley(Boolean runToValley) {
    this.runToValley = runToValley;
  }

  public GBLTSActivityPoiLocalized isWithLigth(Boolean isWithLigth) {
    this.isWithLigth = isWithLigth;
    return this;
  }

   /**
   * Get isWithLigth
   * @return isWithLigth
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsWithLigth() {
    return isWithLigth;
  }

  public void setIsWithLigth(Boolean isWithLigth) {
    this.isWithLigth = isWithLigth;
  }

  public GBLTSActivityPoiLocalized hasRentals(Boolean hasRentals) {
    this.hasRentals = hasRentals;
    return this;
  }

   /**
   * Get hasRentals
   * @return hasRentals
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasRentals() {
    return hasRentals;
  }

  public void setHasRentals(Boolean hasRentals) {
    this.hasRentals = hasRentals;
  }

  public GBLTSActivityPoiLocalized hasFreeEntrance(Boolean hasFreeEntrance) {
    this.hasFreeEntrance = hasFreeEntrance;
    return this;
  }

   /**
   * Get hasFreeEntrance
   * @return hasFreeEntrance
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasFreeEntrance() {
    return hasFreeEntrance;
  }

  public void setHasFreeEntrance(Boolean hasFreeEntrance) {
    this.hasFreeEntrance = hasFreeEntrance;
  }

  public GBLTSActivityPoiLocalized liftAvailable(Boolean liftAvailable) {
    this.liftAvailable = liftAvailable;
    return this;
  }

   /**
   * Get liftAvailable
   * @return liftAvailable
  **/
  @ApiModelProperty(value = "")
  public Boolean isLiftAvailable() {
    return liftAvailable;
  }

  public void setLiftAvailable(Boolean liftAvailable) {
    this.liftAvailable = liftAvailable;
  }

  public GBLTSActivityPoiLocalized feetClimb(Boolean feetClimb) {
    this.feetClimb = feetClimb;
    return this;
  }

   /**
   * Get feetClimb
   * @return feetClimb
  **/
  @ApiModelProperty(value = "")
  public Boolean isFeetClimb() {
    return feetClimb;
  }

  public void setFeetClimb(Boolean feetClimb) {
    this.feetClimb = feetClimb;
  }

  public GBLTSActivityPoiLocalized bikeTransport(Boolean bikeTransport) {
    this.bikeTransport = bikeTransport;
    return this;
  }

   /**
   * Get bikeTransport
   * @return bikeTransport
  **/
  @ApiModelProperty(value = "")
  public Boolean isBikeTransport() {
    return bikeTransport;
  }

  public void setBikeTransport(Boolean bikeTransport) {
    this.bikeTransport = bikeTransport;
  }

  public GBLTSActivityPoiLocalized operationSchedule(List<OperationSchedule> operationSchedule) {
    this.operationSchedule = operationSchedule;
    return this;
  }

  public GBLTSActivityPoiLocalized addOperationScheduleItem(OperationSchedule operationScheduleItem) {
    if (this.operationSchedule == null) {
      this.operationSchedule = new ArrayList<>();
    }
    this.operationSchedule.add(operationScheduleItem);
    return this;
  }

   /**
   * Get operationSchedule
   * @return operationSchedule
  **/
  @ApiModelProperty(value = "")
  public List<OperationSchedule> getOperationSchedule() {
    return operationSchedule;
  }

  public void setOperationSchedule(List<OperationSchedule> operationSchedule) {
    this.operationSchedule = operationSchedule;
  }

  public GBLTSActivityPoiLocalized gpsInfo(List<GpsInfo> gpsInfo) {
    this.gpsInfo = gpsInfo;
    return this;
  }

  public GBLTSActivityPoiLocalized addGpsInfoItem(GpsInfo gpsInfoItem) {
    if (this.gpsInfo == null) {
      this.gpsInfo = new ArrayList<>();
    }
    this.gpsInfo.add(gpsInfoItem);
    return this;
  }

   /**
   * Get gpsInfo
   * @return gpsInfo
  **/
  @ApiModelProperty(value = "")
  public List<GpsInfo> getGpsInfo() {
    return gpsInfo;
  }

  public void setGpsInfo(List<GpsInfo> gpsInfo) {
    this.gpsInfo = gpsInfo;
  }

  public GBLTSActivityPoiLocalized gpsTrack(List<GpsTrack> gpsTrack) {
    this.gpsTrack = gpsTrack;
    return this;
  }

  public GBLTSActivityPoiLocalized addGpsTrackItem(GpsTrack gpsTrackItem) {
    if (this.gpsTrack == null) {
      this.gpsTrack = new ArrayList<>();
    }
    this.gpsTrack.add(gpsTrackItem);
    return this;
  }

   /**
   * Get gpsTrack
   * @return gpsTrack
  **/
  @ApiModelProperty(value = "")
  public List<GpsTrack> getGpsTrack() {
    return gpsTrack;
  }

  public void setGpsTrack(List<GpsTrack> gpsTrack) {
    this.gpsTrack = gpsTrack;
  }

  public GBLTSActivityPoiLocalized imageGallery(List<ImageGalleryLocalized> imageGallery) {
    this.imageGallery = imageGallery;
    return this;
  }

  public GBLTSActivityPoiLocalized addImageGalleryItem(ImageGalleryLocalized imageGalleryItem) {
    if (this.imageGallery == null) {
      this.imageGallery = new ArrayList<>();
    }
    this.imageGallery.add(imageGalleryItem);
    return this;
  }

   /**
   * Get imageGallery
   * @return imageGallery
  **/
  @ApiModelProperty(value = "")
  public List<ImageGalleryLocalized> getImageGallery() {
    return imageGallery;
  }

  public void setImageGallery(List<ImageGalleryLocalized> imageGallery) {
    this.imageGallery = imageGallery;
  }

  public GBLTSActivityPoiLocalized detail(Detail detail) {
    this.detail = detail;
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @ApiModelProperty(value = "")
  public Detail getDetail() {
    return detail;
  }

  public void setDetail(Detail detail) {
    this.detail = detail;
  }

  public GBLTSActivityPoiLocalized contactInfos(ContactInfos contactInfos) {
    this.contactInfos = contactInfos;
    return this;
  }

   /**
   * Get contactInfos
   * @return contactInfos
  **/
  @ApiModelProperty(value = "")
  public ContactInfos getContactInfos() {
    return contactInfos;
  }

  public void setContactInfos(ContactInfos contactInfos) {
    this.contactInfos = contactInfos;
  }

  public GBLTSActivityPoiLocalized additionalPoiInfos(AdditionalPoiInfos additionalPoiInfos) {
    this.additionalPoiInfos = additionalPoiInfos;
    return this;
  }

   /**
   * Get additionalPoiInfos
   * @return additionalPoiInfos
  **/
  @ApiModelProperty(value = "")
  public AdditionalPoiInfos getAdditionalPoiInfos() {
    return additionalPoiInfos;
  }

  public void setAdditionalPoiInfos(AdditionalPoiInfos additionalPoiInfos) {
    this.additionalPoiInfos = additionalPoiInfos;
  }

  public GBLTSActivityPoiLocalized ratings(Ratings ratings) {
    this.ratings = ratings;
    return this;
  }

   /**
   * Get ratings
   * @return ratings
  **/
  @ApiModelProperty(value = "")
  public Ratings getRatings() {
    return ratings;
  }

  public void setRatings(Ratings ratings) {
    this.ratings = ratings;
  }

  public GBLTSActivityPoiLocalized exposition(List<String> exposition) {
    this.exposition = exposition;
    return this;
  }

  public GBLTSActivityPoiLocalized addExpositionItem(String expositionItem) {
    if (this.exposition == null) {
      this.exposition = new ArrayList<>();
    }
    this.exposition.add(expositionItem);
    return this;
  }

   /**
   * Get exposition
   * @return exposition
  **/
  @ApiModelProperty(value = "")
  public List<String> getExposition() {
    return exposition;
  }

  public void setExposition(List<String> exposition) {
    this.exposition = exposition;
  }

  public GBLTSActivityPoiLocalized smgTags(List<String> smgTags) {
    this.smgTags = smgTags;
    return this;
  }

  public GBLTSActivityPoiLocalized addSmgTagsItem(String smgTagsItem) {
    if (this.smgTags == null) {
      this.smgTags = new ArrayList<>();
    }
    this.smgTags.add(smgTagsItem);
    return this;
  }

   /**
   * Get smgTags
   * @return smgTags
  **/
  @ApiModelProperty(value = "")
  public List<String> getSmgTags() {
    return smgTags;
  }

  public void setSmgTags(List<String> smgTags) {
    this.smgTags = smgTags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GBLTSActivityPoiLocalized gbLTSActivityPoiLocalized = (GBLTSActivityPoiLocalized) o;
    return Objects.equals(this.gpsPoints, gbLTSActivityPoiLocalized.gpsPoints) &&
        Objects.equals(this.ltSTags, gbLTSActivityPoiLocalized.ltSTags) &&
        Objects.equals(this.id, gbLTSActivityPoiLocalized.id) &&
        Objects.equals(this.active, gbLTSActivityPoiLocalized.active) &&
        Objects.equals(this.shortname, gbLTSActivityPoiLocalized.shortname) &&
        Objects.equals(this.smgId, gbLTSActivityPoiLocalized.smgId) &&
        Objects.equals(this.highlight, gbLTSActivityPoiLocalized.highlight) &&
        Objects.equals(this.difficulty, gbLTSActivityPoiLocalized.difficulty) &&
        Objects.equals(this.type, gbLTSActivityPoiLocalized.type) &&
        Objects.equals(this.subType, gbLTSActivityPoiLocalized.subType) &&
        Objects.equals(this.firstImport, gbLTSActivityPoiLocalized.firstImport) &&
        Objects.equals(this.lastChange, gbLTSActivityPoiLocalized.lastChange) &&
        Objects.equals(this.smgActive, gbLTSActivityPoiLocalized.smgActive) &&
        Objects.equals(this.locationInfo, gbLTSActivityPoiLocalized.locationInfo) &&
        Objects.equals(this.tourismorganizationId, gbLTSActivityPoiLocalized.tourismorganizationId) &&
        Objects.equals(this.areaId, gbLTSActivityPoiLocalized.areaId) &&
        Objects.equals(this.altitudeDifference, gbLTSActivityPoiLocalized.altitudeDifference) &&
        Objects.equals(this.altitudeHighestPoint, gbLTSActivityPoiLocalized.altitudeHighestPoint) &&
        Objects.equals(this.altitudeLowestPoint, gbLTSActivityPoiLocalized.altitudeLowestPoint) &&
        Objects.equals(this.altitudeSumUp, gbLTSActivityPoiLocalized.altitudeSumUp) &&
        Objects.equals(this.altitudeSumDown, gbLTSActivityPoiLocalized.altitudeSumDown) &&
        Objects.equals(this.distanceDuration, gbLTSActivityPoiLocalized.distanceDuration) &&
        Objects.equals(this.distanceLength, gbLTSActivityPoiLocalized.distanceLength) &&
        Objects.equals(this.isOpen, gbLTSActivityPoiLocalized.isOpen) &&
        Objects.equals(this.isPrepared, gbLTSActivityPoiLocalized.isPrepared) &&
        Objects.equals(this.runToValley, gbLTSActivityPoiLocalized.runToValley) &&
        Objects.equals(this.isWithLigth, gbLTSActivityPoiLocalized.isWithLigth) &&
        Objects.equals(this.hasRentals, gbLTSActivityPoiLocalized.hasRentals) &&
        Objects.equals(this.hasFreeEntrance, gbLTSActivityPoiLocalized.hasFreeEntrance) &&
        Objects.equals(this.liftAvailable, gbLTSActivityPoiLocalized.liftAvailable) &&
        Objects.equals(this.feetClimb, gbLTSActivityPoiLocalized.feetClimb) &&
        Objects.equals(this.bikeTransport, gbLTSActivityPoiLocalized.bikeTransport) &&
        Objects.equals(this.operationSchedule, gbLTSActivityPoiLocalized.operationSchedule) &&
        Objects.equals(this.gpsInfo, gbLTSActivityPoiLocalized.gpsInfo) &&
        Objects.equals(this.gpsTrack, gbLTSActivityPoiLocalized.gpsTrack) &&
        Objects.equals(this.imageGallery, gbLTSActivityPoiLocalized.imageGallery) &&
        Objects.equals(this.detail, gbLTSActivityPoiLocalized.detail) &&
        Objects.equals(this.contactInfos, gbLTSActivityPoiLocalized.contactInfos) &&
        Objects.equals(this.additionalPoiInfos, gbLTSActivityPoiLocalized.additionalPoiInfos) &&
        Objects.equals(this.ratings, gbLTSActivityPoiLocalized.ratings) &&
        Objects.equals(this.exposition, gbLTSActivityPoiLocalized.exposition) &&
        Objects.equals(this.smgTags, gbLTSActivityPoiLocalized.smgTags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gpsPoints, ltSTags, id, active, shortname, smgId, highlight, difficulty, type, subType, firstImport, lastChange, smgActive, locationInfo, tourismorganizationId, areaId, altitudeDifference, altitudeHighestPoint, altitudeLowestPoint, altitudeSumUp, altitudeSumDown, distanceDuration, distanceLength, isOpen, isPrepared, runToValley, isWithLigth, hasRentals, hasFreeEntrance, liftAvailable, feetClimb, bikeTransport, operationSchedule, gpsInfo, gpsTrack, imageGallery, detail, contactInfos, additionalPoiInfos, ratings, exposition, smgTags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GBLTSActivityPoiLocalized {\n");
    
    sb.append("    gpsPoints: ").append(toIndentedString(gpsPoints)).append("\n");
    sb.append("    ltSTags: ").append(toIndentedString(ltSTags)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    shortname: ").append(toIndentedString(shortname)).append("\n");
    sb.append("    smgId: ").append(toIndentedString(smgId)).append("\n");
    sb.append("    highlight: ").append(toIndentedString(highlight)).append("\n");
    sb.append("    difficulty: ").append(toIndentedString(difficulty)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    subType: ").append(toIndentedString(subType)).append("\n");
    sb.append("    firstImport: ").append(toIndentedString(firstImport)).append("\n");
    sb.append("    lastChange: ").append(toIndentedString(lastChange)).append("\n");
    sb.append("    smgActive: ").append(toIndentedString(smgActive)).append("\n");
    sb.append("    locationInfo: ").append(toIndentedString(locationInfo)).append("\n");
    sb.append("    tourismorganizationId: ").append(toIndentedString(tourismorganizationId)).append("\n");
    sb.append("    areaId: ").append(toIndentedString(areaId)).append("\n");
    sb.append("    altitudeDifference: ").append(toIndentedString(altitudeDifference)).append("\n");
    sb.append("    altitudeHighestPoint: ").append(toIndentedString(altitudeHighestPoint)).append("\n");
    sb.append("    altitudeLowestPoint: ").append(toIndentedString(altitudeLowestPoint)).append("\n");
    sb.append("    altitudeSumUp: ").append(toIndentedString(altitudeSumUp)).append("\n");
    sb.append("    altitudeSumDown: ").append(toIndentedString(altitudeSumDown)).append("\n");
    sb.append("    distanceDuration: ").append(toIndentedString(distanceDuration)).append("\n");
    sb.append("    distanceLength: ").append(toIndentedString(distanceLength)).append("\n");
    sb.append("    isOpen: ").append(toIndentedString(isOpen)).append("\n");
    sb.append("    isPrepared: ").append(toIndentedString(isPrepared)).append("\n");
    sb.append("    runToValley: ").append(toIndentedString(runToValley)).append("\n");
    sb.append("    isWithLigth: ").append(toIndentedString(isWithLigth)).append("\n");
    sb.append("    hasRentals: ").append(toIndentedString(hasRentals)).append("\n");
    sb.append("    hasFreeEntrance: ").append(toIndentedString(hasFreeEntrance)).append("\n");
    sb.append("    liftAvailable: ").append(toIndentedString(liftAvailable)).append("\n");
    sb.append("    feetClimb: ").append(toIndentedString(feetClimb)).append("\n");
    sb.append("    bikeTransport: ").append(toIndentedString(bikeTransport)).append("\n");
    sb.append("    operationSchedule: ").append(toIndentedString(operationSchedule)).append("\n");
    sb.append("    gpsInfo: ").append(toIndentedString(gpsInfo)).append("\n");
    sb.append("    gpsTrack: ").append(toIndentedString(gpsTrack)).append("\n");
    sb.append("    imageGallery: ").append(toIndentedString(imageGallery)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    contactInfos: ").append(toIndentedString(contactInfos)).append("\n");
    sb.append("    additionalPoiInfos: ").append(toIndentedString(additionalPoiInfos)).append("\n");
    sb.append("    ratings: ").append(toIndentedString(ratings)).append("\n");
    sb.append("    exposition: ").append(toIndentedString(exposition)).append("\n");
    sb.append("    smgTags: ").append(toIndentedString(smgTags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

