/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LoginPostModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class LoginPostModel {
  @JsonProperty("username")
  private String username = null;

  @JsonProperty("pswd")
  private String pswd = null;

  @JsonProperty("returnurl")
  private String returnurl = null;

  public LoginPostModel username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public LoginPostModel pswd(String pswd) {
    this.pswd = pswd;
    return this;
  }

   /**
   * Get pswd
   * @return pswd
  **/
  @ApiModelProperty(value = "")
  public String getPswd() {
    return pswd;
  }

  public void setPswd(String pswd) {
    this.pswd = pswd;
  }

  public LoginPostModel returnurl(String returnurl) {
    this.returnurl = returnurl;
    return this;
  }

   /**
   * Get returnurl
   * @return returnurl
  **/
  @ApiModelProperty(value = "")
  public String getReturnurl() {
    return returnurl;
  }

  public void setReturnurl(String returnurl) {
    this.returnurl = returnurl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginPostModel loginPostModel = (LoginPostModel) o;
    return Objects.equals(this.username, loginPostModel.username) &&
        Objects.equals(this.pswd, loginPostModel.pswd) &&
        Objects.equals(this.returnurl, loginPostModel.returnurl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, pswd, returnurl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginPostModel {\n");
    
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    pswd: ").append(toIndentedString(pswd)).append("\n");
    sb.append("    returnurl: ").append(toIndentedString(returnurl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

