/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * Mountain
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class Mountain {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("Title")
  private String title = null;

  @JsonProperty("Conditions")
  private String conditions = null;

  @JsonProperty("Weatherdesc")
  private String weatherdesc = null;

  @JsonProperty("Zerolimit")
  private String zerolimit = null;

  @JsonProperty("MountainImgurl")
  private String mountainImgurl = null;

  @JsonProperty("Reliability")
  private String reliability = null;

  @JsonProperty("Sunrise")
  private String sunrise = null;

  @JsonProperty("Sunset")
  private String sunset = null;

  @JsonProperty("Moonrise")
  private String moonrise = null;

  @JsonProperty("Moonset")
  private String moonset = null;

  @JsonProperty("Northcode")
  private String northcode = null;

  @JsonProperty("Northdesc")
  private String northdesc = null;

  @JsonProperty("Northimgurl")
  private String northimgurl = null;

  @JsonProperty("Southcode")
  private String southcode = null;

  @JsonProperty("Southdesc")
  private String southdesc = null;

  @JsonProperty("Southimgurl")
  private String southimgurl = null;

  @JsonProperty("Temp1000")
  private Integer temp1000 = null;

  @JsonProperty("Temp2000")
  private Integer temp2000 = null;

  @JsonProperty("Temp3000")
  private Integer temp3000 = null;

  @JsonProperty("Temp4000")
  private Integer temp4000 = null;

  @JsonProperty("Windcode")
  private String windcode = null;

  @JsonProperty("Winddesc")
  private String winddesc = null;

  @JsonProperty("WindImgurl")
  private String windImgurl = null;

  public Mountain date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Mountain title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Mountain conditions(String conditions) {
    this.conditions = conditions;
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  @ApiModelProperty(value = "")
  public String getConditions() {
    return conditions;
  }

  public void setConditions(String conditions) {
    this.conditions = conditions;
  }

  public Mountain weatherdesc(String weatherdesc) {
    this.weatherdesc = weatherdesc;
    return this;
  }

   /**
   * Get weatherdesc
   * @return weatherdesc
  **/
  @ApiModelProperty(value = "")
  public String getWeatherdesc() {
    return weatherdesc;
  }

  public void setWeatherdesc(String weatherdesc) {
    this.weatherdesc = weatherdesc;
  }

  public Mountain zerolimit(String zerolimit) {
    this.zerolimit = zerolimit;
    return this;
  }

   /**
   * Get zerolimit
   * @return zerolimit
  **/
  @ApiModelProperty(value = "")
  public String getZerolimit() {
    return zerolimit;
  }

  public void setZerolimit(String zerolimit) {
    this.zerolimit = zerolimit;
  }

  public Mountain mountainImgurl(String mountainImgurl) {
    this.mountainImgurl = mountainImgurl;
    return this;
  }

   /**
   * Get mountainImgurl
   * @return mountainImgurl
  **/
  @ApiModelProperty(value = "")
  public String getMountainImgurl() {
    return mountainImgurl;
  }

  public void setMountainImgurl(String mountainImgurl) {
    this.mountainImgurl = mountainImgurl;
  }

  public Mountain reliability(String reliability) {
    this.reliability = reliability;
    return this;
  }

   /**
   * Get reliability
   * @return reliability
  **/
  @ApiModelProperty(value = "")
  public String getReliability() {
    return reliability;
  }

  public void setReliability(String reliability) {
    this.reliability = reliability;
  }

  public Mountain sunrise(String sunrise) {
    this.sunrise = sunrise;
    return this;
  }

   /**
   * Get sunrise
   * @return sunrise
  **/
  @ApiModelProperty(value = "")
  public String getSunrise() {
    return sunrise;
  }

  public void setSunrise(String sunrise) {
    this.sunrise = sunrise;
  }

  public Mountain sunset(String sunset) {
    this.sunset = sunset;
    return this;
  }

   /**
   * Get sunset
   * @return sunset
  **/
  @ApiModelProperty(value = "")
  public String getSunset() {
    return sunset;
  }

  public void setSunset(String sunset) {
    this.sunset = sunset;
  }

  public Mountain moonrise(String moonrise) {
    this.moonrise = moonrise;
    return this;
  }

   /**
   * Get moonrise
   * @return moonrise
  **/
  @ApiModelProperty(value = "")
  public String getMoonrise() {
    return moonrise;
  }

  public void setMoonrise(String moonrise) {
    this.moonrise = moonrise;
  }

  public Mountain moonset(String moonset) {
    this.moonset = moonset;
    return this;
  }

   /**
   * Get moonset
   * @return moonset
  **/
  @ApiModelProperty(value = "")
  public String getMoonset() {
    return moonset;
  }

  public void setMoonset(String moonset) {
    this.moonset = moonset;
  }

  public Mountain northcode(String northcode) {
    this.northcode = northcode;
    return this;
  }

   /**
   * Get northcode
   * @return northcode
  **/
  @ApiModelProperty(value = "")
  public String getNorthcode() {
    return northcode;
  }

  public void setNorthcode(String northcode) {
    this.northcode = northcode;
  }

  public Mountain northdesc(String northdesc) {
    this.northdesc = northdesc;
    return this;
  }

   /**
   * Get northdesc
   * @return northdesc
  **/
  @ApiModelProperty(value = "")
  public String getNorthdesc() {
    return northdesc;
  }

  public void setNorthdesc(String northdesc) {
    this.northdesc = northdesc;
  }

  public Mountain northimgurl(String northimgurl) {
    this.northimgurl = northimgurl;
    return this;
  }

   /**
   * Get northimgurl
   * @return northimgurl
  **/
  @ApiModelProperty(value = "")
  public String getNorthimgurl() {
    return northimgurl;
  }

  public void setNorthimgurl(String northimgurl) {
    this.northimgurl = northimgurl;
  }

  public Mountain southcode(String southcode) {
    this.southcode = southcode;
    return this;
  }

   /**
   * Get southcode
   * @return southcode
  **/
  @ApiModelProperty(value = "")
  public String getSouthcode() {
    return southcode;
  }

  public void setSouthcode(String southcode) {
    this.southcode = southcode;
  }

  public Mountain southdesc(String southdesc) {
    this.southdesc = southdesc;
    return this;
  }

   /**
   * Get southdesc
   * @return southdesc
  **/
  @ApiModelProperty(value = "")
  public String getSouthdesc() {
    return southdesc;
  }

  public void setSouthdesc(String southdesc) {
    this.southdesc = southdesc;
  }

  public Mountain southimgurl(String southimgurl) {
    this.southimgurl = southimgurl;
    return this;
  }

   /**
   * Get southimgurl
   * @return southimgurl
  **/
  @ApiModelProperty(value = "")
  public String getSouthimgurl() {
    return southimgurl;
  }

  public void setSouthimgurl(String southimgurl) {
    this.southimgurl = southimgurl;
  }

  public Mountain temp1000(Integer temp1000) {
    this.temp1000 = temp1000;
    return this;
  }

   /**
   * Get temp1000
   * @return temp1000
  **/
  @ApiModelProperty(value = "")
  public Integer getTemp1000() {
    return temp1000;
  }

  public void setTemp1000(Integer temp1000) {
    this.temp1000 = temp1000;
  }

  public Mountain temp2000(Integer temp2000) {
    this.temp2000 = temp2000;
    return this;
  }

   /**
   * Get temp2000
   * @return temp2000
  **/
  @ApiModelProperty(value = "")
  public Integer getTemp2000() {
    return temp2000;
  }

  public void setTemp2000(Integer temp2000) {
    this.temp2000 = temp2000;
  }

  public Mountain temp3000(Integer temp3000) {
    this.temp3000 = temp3000;
    return this;
  }

   /**
   * Get temp3000
   * @return temp3000
  **/
  @ApiModelProperty(value = "")
  public Integer getTemp3000() {
    return temp3000;
  }

  public void setTemp3000(Integer temp3000) {
    this.temp3000 = temp3000;
  }

  public Mountain temp4000(Integer temp4000) {
    this.temp4000 = temp4000;
    return this;
  }

   /**
   * Get temp4000
   * @return temp4000
  **/
  @ApiModelProperty(value = "")
  public Integer getTemp4000() {
    return temp4000;
  }

  public void setTemp4000(Integer temp4000) {
    this.temp4000 = temp4000;
  }

  public Mountain windcode(String windcode) {
    this.windcode = windcode;
    return this;
  }

   /**
   * Get windcode
   * @return windcode
  **/
  @ApiModelProperty(value = "")
  public String getWindcode() {
    return windcode;
  }

  public void setWindcode(String windcode) {
    this.windcode = windcode;
  }

  public Mountain winddesc(String winddesc) {
    this.winddesc = winddesc;
    return this;
  }

   /**
   * Get winddesc
   * @return winddesc
  **/
  @ApiModelProperty(value = "")
  public String getWinddesc() {
    return winddesc;
  }

  public void setWinddesc(String winddesc) {
    this.winddesc = winddesc;
  }

  public Mountain windImgurl(String windImgurl) {
    this.windImgurl = windImgurl;
    return this;
  }

   /**
   * Get windImgurl
   * @return windImgurl
  **/
  @ApiModelProperty(value = "")
  public String getWindImgurl() {
    return windImgurl;
  }

  public void setWindImgurl(String windImgurl) {
    this.windImgurl = windImgurl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mountain mountain = (Mountain) o;
    return Objects.equals(this.date, mountain.date) &&
        Objects.equals(this.title, mountain.title) &&
        Objects.equals(this.conditions, mountain.conditions) &&
        Objects.equals(this.weatherdesc, mountain.weatherdesc) &&
        Objects.equals(this.zerolimit, mountain.zerolimit) &&
        Objects.equals(this.mountainImgurl, mountain.mountainImgurl) &&
        Objects.equals(this.reliability, mountain.reliability) &&
        Objects.equals(this.sunrise, mountain.sunrise) &&
        Objects.equals(this.sunset, mountain.sunset) &&
        Objects.equals(this.moonrise, mountain.moonrise) &&
        Objects.equals(this.moonset, mountain.moonset) &&
        Objects.equals(this.northcode, mountain.northcode) &&
        Objects.equals(this.northdesc, mountain.northdesc) &&
        Objects.equals(this.northimgurl, mountain.northimgurl) &&
        Objects.equals(this.southcode, mountain.southcode) &&
        Objects.equals(this.southdesc, mountain.southdesc) &&
        Objects.equals(this.southimgurl, mountain.southimgurl) &&
        Objects.equals(this.temp1000, mountain.temp1000) &&
        Objects.equals(this.temp2000, mountain.temp2000) &&
        Objects.equals(this.temp3000, mountain.temp3000) &&
        Objects.equals(this.temp4000, mountain.temp4000) &&
        Objects.equals(this.windcode, mountain.windcode) &&
        Objects.equals(this.winddesc, mountain.winddesc) &&
        Objects.equals(this.windImgurl, mountain.windImgurl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, title, conditions, weatherdesc, zerolimit, mountainImgurl, reliability, sunrise, sunset, moonrise, moonset, northcode, northdesc, northimgurl, southcode, southdesc, southimgurl, temp1000, temp2000, temp3000, temp4000, windcode, winddesc, windImgurl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mountain {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    weatherdesc: ").append(toIndentedString(weatherdesc)).append("\n");
    sb.append("    zerolimit: ").append(toIndentedString(zerolimit)).append("\n");
    sb.append("    mountainImgurl: ").append(toIndentedString(mountainImgurl)).append("\n");
    sb.append("    reliability: ").append(toIndentedString(reliability)).append("\n");
    sb.append("    sunrise: ").append(toIndentedString(sunrise)).append("\n");
    sb.append("    sunset: ").append(toIndentedString(sunset)).append("\n");
    sb.append("    moonrise: ").append(toIndentedString(moonrise)).append("\n");
    sb.append("    moonset: ").append(toIndentedString(moonset)).append("\n");
    sb.append("    northcode: ").append(toIndentedString(northcode)).append("\n");
    sb.append("    northdesc: ").append(toIndentedString(northdesc)).append("\n");
    sb.append("    northimgurl: ").append(toIndentedString(northimgurl)).append("\n");
    sb.append("    southcode: ").append(toIndentedString(southcode)).append("\n");
    sb.append("    southdesc: ").append(toIndentedString(southdesc)).append("\n");
    sb.append("    southimgurl: ").append(toIndentedString(southimgurl)).append("\n");
    sb.append("    temp1000: ").append(toIndentedString(temp1000)).append("\n");
    sb.append("    temp2000: ").append(toIndentedString(temp2000)).append("\n");
    sb.append("    temp3000: ").append(toIndentedString(temp3000)).append("\n");
    sb.append("    temp4000: ").append(toIndentedString(temp4000)).append("\n");
    sb.append("    windcode: ").append(toIndentedString(windcode)).append("\n");
    sb.append("    winddesc: ").append(toIndentedString(winddesc)).append("\n");
    sb.append("    windImgurl: ").append(toIndentedString(windImgurl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

