/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * ODHActivityPoiLocalized
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class ODHActivityPoiLocalized {
  @JsonProperty("GpsPoints")
  private Map<String, GpsInfo> gpsPoints = null;

  @JsonProperty("PoiType")
  private String poiType = null;

  @JsonProperty("PoiProperty")
  private List<PoiProperty> poiProperty = null;

  @JsonProperty("PoiServices")
  private List<String> poiServices = null;

  @JsonProperty("Source")
  private String source = null;

  @JsonProperty("SyncSourceInterface")
  private String syncSourceInterface = null;

  @JsonProperty("SyncUpdateMode")
  private String syncUpdateMode = null;

  @JsonProperty("AgeFrom")
  private Integer ageFrom = null;

  @JsonProperty("AgeTo")
  private Integer ageTo = null;

  @JsonProperty("MaxSeatingCapacity")
  private Integer maxSeatingCapacity = null;

  @JsonProperty("CategoryCodes")
  private List<CategoryCodes> categoryCodes = null;

  @JsonProperty("DishRates")
  private List<DishRates> dishRates = null;

  @JsonProperty("CapacityCeremony")
  private List<CapacityCeremony> capacityCeremony = null;

  @JsonProperty("Facilities")
  private List<Facilities> facilities = null;

  @JsonProperty("RelatedContent")
  private List<RelatedContent> relatedContent = null;

  @JsonProperty("Id")
  private String id = null;

  @JsonProperty("Active")
  private Boolean active = null;

  @JsonProperty("Shortname")
  private String shortname = null;

  @JsonProperty("SmgId")
  private String smgId = null;

  @JsonProperty("Highlight")
  private Boolean highlight = null;

  @JsonProperty("Difficulty")
  private String difficulty = null;

  @JsonProperty("Type")
  private String type = null;

  @JsonProperty("SubType")
  private String subType = null;

  @JsonProperty("FirstImport")
  private String firstImport = null;

  @JsonProperty("LastChange")
  private String lastChange = null;

  @JsonProperty("SmgActive")
  private Boolean smgActive = null;

  @JsonProperty("LocationInfo")
  private LocationInfoLocalized locationInfo = null;

  @JsonProperty("TourismorganizationId")
  private String tourismorganizationId = null;

  @JsonProperty("AreaId")
  private List<String> areaId = null;

  @JsonProperty("AltitudeDifference")
  private Double altitudeDifference = null;

  @JsonProperty("AltitudeHighestPoint")
  private Double altitudeHighestPoint = null;

  @JsonProperty("AltitudeLowestPoint")
  private Double altitudeLowestPoint = null;

  @JsonProperty("AltitudeSumUp")
  private Double altitudeSumUp = null;

  @JsonProperty("AltitudeSumDown")
  private Double altitudeSumDown = null;

  @JsonProperty("DistanceDuration")
  private Double distanceDuration = null;

  @JsonProperty("DistanceLength")
  private Double distanceLength = null;

  @JsonProperty("IsOpen")
  private Boolean isOpen = null;

  @JsonProperty("IsPrepared")
  private Boolean isPrepared = null;

  @JsonProperty("RunToValley")
  private Boolean runToValley = null;

  @JsonProperty("IsWithLigth")
  private Boolean isWithLigth = null;

  @JsonProperty("HasRentals")
  private Boolean hasRentals = null;

  @JsonProperty("HasFreeEntrance")
  private Boolean hasFreeEntrance = null;

  @JsonProperty("LiftAvailable")
  private Boolean liftAvailable = null;

  @JsonProperty("FeetClimb")
  private Boolean feetClimb = null;

  @JsonProperty("BikeTransport")
  private Boolean bikeTransport = null;

  @JsonProperty("OperationSchedule")
  private List<OperationSchedule> operationSchedule = null;

  @JsonProperty("GpsInfo")
  private List<GpsInfo> gpsInfo = null;

  @JsonProperty("GpsTrack")
  private List<GpsTrack> gpsTrack = null;

  @JsonProperty("ImageGallery")
  private List<ImageGalleryLocalized> imageGallery = null;

  @JsonProperty("Detail")
  private Detail detail = null;

  @JsonProperty("ContactInfos")
  private ContactInfos contactInfos = null;

  @JsonProperty("AdditionalPoiInfos")
  private AdditionalPoiInfos additionalPoiInfos = null;

  @JsonProperty("Ratings")
  private Ratings ratings = null;

  @JsonProperty("Exposition")
  private List<String> exposition = null;

  @JsonProperty("SmgTags")
  private List<String> smgTags = null;

  public ODHActivityPoiLocalized gpsPoints(Map<String, GpsInfo> gpsPoints) {
    this.gpsPoints = gpsPoints;
    return this;
  }

  public ODHActivityPoiLocalized putGpsPointsItem(String key, GpsInfo gpsPointsItem) {
    if (this.gpsPoints == null) {
      this.gpsPoints = new HashMap<>();
    }
    this.gpsPoints.put(key, gpsPointsItem);
    return this;
  }

   /**
   * Get gpsPoints
   * @return gpsPoints
  **/
  @ApiModelProperty(value = "")
  public Map<String, GpsInfo> getGpsPoints() {
    return gpsPoints;
  }

  public void setGpsPoints(Map<String, GpsInfo> gpsPoints) {
    this.gpsPoints = gpsPoints;
  }

  public ODHActivityPoiLocalized poiType(String poiType) {
    this.poiType = poiType;
    return this;
  }

   /**
   * Get poiType
   * @return poiType
  **/
  @ApiModelProperty(value = "")
  public String getPoiType() {
    return poiType;
  }

  public void setPoiType(String poiType) {
    this.poiType = poiType;
  }

  public ODHActivityPoiLocalized poiProperty(List<PoiProperty> poiProperty) {
    this.poiProperty = poiProperty;
    return this;
  }

  public ODHActivityPoiLocalized addPoiPropertyItem(PoiProperty poiPropertyItem) {
    if (this.poiProperty == null) {
      this.poiProperty = new ArrayList<>();
    }
    this.poiProperty.add(poiPropertyItem);
    return this;
  }

   /**
   * Get poiProperty
   * @return poiProperty
  **/
  @ApiModelProperty(value = "")
  public List<PoiProperty> getPoiProperty() {
    return poiProperty;
  }

  public void setPoiProperty(List<PoiProperty> poiProperty) {
    this.poiProperty = poiProperty;
  }

  public ODHActivityPoiLocalized poiServices(List<String> poiServices) {
    this.poiServices = poiServices;
    return this;
  }

  public ODHActivityPoiLocalized addPoiServicesItem(String poiServicesItem) {
    if (this.poiServices == null) {
      this.poiServices = new ArrayList<>();
    }
    this.poiServices.add(poiServicesItem);
    return this;
  }

   /**
   * Get poiServices
   * @return poiServices
  **/
  @ApiModelProperty(value = "")
  public List<String> getPoiServices() {
    return poiServices;
  }

  public void setPoiServices(List<String> poiServices) {
    this.poiServices = poiServices;
  }

  public ODHActivityPoiLocalized source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @ApiModelProperty(value = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public ODHActivityPoiLocalized syncSourceInterface(String syncSourceInterface) {
    this.syncSourceInterface = syncSourceInterface;
    return this;
  }

   /**
   * Get syncSourceInterface
   * @return syncSourceInterface
  **/
  @ApiModelProperty(value = "")
  public String getSyncSourceInterface() {
    return syncSourceInterface;
  }

  public void setSyncSourceInterface(String syncSourceInterface) {
    this.syncSourceInterface = syncSourceInterface;
  }

  public ODHActivityPoiLocalized syncUpdateMode(String syncUpdateMode) {
    this.syncUpdateMode = syncUpdateMode;
    return this;
  }

   /**
   * Get syncUpdateMode
   * @return syncUpdateMode
  **/
  @ApiModelProperty(value = "")
  public String getSyncUpdateMode() {
    return syncUpdateMode;
  }

  public void setSyncUpdateMode(String syncUpdateMode) {
    this.syncUpdateMode = syncUpdateMode;
  }

  public ODHActivityPoiLocalized ageFrom(Integer ageFrom) {
    this.ageFrom = ageFrom;
    return this;
  }

   /**
   * Get ageFrom
   * @return ageFrom
  **/
  @ApiModelProperty(value = "")
  public Integer getAgeFrom() {
    return ageFrom;
  }

  public void setAgeFrom(Integer ageFrom) {
    this.ageFrom = ageFrom;
  }

  public ODHActivityPoiLocalized ageTo(Integer ageTo) {
    this.ageTo = ageTo;
    return this;
  }

   /**
   * Get ageTo
   * @return ageTo
  **/
  @ApiModelProperty(value = "")
  public Integer getAgeTo() {
    return ageTo;
  }

  public void setAgeTo(Integer ageTo) {
    this.ageTo = ageTo;
  }

  public ODHActivityPoiLocalized maxSeatingCapacity(Integer maxSeatingCapacity) {
    this.maxSeatingCapacity = maxSeatingCapacity;
    return this;
  }

   /**
   * Get maxSeatingCapacity
   * @return maxSeatingCapacity
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxSeatingCapacity() {
    return maxSeatingCapacity;
  }

  public void setMaxSeatingCapacity(Integer maxSeatingCapacity) {
    this.maxSeatingCapacity = maxSeatingCapacity;
  }

  public ODHActivityPoiLocalized categoryCodes(List<CategoryCodes> categoryCodes) {
    this.categoryCodes = categoryCodes;
    return this;
  }

  public ODHActivityPoiLocalized addCategoryCodesItem(CategoryCodes categoryCodesItem) {
    if (this.categoryCodes == null) {
      this.categoryCodes = new ArrayList<>();
    }
    this.categoryCodes.add(categoryCodesItem);
    return this;
  }

   /**
   * Get categoryCodes
   * @return categoryCodes
  **/
  @ApiModelProperty(value = "")
  public List<CategoryCodes> getCategoryCodes() {
    return categoryCodes;
  }

  public void setCategoryCodes(List<CategoryCodes> categoryCodes) {
    this.categoryCodes = categoryCodes;
  }

  public ODHActivityPoiLocalized dishRates(List<DishRates> dishRates) {
    this.dishRates = dishRates;
    return this;
  }

  public ODHActivityPoiLocalized addDishRatesItem(DishRates dishRatesItem) {
    if (this.dishRates == null) {
      this.dishRates = new ArrayList<>();
    }
    this.dishRates.add(dishRatesItem);
    return this;
  }

   /**
   * Get dishRates
   * @return dishRates
  **/
  @ApiModelProperty(value = "")
  public List<DishRates> getDishRates() {
    return dishRates;
  }

  public void setDishRates(List<DishRates> dishRates) {
    this.dishRates = dishRates;
  }

  public ODHActivityPoiLocalized capacityCeremony(List<CapacityCeremony> capacityCeremony) {
    this.capacityCeremony = capacityCeremony;
    return this;
  }

  public ODHActivityPoiLocalized addCapacityCeremonyItem(CapacityCeremony capacityCeremonyItem) {
    if (this.capacityCeremony == null) {
      this.capacityCeremony = new ArrayList<>();
    }
    this.capacityCeremony.add(capacityCeremonyItem);
    return this;
  }

   /**
   * Get capacityCeremony
   * @return capacityCeremony
  **/
  @ApiModelProperty(value = "")
  public List<CapacityCeremony> getCapacityCeremony() {
    return capacityCeremony;
  }

  public void setCapacityCeremony(List<CapacityCeremony> capacityCeremony) {
    this.capacityCeremony = capacityCeremony;
  }

  public ODHActivityPoiLocalized facilities(List<Facilities> facilities) {
    this.facilities = facilities;
    return this;
  }

  public ODHActivityPoiLocalized addFacilitiesItem(Facilities facilitiesItem) {
    if (this.facilities == null) {
      this.facilities = new ArrayList<>();
    }
    this.facilities.add(facilitiesItem);
    return this;
  }

   /**
   * Get facilities
   * @return facilities
  **/
  @ApiModelProperty(value = "")
  public List<Facilities> getFacilities() {
    return facilities;
  }

  public void setFacilities(List<Facilities> facilities) {
    this.facilities = facilities;
  }

  public ODHActivityPoiLocalized relatedContent(List<RelatedContent> relatedContent) {
    this.relatedContent = relatedContent;
    return this;
  }

  public ODHActivityPoiLocalized addRelatedContentItem(RelatedContent relatedContentItem) {
    if (this.relatedContent == null) {
      this.relatedContent = new ArrayList<>();
    }
    this.relatedContent.add(relatedContentItem);
    return this;
  }

   /**
   * Get relatedContent
   * @return relatedContent
  **/
  @ApiModelProperty(value = "")
  public List<RelatedContent> getRelatedContent() {
    return relatedContent;
  }

  public void setRelatedContent(List<RelatedContent> relatedContent) {
    this.relatedContent = relatedContent;
  }

  public ODHActivityPoiLocalized id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ODHActivityPoiLocalized active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public ODHActivityPoiLocalized shortname(String shortname) {
    this.shortname = shortname;
    return this;
  }

   /**
   * Get shortname
   * @return shortname
  **/
  @ApiModelProperty(value = "")
  public String getShortname() {
    return shortname;
  }

  public void setShortname(String shortname) {
    this.shortname = shortname;
  }

  public ODHActivityPoiLocalized smgId(String smgId) {
    this.smgId = smgId;
    return this;
  }

   /**
   * Get smgId
   * @return smgId
  **/
  @ApiModelProperty(value = "")
  public String getSmgId() {
    return smgId;
  }

  public void setSmgId(String smgId) {
    this.smgId = smgId;
  }

  public ODHActivityPoiLocalized highlight(Boolean highlight) {
    this.highlight = highlight;
    return this;
  }

   /**
   * Get highlight
   * @return highlight
  **/
  @ApiModelProperty(value = "")
  public Boolean isHighlight() {
    return highlight;
  }

  public void setHighlight(Boolean highlight) {
    this.highlight = highlight;
  }

  public ODHActivityPoiLocalized difficulty(String difficulty) {
    this.difficulty = difficulty;
    return this;
  }

   /**
   * Get difficulty
   * @return difficulty
  **/
  @ApiModelProperty(value = "")
  public String getDifficulty() {
    return difficulty;
  }

  public void setDifficulty(String difficulty) {
    this.difficulty = difficulty;
  }

  public ODHActivityPoiLocalized type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ODHActivityPoiLocalized subType(String subType) {
    this.subType = subType;
    return this;
  }

   /**
   * Get subType
   * @return subType
  **/
  @ApiModelProperty(value = "")
  public String getSubType() {
    return subType;
  }

  public void setSubType(String subType) {
    this.subType = subType;
  }

  public ODHActivityPoiLocalized firstImport(String firstImport) {
    this.firstImport = firstImport;
    return this;
  }

   /**
   * Get firstImport
   * @return firstImport
  **/
  @ApiModelProperty(value = "")
  public String getFirstImport() {
    return firstImport;
  }

  public void setFirstImport(String firstImport) {
    this.firstImport = firstImport;
  }

  public ODHActivityPoiLocalized lastChange(String lastChange) {
    this.lastChange = lastChange;
    return this;
  }

   /**
   * Get lastChange
   * @return lastChange
  **/
  @ApiModelProperty(value = "")
  public String getLastChange() {
    return lastChange;
  }

  public void setLastChange(String lastChange) {
    this.lastChange = lastChange;
  }

  public ODHActivityPoiLocalized smgActive(Boolean smgActive) {
    this.smgActive = smgActive;
    return this;
  }

   /**
   * Get smgActive
   * @return smgActive
  **/
  @ApiModelProperty(value = "")
  public Boolean isSmgActive() {
    return smgActive;
  }

  public void setSmgActive(Boolean smgActive) {
    this.smgActive = smgActive;
  }

  public ODHActivityPoiLocalized locationInfo(LocationInfoLocalized locationInfo) {
    this.locationInfo = locationInfo;
    return this;
  }

   /**
   * Get locationInfo
   * @return locationInfo
  **/
  @ApiModelProperty(value = "")
  public LocationInfoLocalized getLocationInfo() {
    return locationInfo;
  }

  public void setLocationInfo(LocationInfoLocalized locationInfo) {
    this.locationInfo = locationInfo;
  }

  public ODHActivityPoiLocalized tourismorganizationId(String tourismorganizationId) {
    this.tourismorganizationId = tourismorganizationId;
    return this;
  }

   /**
   * Get tourismorganizationId
   * @return tourismorganizationId
  **/
  @ApiModelProperty(value = "")
  public String getTourismorganizationId() {
    return tourismorganizationId;
  }

  public void setTourismorganizationId(String tourismorganizationId) {
    this.tourismorganizationId = tourismorganizationId;
  }

  public ODHActivityPoiLocalized areaId(List<String> areaId) {
    this.areaId = areaId;
    return this;
  }

  public ODHActivityPoiLocalized addAreaIdItem(String areaIdItem) {
    if (this.areaId == null) {
      this.areaId = new ArrayList<>();
    }
    this.areaId.add(areaIdItem);
    return this;
  }

   /**
   * Get areaId
   * @return areaId
  **/
  @ApiModelProperty(value = "")
  public List<String> getAreaId() {
    return areaId;
  }

  public void setAreaId(List<String> areaId) {
    this.areaId = areaId;
  }

  public ODHActivityPoiLocalized altitudeDifference(Double altitudeDifference) {
    this.altitudeDifference = altitudeDifference;
    return this;
  }

   /**
   * Get altitudeDifference
   * @return altitudeDifference
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeDifference() {
    return altitudeDifference;
  }

  public void setAltitudeDifference(Double altitudeDifference) {
    this.altitudeDifference = altitudeDifference;
  }

  public ODHActivityPoiLocalized altitudeHighestPoint(Double altitudeHighestPoint) {
    this.altitudeHighestPoint = altitudeHighestPoint;
    return this;
  }

   /**
   * Get altitudeHighestPoint
   * @return altitudeHighestPoint
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeHighestPoint() {
    return altitudeHighestPoint;
  }

  public void setAltitudeHighestPoint(Double altitudeHighestPoint) {
    this.altitudeHighestPoint = altitudeHighestPoint;
  }

  public ODHActivityPoiLocalized altitudeLowestPoint(Double altitudeLowestPoint) {
    this.altitudeLowestPoint = altitudeLowestPoint;
    return this;
  }

   /**
   * Get altitudeLowestPoint
   * @return altitudeLowestPoint
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeLowestPoint() {
    return altitudeLowestPoint;
  }

  public void setAltitudeLowestPoint(Double altitudeLowestPoint) {
    this.altitudeLowestPoint = altitudeLowestPoint;
  }

  public ODHActivityPoiLocalized altitudeSumUp(Double altitudeSumUp) {
    this.altitudeSumUp = altitudeSumUp;
    return this;
  }

   /**
   * Get altitudeSumUp
   * @return altitudeSumUp
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeSumUp() {
    return altitudeSumUp;
  }

  public void setAltitudeSumUp(Double altitudeSumUp) {
    this.altitudeSumUp = altitudeSumUp;
  }

  public ODHActivityPoiLocalized altitudeSumDown(Double altitudeSumDown) {
    this.altitudeSumDown = altitudeSumDown;
    return this;
  }

   /**
   * Get altitudeSumDown
   * @return altitudeSumDown
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeSumDown() {
    return altitudeSumDown;
  }

  public void setAltitudeSumDown(Double altitudeSumDown) {
    this.altitudeSumDown = altitudeSumDown;
  }

  public ODHActivityPoiLocalized distanceDuration(Double distanceDuration) {
    this.distanceDuration = distanceDuration;
    return this;
  }

   /**
   * Get distanceDuration
   * @return distanceDuration
  **/
  @ApiModelProperty(value = "")
  public Double getDistanceDuration() {
    return distanceDuration;
  }

  public void setDistanceDuration(Double distanceDuration) {
    this.distanceDuration = distanceDuration;
  }

  public ODHActivityPoiLocalized distanceLength(Double distanceLength) {
    this.distanceLength = distanceLength;
    return this;
  }

   /**
   * Get distanceLength
   * @return distanceLength
  **/
  @ApiModelProperty(value = "")
  public Double getDistanceLength() {
    return distanceLength;
  }

  public void setDistanceLength(Double distanceLength) {
    this.distanceLength = distanceLength;
  }

  public ODHActivityPoiLocalized isOpen(Boolean isOpen) {
    this.isOpen = isOpen;
    return this;
  }

   /**
   * Get isOpen
   * @return isOpen
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsOpen() {
    return isOpen;
  }

  public void setIsOpen(Boolean isOpen) {
    this.isOpen = isOpen;
  }

  public ODHActivityPoiLocalized isPrepared(Boolean isPrepared) {
    this.isPrepared = isPrepared;
    return this;
  }

   /**
   * Get isPrepared
   * @return isPrepared
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPrepared() {
    return isPrepared;
  }

  public void setIsPrepared(Boolean isPrepared) {
    this.isPrepared = isPrepared;
  }

  public ODHActivityPoiLocalized runToValley(Boolean runToValley) {
    this.runToValley = runToValley;
    return this;
  }

   /**
   * Get runToValley
   * @return runToValley
  **/
  @ApiModelProperty(value = "")
  public Boolean isRunToValley() {
    return runToValley;
  }

  public void setRunToValley(Boolean runToValley) {
    this.runToValley = runToValley;
  }

  public ODHActivityPoiLocalized isWithLigth(Boolean isWithLigth) {
    this.isWithLigth = isWithLigth;
    return this;
  }

   /**
   * Get isWithLigth
   * @return isWithLigth
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsWithLigth() {
    return isWithLigth;
  }

  public void setIsWithLigth(Boolean isWithLigth) {
    this.isWithLigth = isWithLigth;
  }

  public ODHActivityPoiLocalized hasRentals(Boolean hasRentals) {
    this.hasRentals = hasRentals;
    return this;
  }

   /**
   * Get hasRentals
   * @return hasRentals
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasRentals() {
    return hasRentals;
  }

  public void setHasRentals(Boolean hasRentals) {
    this.hasRentals = hasRentals;
  }

  public ODHActivityPoiLocalized hasFreeEntrance(Boolean hasFreeEntrance) {
    this.hasFreeEntrance = hasFreeEntrance;
    return this;
  }

   /**
   * Get hasFreeEntrance
   * @return hasFreeEntrance
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasFreeEntrance() {
    return hasFreeEntrance;
  }

  public void setHasFreeEntrance(Boolean hasFreeEntrance) {
    this.hasFreeEntrance = hasFreeEntrance;
  }

  public ODHActivityPoiLocalized liftAvailable(Boolean liftAvailable) {
    this.liftAvailable = liftAvailable;
    return this;
  }

   /**
   * Get liftAvailable
   * @return liftAvailable
  **/
  @ApiModelProperty(value = "")
  public Boolean isLiftAvailable() {
    return liftAvailable;
  }

  public void setLiftAvailable(Boolean liftAvailable) {
    this.liftAvailable = liftAvailable;
  }

  public ODHActivityPoiLocalized feetClimb(Boolean feetClimb) {
    this.feetClimb = feetClimb;
    return this;
  }

   /**
   * Get feetClimb
   * @return feetClimb
  **/
  @ApiModelProperty(value = "")
  public Boolean isFeetClimb() {
    return feetClimb;
  }

  public void setFeetClimb(Boolean feetClimb) {
    this.feetClimb = feetClimb;
  }

  public ODHActivityPoiLocalized bikeTransport(Boolean bikeTransport) {
    this.bikeTransport = bikeTransport;
    return this;
  }

   /**
   * Get bikeTransport
   * @return bikeTransport
  **/
  @ApiModelProperty(value = "")
  public Boolean isBikeTransport() {
    return bikeTransport;
  }

  public void setBikeTransport(Boolean bikeTransport) {
    this.bikeTransport = bikeTransport;
  }

  public ODHActivityPoiLocalized operationSchedule(List<OperationSchedule> operationSchedule) {
    this.operationSchedule = operationSchedule;
    return this;
  }

  public ODHActivityPoiLocalized addOperationScheduleItem(OperationSchedule operationScheduleItem) {
    if (this.operationSchedule == null) {
      this.operationSchedule = new ArrayList<>();
    }
    this.operationSchedule.add(operationScheduleItem);
    return this;
  }

   /**
   * Get operationSchedule
   * @return operationSchedule
  **/
  @ApiModelProperty(value = "")
  public List<OperationSchedule> getOperationSchedule() {
    return operationSchedule;
  }

  public void setOperationSchedule(List<OperationSchedule> operationSchedule) {
    this.operationSchedule = operationSchedule;
  }

  public ODHActivityPoiLocalized gpsInfo(List<GpsInfo> gpsInfo) {
    this.gpsInfo = gpsInfo;
    return this;
  }

  public ODHActivityPoiLocalized addGpsInfoItem(GpsInfo gpsInfoItem) {
    if (this.gpsInfo == null) {
      this.gpsInfo = new ArrayList<>();
    }
    this.gpsInfo.add(gpsInfoItem);
    return this;
  }

   /**
   * Get gpsInfo
   * @return gpsInfo
  **/
  @ApiModelProperty(value = "")
  public List<GpsInfo> getGpsInfo() {
    return gpsInfo;
  }

  public void setGpsInfo(List<GpsInfo> gpsInfo) {
    this.gpsInfo = gpsInfo;
  }

  public ODHActivityPoiLocalized gpsTrack(List<GpsTrack> gpsTrack) {
    this.gpsTrack = gpsTrack;
    return this;
  }

  public ODHActivityPoiLocalized addGpsTrackItem(GpsTrack gpsTrackItem) {
    if (this.gpsTrack == null) {
      this.gpsTrack = new ArrayList<>();
    }
    this.gpsTrack.add(gpsTrackItem);
    return this;
  }

   /**
   * Get gpsTrack
   * @return gpsTrack
  **/
  @ApiModelProperty(value = "")
  public List<GpsTrack> getGpsTrack() {
    return gpsTrack;
  }

  public void setGpsTrack(List<GpsTrack> gpsTrack) {
    this.gpsTrack = gpsTrack;
  }

  public ODHActivityPoiLocalized imageGallery(List<ImageGalleryLocalized> imageGallery) {
    this.imageGallery = imageGallery;
    return this;
  }

  public ODHActivityPoiLocalized addImageGalleryItem(ImageGalleryLocalized imageGalleryItem) {
    if (this.imageGallery == null) {
      this.imageGallery = new ArrayList<>();
    }
    this.imageGallery.add(imageGalleryItem);
    return this;
  }

   /**
   * Get imageGallery
   * @return imageGallery
  **/
  @ApiModelProperty(value = "")
  public List<ImageGalleryLocalized> getImageGallery() {
    return imageGallery;
  }

  public void setImageGallery(List<ImageGalleryLocalized> imageGallery) {
    this.imageGallery = imageGallery;
  }

  public ODHActivityPoiLocalized detail(Detail detail) {
    this.detail = detail;
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @ApiModelProperty(value = "")
  public Detail getDetail() {
    return detail;
  }

  public void setDetail(Detail detail) {
    this.detail = detail;
  }

  public ODHActivityPoiLocalized contactInfos(ContactInfos contactInfos) {
    this.contactInfos = contactInfos;
    return this;
  }

   /**
   * Get contactInfos
   * @return contactInfos
  **/
  @ApiModelProperty(value = "")
  public ContactInfos getContactInfos() {
    return contactInfos;
  }

  public void setContactInfos(ContactInfos contactInfos) {
    this.contactInfos = contactInfos;
  }

  public ODHActivityPoiLocalized additionalPoiInfos(AdditionalPoiInfos additionalPoiInfos) {
    this.additionalPoiInfos = additionalPoiInfos;
    return this;
  }

   /**
   * Get additionalPoiInfos
   * @return additionalPoiInfos
  **/
  @ApiModelProperty(value = "")
  public AdditionalPoiInfos getAdditionalPoiInfos() {
    return additionalPoiInfos;
  }

  public void setAdditionalPoiInfos(AdditionalPoiInfos additionalPoiInfos) {
    this.additionalPoiInfos = additionalPoiInfos;
  }

  public ODHActivityPoiLocalized ratings(Ratings ratings) {
    this.ratings = ratings;
    return this;
  }

   /**
   * Get ratings
   * @return ratings
  **/
  @ApiModelProperty(value = "")
  public Ratings getRatings() {
    return ratings;
  }

  public void setRatings(Ratings ratings) {
    this.ratings = ratings;
  }

  public ODHActivityPoiLocalized exposition(List<String> exposition) {
    this.exposition = exposition;
    return this;
  }

  public ODHActivityPoiLocalized addExpositionItem(String expositionItem) {
    if (this.exposition == null) {
      this.exposition = new ArrayList<>();
    }
    this.exposition.add(expositionItem);
    return this;
  }

   /**
   * Get exposition
   * @return exposition
  **/
  @ApiModelProperty(value = "")
  public List<String> getExposition() {
    return exposition;
  }

  public void setExposition(List<String> exposition) {
    this.exposition = exposition;
  }

  public ODHActivityPoiLocalized smgTags(List<String> smgTags) {
    this.smgTags = smgTags;
    return this;
  }

  public ODHActivityPoiLocalized addSmgTagsItem(String smgTagsItem) {
    if (this.smgTags == null) {
      this.smgTags = new ArrayList<>();
    }
    this.smgTags.add(smgTagsItem);
    return this;
  }

   /**
   * Get smgTags
   * @return smgTags
  **/
  @ApiModelProperty(value = "")
  public List<String> getSmgTags() {
    return smgTags;
  }

  public void setSmgTags(List<String> smgTags) {
    this.smgTags = smgTags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ODHActivityPoiLocalized odHActivityPoiLocalized = (ODHActivityPoiLocalized) o;
    return Objects.equals(this.gpsPoints, odHActivityPoiLocalized.gpsPoints) &&
        Objects.equals(this.poiType, odHActivityPoiLocalized.poiType) &&
        Objects.equals(this.poiProperty, odHActivityPoiLocalized.poiProperty) &&
        Objects.equals(this.poiServices, odHActivityPoiLocalized.poiServices) &&
        Objects.equals(this.source, odHActivityPoiLocalized.source) &&
        Objects.equals(this.syncSourceInterface, odHActivityPoiLocalized.syncSourceInterface) &&
        Objects.equals(this.syncUpdateMode, odHActivityPoiLocalized.syncUpdateMode) &&
        Objects.equals(this.ageFrom, odHActivityPoiLocalized.ageFrom) &&
        Objects.equals(this.ageTo, odHActivityPoiLocalized.ageTo) &&
        Objects.equals(this.maxSeatingCapacity, odHActivityPoiLocalized.maxSeatingCapacity) &&
        Objects.equals(this.categoryCodes, odHActivityPoiLocalized.categoryCodes) &&
        Objects.equals(this.dishRates, odHActivityPoiLocalized.dishRates) &&
        Objects.equals(this.capacityCeremony, odHActivityPoiLocalized.capacityCeremony) &&
        Objects.equals(this.facilities, odHActivityPoiLocalized.facilities) &&
        Objects.equals(this.relatedContent, odHActivityPoiLocalized.relatedContent) &&
        Objects.equals(this.id, odHActivityPoiLocalized.id) &&
        Objects.equals(this.active, odHActivityPoiLocalized.active) &&
        Objects.equals(this.shortname, odHActivityPoiLocalized.shortname) &&
        Objects.equals(this.smgId, odHActivityPoiLocalized.smgId) &&
        Objects.equals(this.highlight, odHActivityPoiLocalized.highlight) &&
        Objects.equals(this.difficulty, odHActivityPoiLocalized.difficulty) &&
        Objects.equals(this.type, odHActivityPoiLocalized.type) &&
        Objects.equals(this.subType, odHActivityPoiLocalized.subType) &&
        Objects.equals(this.firstImport, odHActivityPoiLocalized.firstImport) &&
        Objects.equals(this.lastChange, odHActivityPoiLocalized.lastChange) &&
        Objects.equals(this.smgActive, odHActivityPoiLocalized.smgActive) &&
        Objects.equals(this.locationInfo, odHActivityPoiLocalized.locationInfo) &&
        Objects.equals(this.tourismorganizationId, odHActivityPoiLocalized.tourismorganizationId) &&
        Objects.equals(this.areaId, odHActivityPoiLocalized.areaId) &&
        Objects.equals(this.altitudeDifference, odHActivityPoiLocalized.altitudeDifference) &&
        Objects.equals(this.altitudeHighestPoint, odHActivityPoiLocalized.altitudeHighestPoint) &&
        Objects.equals(this.altitudeLowestPoint, odHActivityPoiLocalized.altitudeLowestPoint) &&
        Objects.equals(this.altitudeSumUp, odHActivityPoiLocalized.altitudeSumUp) &&
        Objects.equals(this.altitudeSumDown, odHActivityPoiLocalized.altitudeSumDown) &&
        Objects.equals(this.distanceDuration, odHActivityPoiLocalized.distanceDuration) &&
        Objects.equals(this.distanceLength, odHActivityPoiLocalized.distanceLength) &&
        Objects.equals(this.isOpen, odHActivityPoiLocalized.isOpen) &&
        Objects.equals(this.isPrepared, odHActivityPoiLocalized.isPrepared) &&
        Objects.equals(this.runToValley, odHActivityPoiLocalized.runToValley) &&
        Objects.equals(this.isWithLigth, odHActivityPoiLocalized.isWithLigth) &&
        Objects.equals(this.hasRentals, odHActivityPoiLocalized.hasRentals) &&
        Objects.equals(this.hasFreeEntrance, odHActivityPoiLocalized.hasFreeEntrance) &&
        Objects.equals(this.liftAvailable, odHActivityPoiLocalized.liftAvailable) &&
        Objects.equals(this.feetClimb, odHActivityPoiLocalized.feetClimb) &&
        Objects.equals(this.bikeTransport, odHActivityPoiLocalized.bikeTransport) &&
        Objects.equals(this.operationSchedule, odHActivityPoiLocalized.operationSchedule) &&
        Objects.equals(this.gpsInfo, odHActivityPoiLocalized.gpsInfo) &&
        Objects.equals(this.gpsTrack, odHActivityPoiLocalized.gpsTrack) &&
        Objects.equals(this.imageGallery, odHActivityPoiLocalized.imageGallery) &&
        Objects.equals(this.detail, odHActivityPoiLocalized.detail) &&
        Objects.equals(this.contactInfos, odHActivityPoiLocalized.contactInfos) &&
        Objects.equals(this.additionalPoiInfos, odHActivityPoiLocalized.additionalPoiInfos) &&
        Objects.equals(this.ratings, odHActivityPoiLocalized.ratings) &&
        Objects.equals(this.exposition, odHActivityPoiLocalized.exposition) &&
        Objects.equals(this.smgTags, odHActivityPoiLocalized.smgTags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gpsPoints, poiType, poiProperty, poiServices, source, syncSourceInterface, syncUpdateMode, ageFrom, ageTo, maxSeatingCapacity, categoryCodes, dishRates, capacityCeremony, facilities, relatedContent, id, active, shortname, smgId, highlight, difficulty, type, subType, firstImport, lastChange, smgActive, locationInfo, tourismorganizationId, areaId, altitudeDifference, altitudeHighestPoint, altitudeLowestPoint, altitudeSumUp, altitudeSumDown, distanceDuration, distanceLength, isOpen, isPrepared, runToValley, isWithLigth, hasRentals, hasFreeEntrance, liftAvailable, feetClimb, bikeTransport, operationSchedule, gpsInfo, gpsTrack, imageGallery, detail, contactInfos, additionalPoiInfos, ratings, exposition, smgTags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ODHActivityPoiLocalized {\n");
    
    sb.append("    gpsPoints: ").append(toIndentedString(gpsPoints)).append("\n");
    sb.append("    poiType: ").append(toIndentedString(poiType)).append("\n");
    sb.append("    poiProperty: ").append(toIndentedString(poiProperty)).append("\n");
    sb.append("    poiServices: ").append(toIndentedString(poiServices)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    syncSourceInterface: ").append(toIndentedString(syncSourceInterface)).append("\n");
    sb.append("    syncUpdateMode: ").append(toIndentedString(syncUpdateMode)).append("\n");
    sb.append("    ageFrom: ").append(toIndentedString(ageFrom)).append("\n");
    sb.append("    ageTo: ").append(toIndentedString(ageTo)).append("\n");
    sb.append("    maxSeatingCapacity: ").append(toIndentedString(maxSeatingCapacity)).append("\n");
    sb.append("    categoryCodes: ").append(toIndentedString(categoryCodes)).append("\n");
    sb.append("    dishRates: ").append(toIndentedString(dishRates)).append("\n");
    sb.append("    capacityCeremony: ").append(toIndentedString(capacityCeremony)).append("\n");
    sb.append("    facilities: ").append(toIndentedString(facilities)).append("\n");
    sb.append("    relatedContent: ").append(toIndentedString(relatedContent)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    shortname: ").append(toIndentedString(shortname)).append("\n");
    sb.append("    smgId: ").append(toIndentedString(smgId)).append("\n");
    sb.append("    highlight: ").append(toIndentedString(highlight)).append("\n");
    sb.append("    difficulty: ").append(toIndentedString(difficulty)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    subType: ").append(toIndentedString(subType)).append("\n");
    sb.append("    firstImport: ").append(toIndentedString(firstImport)).append("\n");
    sb.append("    lastChange: ").append(toIndentedString(lastChange)).append("\n");
    sb.append("    smgActive: ").append(toIndentedString(smgActive)).append("\n");
    sb.append("    locationInfo: ").append(toIndentedString(locationInfo)).append("\n");
    sb.append("    tourismorganizationId: ").append(toIndentedString(tourismorganizationId)).append("\n");
    sb.append("    areaId: ").append(toIndentedString(areaId)).append("\n");
    sb.append("    altitudeDifference: ").append(toIndentedString(altitudeDifference)).append("\n");
    sb.append("    altitudeHighestPoint: ").append(toIndentedString(altitudeHighestPoint)).append("\n");
    sb.append("    altitudeLowestPoint: ").append(toIndentedString(altitudeLowestPoint)).append("\n");
    sb.append("    altitudeSumUp: ").append(toIndentedString(altitudeSumUp)).append("\n");
    sb.append("    altitudeSumDown: ").append(toIndentedString(altitudeSumDown)).append("\n");
    sb.append("    distanceDuration: ").append(toIndentedString(distanceDuration)).append("\n");
    sb.append("    distanceLength: ").append(toIndentedString(distanceLength)).append("\n");
    sb.append("    isOpen: ").append(toIndentedString(isOpen)).append("\n");
    sb.append("    isPrepared: ").append(toIndentedString(isPrepared)).append("\n");
    sb.append("    runToValley: ").append(toIndentedString(runToValley)).append("\n");
    sb.append("    isWithLigth: ").append(toIndentedString(isWithLigth)).append("\n");
    sb.append("    hasRentals: ").append(toIndentedString(hasRentals)).append("\n");
    sb.append("    hasFreeEntrance: ").append(toIndentedString(hasFreeEntrance)).append("\n");
    sb.append("    liftAvailable: ").append(toIndentedString(liftAvailable)).append("\n");
    sb.append("    feetClimb: ").append(toIndentedString(feetClimb)).append("\n");
    sb.append("    bikeTransport: ").append(toIndentedString(bikeTransport)).append("\n");
    sb.append("    operationSchedule: ").append(toIndentedString(operationSchedule)).append("\n");
    sb.append("    gpsInfo: ").append(toIndentedString(gpsInfo)).append("\n");
    sb.append("    gpsTrack: ").append(toIndentedString(gpsTrack)).append("\n");
    sb.append("    imageGallery: ").append(toIndentedString(imageGallery)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    contactInfos: ").append(toIndentedString(contactInfos)).append("\n");
    sb.append("    additionalPoiInfos: ").append(toIndentedString(additionalPoiInfos)).append("\n");
    sb.append("    ratings: ").append(toIndentedString(ratings)).append("\n");
    sb.append("    exposition: ").append(toIndentedString(exposition)).append("\n");
    sb.append("    smgTags: ").append(toIndentedString(smgTags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

