/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * Penalty
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class Penalty {
  @JsonProperty("Percent")
  private Integer percent = null;

  @JsonProperty("Datefrom")
  private String datefrom = null;

  @JsonProperty("Daysarrival")
  private Integer daysarrival = null;

  public Penalty percent(Integer percent) {
    this.percent = percent;
    return this;
  }

   /**
   * Get percent
   * @return percent
  **/
  @ApiModelProperty(value = "")
  public Integer getPercent() {
    return percent;
  }

  public void setPercent(Integer percent) {
    this.percent = percent;
  }

  public Penalty datefrom(String datefrom) {
    this.datefrom = datefrom;
    return this;
  }

   /**
   * Get datefrom
   * @return datefrom
  **/
  @ApiModelProperty(value = "")
  public String getDatefrom() {
    return datefrom;
  }

  public void setDatefrom(String datefrom) {
    this.datefrom = datefrom;
  }

  public Penalty daysarrival(Integer daysarrival) {
    this.daysarrival = daysarrival;
    return this;
  }

   /**
   * Get daysarrival
   * @return daysarrival
  **/
  @ApiModelProperty(value = "")
  public Integer getDaysarrival() {
    return daysarrival;
  }

  public void setDaysarrival(Integer daysarrival) {
    this.daysarrival = daysarrival;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Penalty penalty = (Penalty) o;
    return Objects.equals(this.percent, penalty.percent) &&
        Objects.equals(this.datefrom, penalty.datefrom) &&
        Objects.equals(this.daysarrival, penalty.daysarrival);
  }

  @Override
  public int hashCode() {
    return Objects.hash(percent, datefrom, daysarrival);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Penalty {\n");
    
    sb.append("    percent: ").append(toIndentedString(percent)).append("\n");
    sb.append("    datefrom: ").append(toIndentedString(datefrom)).append("\n");
    sb.append("    daysarrival: ").append(toIndentedString(daysarrival)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

