/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * PoiBaseInfos
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class PoiBaseInfos {
  @JsonProperty("Id")
  private String id = null;

  @JsonProperty("OutdooractiveID")
  private String outdooractiveID = null;

  @JsonProperty("OutdooractiveElevationID")
  private String outdooractiveElevationID = null;

  @JsonProperty("Active")
  private Boolean active = null;

  @JsonProperty("Shortname")
  private String shortname = null;

  @JsonProperty("SmgId")
  private String smgId = null;

  @JsonProperty("Highlight")
  private Boolean highlight = null;

  @JsonProperty("Difficulty")
  private String difficulty = null;

  @JsonProperty("Type")
  private String type = null;

  @JsonProperty("SubType")
  private String subType = null;

  @JsonProperty("PoiType")
  private String poiType = null;

  @JsonProperty("FirstImport")
  private String firstImport = null;

  @JsonProperty("LastChange")
  private String lastChange = null;

  @JsonProperty("SmgActive")
  private Boolean smgActive = null;

  @JsonProperty("LocationInfo")
  private LocationInfo locationInfo = null;

  @JsonProperty("TourismorganizationId")
  private String tourismorganizationId = null;

  @JsonProperty("AreaId")
  private List<String> areaId = null;

  @JsonProperty("AltitudeDifference")
  private Double altitudeDifference = null;

  @JsonProperty("AltitudeHighestPoint")
  private Double altitudeHighestPoint = null;

  @JsonProperty("AltitudeLowestPoint")
  private Double altitudeLowestPoint = null;

  @JsonProperty("AltitudeSumUp")
  private Double altitudeSumUp = null;

  @JsonProperty("AltitudeSumDown")
  private Double altitudeSumDown = null;

  @JsonProperty("DistanceDuration")
  private Double distanceDuration = null;

  @JsonProperty("DistanceLength")
  private Double distanceLength = null;

  @JsonProperty("IsOpen")
  private Boolean isOpen = null;

  @JsonProperty("IsPrepared")
  private Boolean isPrepared = null;

  @JsonProperty("RunToValley")
  private Boolean runToValley = null;

  @JsonProperty("IsWithLigth")
  private Boolean isWithLigth = null;

  @JsonProperty("HasRentals")
  private Boolean hasRentals = null;

  @JsonProperty("HasFreeEntrance")
  private Boolean hasFreeEntrance = null;

  @JsonProperty("LiftAvailable")
  private Boolean liftAvailable = null;

  @JsonProperty("FeetClimb")
  private Boolean feetClimb = null;

  @JsonProperty("BikeTransport")
  private Boolean bikeTransport = null;

  @JsonProperty("OperationSchedule")
  private List<OperationSchedule> operationSchedule = null;

  @JsonProperty("GpsInfo")
  private List<GpsInfo> gpsInfo = null;

  @JsonProperty("GpsTrack")
  private List<GpsTrack> gpsTrack = null;

  @JsonProperty("ImageGallery")
  private List<ImageGallery> imageGallery = null;

  @JsonProperty("Detail")
  private Map<String, Detail> detail = null;

  @JsonProperty("ContactInfos")
  private Map<String, ContactInfos> contactInfos = null;

  @JsonProperty("AdditionalPoiInfos")
  private Map<String, AdditionalPoiInfos> additionalPoiInfos = null;

  @JsonProperty("SmgTags")
  private List<String> smgTags = null;

  @JsonProperty("HasLanguage")
  private List<String> hasLanguage = null;

  @JsonProperty("Ratings")
  private Ratings ratings = null;

  @JsonProperty("Exposition")
  private List<String> exposition = null;

  public PoiBaseInfos id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PoiBaseInfos outdooractiveID(String outdooractiveID) {
    this.outdooractiveID = outdooractiveID;
    return this;
  }

   /**
   * Get outdooractiveID
   * @return outdooractiveID
  **/
  @ApiModelProperty(value = "")
  public String getOutdooractiveID() {
    return outdooractiveID;
  }

  public void setOutdooractiveID(String outdooractiveID) {
    this.outdooractiveID = outdooractiveID;
  }

  public PoiBaseInfos outdooractiveElevationID(String outdooractiveElevationID) {
    this.outdooractiveElevationID = outdooractiveElevationID;
    return this;
  }

   /**
   * Get outdooractiveElevationID
   * @return outdooractiveElevationID
  **/
  @ApiModelProperty(value = "")
  public String getOutdooractiveElevationID() {
    return outdooractiveElevationID;
  }

  public void setOutdooractiveElevationID(String outdooractiveElevationID) {
    this.outdooractiveElevationID = outdooractiveElevationID;
  }

  public PoiBaseInfos active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public PoiBaseInfos shortname(String shortname) {
    this.shortname = shortname;
    return this;
  }

   /**
   * Get shortname
   * @return shortname
  **/
  @ApiModelProperty(value = "")
  public String getShortname() {
    return shortname;
  }

  public void setShortname(String shortname) {
    this.shortname = shortname;
  }

  public PoiBaseInfos smgId(String smgId) {
    this.smgId = smgId;
    return this;
  }

   /**
   * Get smgId
   * @return smgId
  **/
  @ApiModelProperty(value = "")
  public String getSmgId() {
    return smgId;
  }

  public void setSmgId(String smgId) {
    this.smgId = smgId;
  }

  public PoiBaseInfos highlight(Boolean highlight) {
    this.highlight = highlight;
    return this;
  }

   /**
   * Get highlight
   * @return highlight
  **/
  @ApiModelProperty(value = "")
  public Boolean isHighlight() {
    return highlight;
  }

  public void setHighlight(Boolean highlight) {
    this.highlight = highlight;
  }

  public PoiBaseInfos difficulty(String difficulty) {
    this.difficulty = difficulty;
    return this;
  }

   /**
   * Get difficulty
   * @return difficulty
  **/
  @ApiModelProperty(value = "")
  public String getDifficulty() {
    return difficulty;
  }

  public void setDifficulty(String difficulty) {
    this.difficulty = difficulty;
  }

  public PoiBaseInfos type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public PoiBaseInfos subType(String subType) {
    this.subType = subType;
    return this;
  }

   /**
   * Get subType
   * @return subType
  **/
  @ApiModelProperty(value = "")
  public String getSubType() {
    return subType;
  }

  public void setSubType(String subType) {
    this.subType = subType;
  }

  public PoiBaseInfos poiType(String poiType) {
    this.poiType = poiType;
    return this;
  }

   /**
   * Get poiType
   * @return poiType
  **/
  @ApiModelProperty(value = "")
  public String getPoiType() {
    return poiType;
  }

  public void setPoiType(String poiType) {
    this.poiType = poiType;
  }

  public PoiBaseInfos firstImport(String firstImport) {
    this.firstImport = firstImport;
    return this;
  }

   /**
   * Get firstImport
   * @return firstImport
  **/
  @ApiModelProperty(value = "")
  public String getFirstImport() {
    return firstImport;
  }

  public void setFirstImport(String firstImport) {
    this.firstImport = firstImport;
  }

  public PoiBaseInfos lastChange(String lastChange) {
    this.lastChange = lastChange;
    return this;
  }

   /**
   * Get lastChange
   * @return lastChange
  **/
  @ApiModelProperty(value = "")
  public String getLastChange() {
    return lastChange;
  }

  public void setLastChange(String lastChange) {
    this.lastChange = lastChange;
  }

  public PoiBaseInfos smgActive(Boolean smgActive) {
    this.smgActive = smgActive;
    return this;
  }

   /**
   * Get smgActive
   * @return smgActive
  **/
  @ApiModelProperty(value = "")
  public Boolean isSmgActive() {
    return smgActive;
  }

  public void setSmgActive(Boolean smgActive) {
    this.smgActive = smgActive;
  }

  public PoiBaseInfos locationInfo(LocationInfo locationInfo) {
    this.locationInfo = locationInfo;
    return this;
  }

   /**
   * Get locationInfo
   * @return locationInfo
  **/
  @ApiModelProperty(value = "")
  public LocationInfo getLocationInfo() {
    return locationInfo;
  }

  public void setLocationInfo(LocationInfo locationInfo) {
    this.locationInfo = locationInfo;
  }

  public PoiBaseInfos tourismorganizationId(String tourismorganizationId) {
    this.tourismorganizationId = tourismorganizationId;
    return this;
  }

   /**
   * Get tourismorganizationId
   * @return tourismorganizationId
  **/
  @ApiModelProperty(value = "")
  public String getTourismorganizationId() {
    return tourismorganizationId;
  }

  public void setTourismorganizationId(String tourismorganizationId) {
    this.tourismorganizationId = tourismorganizationId;
  }

  public PoiBaseInfos areaId(List<String> areaId) {
    this.areaId = areaId;
    return this;
  }

  public PoiBaseInfos addAreaIdItem(String areaIdItem) {
    if (this.areaId == null) {
      this.areaId = new ArrayList<>();
    }
    this.areaId.add(areaIdItem);
    return this;
  }

   /**
   * Get areaId
   * @return areaId
  **/
  @ApiModelProperty(value = "")
  public List<String> getAreaId() {
    return areaId;
  }

  public void setAreaId(List<String> areaId) {
    this.areaId = areaId;
  }

  public PoiBaseInfos altitudeDifference(Double altitudeDifference) {
    this.altitudeDifference = altitudeDifference;
    return this;
  }

   /**
   * Get altitudeDifference
   * @return altitudeDifference
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeDifference() {
    return altitudeDifference;
  }

  public void setAltitudeDifference(Double altitudeDifference) {
    this.altitudeDifference = altitudeDifference;
  }

  public PoiBaseInfos altitudeHighestPoint(Double altitudeHighestPoint) {
    this.altitudeHighestPoint = altitudeHighestPoint;
    return this;
  }

   /**
   * Get altitudeHighestPoint
   * @return altitudeHighestPoint
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeHighestPoint() {
    return altitudeHighestPoint;
  }

  public void setAltitudeHighestPoint(Double altitudeHighestPoint) {
    this.altitudeHighestPoint = altitudeHighestPoint;
  }

  public PoiBaseInfos altitudeLowestPoint(Double altitudeLowestPoint) {
    this.altitudeLowestPoint = altitudeLowestPoint;
    return this;
  }

   /**
   * Get altitudeLowestPoint
   * @return altitudeLowestPoint
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeLowestPoint() {
    return altitudeLowestPoint;
  }

  public void setAltitudeLowestPoint(Double altitudeLowestPoint) {
    this.altitudeLowestPoint = altitudeLowestPoint;
  }

  public PoiBaseInfos altitudeSumUp(Double altitudeSumUp) {
    this.altitudeSumUp = altitudeSumUp;
    return this;
  }

   /**
   * Get altitudeSumUp
   * @return altitudeSumUp
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeSumUp() {
    return altitudeSumUp;
  }

  public void setAltitudeSumUp(Double altitudeSumUp) {
    this.altitudeSumUp = altitudeSumUp;
  }

  public PoiBaseInfos altitudeSumDown(Double altitudeSumDown) {
    this.altitudeSumDown = altitudeSumDown;
    return this;
  }

   /**
   * Get altitudeSumDown
   * @return altitudeSumDown
  **/
  @ApiModelProperty(value = "")
  public Double getAltitudeSumDown() {
    return altitudeSumDown;
  }

  public void setAltitudeSumDown(Double altitudeSumDown) {
    this.altitudeSumDown = altitudeSumDown;
  }

  public PoiBaseInfos distanceDuration(Double distanceDuration) {
    this.distanceDuration = distanceDuration;
    return this;
  }

   /**
   * Get distanceDuration
   * @return distanceDuration
  **/
  @ApiModelProperty(value = "")
  public Double getDistanceDuration() {
    return distanceDuration;
  }

  public void setDistanceDuration(Double distanceDuration) {
    this.distanceDuration = distanceDuration;
  }

  public PoiBaseInfos distanceLength(Double distanceLength) {
    this.distanceLength = distanceLength;
    return this;
  }

   /**
   * Get distanceLength
   * @return distanceLength
  **/
  @ApiModelProperty(value = "")
  public Double getDistanceLength() {
    return distanceLength;
  }

  public void setDistanceLength(Double distanceLength) {
    this.distanceLength = distanceLength;
  }

  public PoiBaseInfos isOpen(Boolean isOpen) {
    this.isOpen = isOpen;
    return this;
  }

   /**
   * Get isOpen
   * @return isOpen
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsOpen() {
    return isOpen;
  }

  public void setIsOpen(Boolean isOpen) {
    this.isOpen = isOpen;
  }

  public PoiBaseInfos isPrepared(Boolean isPrepared) {
    this.isPrepared = isPrepared;
    return this;
  }

   /**
   * Get isPrepared
   * @return isPrepared
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPrepared() {
    return isPrepared;
  }

  public void setIsPrepared(Boolean isPrepared) {
    this.isPrepared = isPrepared;
  }

  public PoiBaseInfos runToValley(Boolean runToValley) {
    this.runToValley = runToValley;
    return this;
  }

   /**
   * Get runToValley
   * @return runToValley
  **/
  @ApiModelProperty(value = "")
  public Boolean isRunToValley() {
    return runToValley;
  }

  public void setRunToValley(Boolean runToValley) {
    this.runToValley = runToValley;
  }

  public PoiBaseInfos isWithLigth(Boolean isWithLigth) {
    this.isWithLigth = isWithLigth;
    return this;
  }

   /**
   * Get isWithLigth
   * @return isWithLigth
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsWithLigth() {
    return isWithLigth;
  }

  public void setIsWithLigth(Boolean isWithLigth) {
    this.isWithLigth = isWithLigth;
  }

  public PoiBaseInfos hasRentals(Boolean hasRentals) {
    this.hasRentals = hasRentals;
    return this;
  }

   /**
   * Get hasRentals
   * @return hasRentals
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasRentals() {
    return hasRentals;
  }

  public void setHasRentals(Boolean hasRentals) {
    this.hasRentals = hasRentals;
  }

  public PoiBaseInfos hasFreeEntrance(Boolean hasFreeEntrance) {
    this.hasFreeEntrance = hasFreeEntrance;
    return this;
  }

   /**
   * Get hasFreeEntrance
   * @return hasFreeEntrance
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasFreeEntrance() {
    return hasFreeEntrance;
  }

  public void setHasFreeEntrance(Boolean hasFreeEntrance) {
    this.hasFreeEntrance = hasFreeEntrance;
  }

  public PoiBaseInfos liftAvailable(Boolean liftAvailable) {
    this.liftAvailable = liftAvailable;
    return this;
  }

   /**
   * Get liftAvailable
   * @return liftAvailable
  **/
  @ApiModelProperty(value = "")
  public Boolean isLiftAvailable() {
    return liftAvailable;
  }

  public void setLiftAvailable(Boolean liftAvailable) {
    this.liftAvailable = liftAvailable;
  }

  public PoiBaseInfos feetClimb(Boolean feetClimb) {
    this.feetClimb = feetClimb;
    return this;
  }

   /**
   * Get feetClimb
   * @return feetClimb
  **/
  @ApiModelProperty(value = "")
  public Boolean isFeetClimb() {
    return feetClimb;
  }

  public void setFeetClimb(Boolean feetClimb) {
    this.feetClimb = feetClimb;
  }

  public PoiBaseInfos bikeTransport(Boolean bikeTransport) {
    this.bikeTransport = bikeTransport;
    return this;
  }

   /**
   * Get bikeTransport
   * @return bikeTransport
  **/
  @ApiModelProperty(value = "")
  public Boolean isBikeTransport() {
    return bikeTransport;
  }

  public void setBikeTransport(Boolean bikeTransport) {
    this.bikeTransport = bikeTransport;
  }

  public PoiBaseInfos operationSchedule(List<OperationSchedule> operationSchedule) {
    this.operationSchedule = operationSchedule;
    return this;
  }

  public PoiBaseInfos addOperationScheduleItem(OperationSchedule operationScheduleItem) {
    if (this.operationSchedule == null) {
      this.operationSchedule = new ArrayList<>();
    }
    this.operationSchedule.add(operationScheduleItem);
    return this;
  }

   /**
   * Get operationSchedule
   * @return operationSchedule
  **/
  @ApiModelProperty(value = "")
  public List<OperationSchedule> getOperationSchedule() {
    return operationSchedule;
  }

  public void setOperationSchedule(List<OperationSchedule> operationSchedule) {
    this.operationSchedule = operationSchedule;
  }

  public PoiBaseInfos gpsInfo(List<GpsInfo> gpsInfo) {
    this.gpsInfo = gpsInfo;
    return this;
  }

  public PoiBaseInfos addGpsInfoItem(GpsInfo gpsInfoItem) {
    if (this.gpsInfo == null) {
      this.gpsInfo = new ArrayList<>();
    }
    this.gpsInfo.add(gpsInfoItem);
    return this;
  }

   /**
   * Get gpsInfo
   * @return gpsInfo
  **/
  @ApiModelProperty(value = "")
  public List<GpsInfo> getGpsInfo() {
    return gpsInfo;
  }

  public void setGpsInfo(List<GpsInfo> gpsInfo) {
    this.gpsInfo = gpsInfo;
  }

  public PoiBaseInfos gpsTrack(List<GpsTrack> gpsTrack) {
    this.gpsTrack = gpsTrack;
    return this;
  }

  public PoiBaseInfos addGpsTrackItem(GpsTrack gpsTrackItem) {
    if (this.gpsTrack == null) {
      this.gpsTrack = new ArrayList<>();
    }
    this.gpsTrack.add(gpsTrackItem);
    return this;
  }

   /**
   * Get gpsTrack
   * @return gpsTrack
  **/
  @ApiModelProperty(value = "")
  public List<GpsTrack> getGpsTrack() {
    return gpsTrack;
  }

  public void setGpsTrack(List<GpsTrack> gpsTrack) {
    this.gpsTrack = gpsTrack;
  }

  public PoiBaseInfos imageGallery(List<ImageGallery> imageGallery) {
    this.imageGallery = imageGallery;
    return this;
  }

  public PoiBaseInfos addImageGalleryItem(ImageGallery imageGalleryItem) {
    if (this.imageGallery == null) {
      this.imageGallery = new ArrayList<>();
    }
    this.imageGallery.add(imageGalleryItem);
    return this;
  }

   /**
   * Get imageGallery
   * @return imageGallery
  **/
  @ApiModelProperty(value = "")
  public List<ImageGallery> getImageGallery() {
    return imageGallery;
  }

  public void setImageGallery(List<ImageGallery> imageGallery) {
    this.imageGallery = imageGallery;
  }

  public PoiBaseInfos detail(Map<String, Detail> detail) {
    this.detail = detail;
    return this;
  }

  public PoiBaseInfos putDetailItem(String key, Detail detailItem) {
    if (this.detail == null) {
      this.detail = new HashMap<>();
    }
    this.detail.put(key, detailItem);
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @ApiModelProperty(value = "")
  public Map<String, Detail> getDetail() {
    return detail;
  }

  public void setDetail(Map<String, Detail> detail) {
    this.detail = detail;
  }

  public PoiBaseInfos contactInfos(Map<String, ContactInfos> contactInfos) {
    this.contactInfos = contactInfos;
    return this;
  }

  public PoiBaseInfos putContactInfosItem(String key, ContactInfos contactInfosItem) {
    if (this.contactInfos == null) {
      this.contactInfos = new HashMap<>();
    }
    this.contactInfos.put(key, contactInfosItem);
    return this;
  }

   /**
   * Get contactInfos
   * @return contactInfos
  **/
  @ApiModelProperty(value = "")
  public Map<String, ContactInfos> getContactInfos() {
    return contactInfos;
  }

  public void setContactInfos(Map<String, ContactInfos> contactInfos) {
    this.contactInfos = contactInfos;
  }

  public PoiBaseInfos additionalPoiInfos(Map<String, AdditionalPoiInfos> additionalPoiInfos) {
    this.additionalPoiInfos = additionalPoiInfos;
    return this;
  }

  public PoiBaseInfos putAdditionalPoiInfosItem(String key, AdditionalPoiInfos additionalPoiInfosItem) {
    if (this.additionalPoiInfos == null) {
      this.additionalPoiInfos = new HashMap<>();
    }
    this.additionalPoiInfos.put(key, additionalPoiInfosItem);
    return this;
  }

   /**
   * Get additionalPoiInfos
   * @return additionalPoiInfos
  **/
  @ApiModelProperty(value = "")
  public Map<String, AdditionalPoiInfos> getAdditionalPoiInfos() {
    return additionalPoiInfos;
  }

  public void setAdditionalPoiInfos(Map<String, AdditionalPoiInfos> additionalPoiInfos) {
    this.additionalPoiInfos = additionalPoiInfos;
  }

  public PoiBaseInfos smgTags(List<String> smgTags) {
    this.smgTags = smgTags;
    return this;
  }

  public PoiBaseInfos addSmgTagsItem(String smgTagsItem) {
    if (this.smgTags == null) {
      this.smgTags = new ArrayList<>();
    }
    this.smgTags.add(smgTagsItem);
    return this;
  }

   /**
   * Get smgTags
   * @return smgTags
  **/
  @ApiModelProperty(value = "")
  public List<String> getSmgTags() {
    return smgTags;
  }

  public void setSmgTags(List<String> smgTags) {
    this.smgTags = smgTags;
  }

  public PoiBaseInfos hasLanguage(List<String> hasLanguage) {
    this.hasLanguage = hasLanguage;
    return this;
  }

  public PoiBaseInfos addHasLanguageItem(String hasLanguageItem) {
    if (this.hasLanguage == null) {
      this.hasLanguage = new ArrayList<>();
    }
    this.hasLanguage.add(hasLanguageItem);
    return this;
  }

   /**
   * Get hasLanguage
   * @return hasLanguage
  **/
  @ApiModelProperty(value = "")
  public List<String> getHasLanguage() {
    return hasLanguage;
  }

  public void setHasLanguage(List<String> hasLanguage) {
    this.hasLanguage = hasLanguage;
  }

  public PoiBaseInfos ratings(Ratings ratings) {
    this.ratings = ratings;
    return this;
  }

   /**
   * Get ratings
   * @return ratings
  **/
  @ApiModelProperty(value = "")
  public Ratings getRatings() {
    return ratings;
  }

  public void setRatings(Ratings ratings) {
    this.ratings = ratings;
  }

  public PoiBaseInfos exposition(List<String> exposition) {
    this.exposition = exposition;
    return this;
  }

  public PoiBaseInfos addExpositionItem(String expositionItem) {
    if (this.exposition == null) {
      this.exposition = new ArrayList<>();
    }
    this.exposition.add(expositionItem);
    return this;
  }

   /**
   * Get exposition
   * @return exposition
  **/
  @ApiModelProperty(value = "")
  public List<String> getExposition() {
    return exposition;
  }

  public void setExposition(List<String> exposition) {
    this.exposition = exposition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoiBaseInfos poiBaseInfos = (PoiBaseInfos) o;
    return Objects.equals(this.id, poiBaseInfos.id) &&
        Objects.equals(this.outdooractiveID, poiBaseInfos.outdooractiveID) &&
        Objects.equals(this.outdooractiveElevationID, poiBaseInfos.outdooractiveElevationID) &&
        Objects.equals(this.active, poiBaseInfos.active) &&
        Objects.equals(this.shortname, poiBaseInfos.shortname) &&
        Objects.equals(this.smgId, poiBaseInfos.smgId) &&
        Objects.equals(this.highlight, poiBaseInfos.highlight) &&
        Objects.equals(this.difficulty, poiBaseInfos.difficulty) &&
        Objects.equals(this.type, poiBaseInfos.type) &&
        Objects.equals(this.subType, poiBaseInfos.subType) &&
        Objects.equals(this.poiType, poiBaseInfos.poiType) &&
        Objects.equals(this.firstImport, poiBaseInfos.firstImport) &&
        Objects.equals(this.lastChange, poiBaseInfos.lastChange) &&
        Objects.equals(this.smgActive, poiBaseInfos.smgActive) &&
        Objects.equals(this.locationInfo, poiBaseInfos.locationInfo) &&
        Objects.equals(this.tourismorganizationId, poiBaseInfos.tourismorganizationId) &&
        Objects.equals(this.areaId, poiBaseInfos.areaId) &&
        Objects.equals(this.altitudeDifference, poiBaseInfos.altitudeDifference) &&
        Objects.equals(this.altitudeHighestPoint, poiBaseInfos.altitudeHighestPoint) &&
        Objects.equals(this.altitudeLowestPoint, poiBaseInfos.altitudeLowestPoint) &&
        Objects.equals(this.altitudeSumUp, poiBaseInfos.altitudeSumUp) &&
        Objects.equals(this.altitudeSumDown, poiBaseInfos.altitudeSumDown) &&
        Objects.equals(this.distanceDuration, poiBaseInfos.distanceDuration) &&
        Objects.equals(this.distanceLength, poiBaseInfos.distanceLength) &&
        Objects.equals(this.isOpen, poiBaseInfos.isOpen) &&
        Objects.equals(this.isPrepared, poiBaseInfos.isPrepared) &&
        Objects.equals(this.runToValley, poiBaseInfos.runToValley) &&
        Objects.equals(this.isWithLigth, poiBaseInfos.isWithLigth) &&
        Objects.equals(this.hasRentals, poiBaseInfos.hasRentals) &&
        Objects.equals(this.hasFreeEntrance, poiBaseInfos.hasFreeEntrance) &&
        Objects.equals(this.liftAvailable, poiBaseInfos.liftAvailable) &&
        Objects.equals(this.feetClimb, poiBaseInfos.feetClimb) &&
        Objects.equals(this.bikeTransport, poiBaseInfos.bikeTransport) &&
        Objects.equals(this.operationSchedule, poiBaseInfos.operationSchedule) &&
        Objects.equals(this.gpsInfo, poiBaseInfos.gpsInfo) &&
        Objects.equals(this.gpsTrack, poiBaseInfos.gpsTrack) &&
        Objects.equals(this.imageGallery, poiBaseInfos.imageGallery) &&
        Objects.equals(this.detail, poiBaseInfos.detail) &&
        Objects.equals(this.contactInfos, poiBaseInfos.contactInfos) &&
        Objects.equals(this.additionalPoiInfos, poiBaseInfos.additionalPoiInfos) &&
        Objects.equals(this.smgTags, poiBaseInfos.smgTags) &&
        Objects.equals(this.hasLanguage, poiBaseInfos.hasLanguage) &&
        Objects.equals(this.ratings, poiBaseInfos.ratings) &&
        Objects.equals(this.exposition, poiBaseInfos.exposition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, outdooractiveID, outdooractiveElevationID, active, shortname, smgId, highlight, difficulty, type, subType, poiType, firstImport, lastChange, smgActive, locationInfo, tourismorganizationId, areaId, altitudeDifference, altitudeHighestPoint, altitudeLowestPoint, altitudeSumUp, altitudeSumDown, distanceDuration, distanceLength, isOpen, isPrepared, runToValley, isWithLigth, hasRentals, hasFreeEntrance, liftAvailable, feetClimb, bikeTransport, operationSchedule, gpsInfo, gpsTrack, imageGallery, detail, contactInfos, additionalPoiInfos, smgTags, hasLanguage, ratings, exposition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoiBaseInfos {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    outdooractiveID: ").append(toIndentedString(outdooractiveID)).append("\n");
    sb.append("    outdooractiveElevationID: ").append(toIndentedString(outdooractiveElevationID)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    shortname: ").append(toIndentedString(shortname)).append("\n");
    sb.append("    smgId: ").append(toIndentedString(smgId)).append("\n");
    sb.append("    highlight: ").append(toIndentedString(highlight)).append("\n");
    sb.append("    difficulty: ").append(toIndentedString(difficulty)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    subType: ").append(toIndentedString(subType)).append("\n");
    sb.append("    poiType: ").append(toIndentedString(poiType)).append("\n");
    sb.append("    firstImport: ").append(toIndentedString(firstImport)).append("\n");
    sb.append("    lastChange: ").append(toIndentedString(lastChange)).append("\n");
    sb.append("    smgActive: ").append(toIndentedString(smgActive)).append("\n");
    sb.append("    locationInfo: ").append(toIndentedString(locationInfo)).append("\n");
    sb.append("    tourismorganizationId: ").append(toIndentedString(tourismorganizationId)).append("\n");
    sb.append("    areaId: ").append(toIndentedString(areaId)).append("\n");
    sb.append("    altitudeDifference: ").append(toIndentedString(altitudeDifference)).append("\n");
    sb.append("    altitudeHighestPoint: ").append(toIndentedString(altitudeHighestPoint)).append("\n");
    sb.append("    altitudeLowestPoint: ").append(toIndentedString(altitudeLowestPoint)).append("\n");
    sb.append("    altitudeSumUp: ").append(toIndentedString(altitudeSumUp)).append("\n");
    sb.append("    altitudeSumDown: ").append(toIndentedString(altitudeSumDown)).append("\n");
    sb.append("    distanceDuration: ").append(toIndentedString(distanceDuration)).append("\n");
    sb.append("    distanceLength: ").append(toIndentedString(distanceLength)).append("\n");
    sb.append("    isOpen: ").append(toIndentedString(isOpen)).append("\n");
    sb.append("    isPrepared: ").append(toIndentedString(isPrepared)).append("\n");
    sb.append("    runToValley: ").append(toIndentedString(runToValley)).append("\n");
    sb.append("    isWithLigth: ").append(toIndentedString(isWithLigth)).append("\n");
    sb.append("    hasRentals: ").append(toIndentedString(hasRentals)).append("\n");
    sb.append("    hasFreeEntrance: ").append(toIndentedString(hasFreeEntrance)).append("\n");
    sb.append("    liftAvailable: ").append(toIndentedString(liftAvailable)).append("\n");
    sb.append("    feetClimb: ").append(toIndentedString(feetClimb)).append("\n");
    sb.append("    bikeTransport: ").append(toIndentedString(bikeTransport)).append("\n");
    sb.append("    operationSchedule: ").append(toIndentedString(operationSchedule)).append("\n");
    sb.append("    gpsInfo: ").append(toIndentedString(gpsInfo)).append("\n");
    sb.append("    gpsTrack: ").append(toIndentedString(gpsTrack)).append("\n");
    sb.append("    imageGallery: ").append(toIndentedString(imageGallery)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    contactInfos: ").append(toIndentedString(contactInfos)).append("\n");
    sb.append("    additionalPoiInfos: ").append(toIndentedString(additionalPoiInfos)).append("\n");
    sb.append("    smgTags: ").append(toIndentedString(smgTags)).append("\n");
    sb.append("    hasLanguage: ").append(toIndentedString(hasLanguage)).append("\n");
    sb.append("    ratings: ").append(toIndentedString(ratings)).append("\n");
    sb.append("    exposition: ").append(toIndentedString(exposition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

