/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Ratings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class Ratings {
  @JsonProperty("Stamina")
  private String stamina = null;

  @JsonProperty("Experience")
  private String experience = null;

  @JsonProperty("Landscape")
  private String landscape = null;

  @JsonProperty("Difficulty")
  private String difficulty = null;

  @JsonProperty("Technique")
  private String technique = null;

  public Ratings stamina(String stamina) {
    this.stamina = stamina;
    return this;
  }

   /**
   * Get stamina
   * @return stamina
  **/
  @ApiModelProperty(value = "")
  public String getStamina() {
    return stamina;
  }

  public void setStamina(String stamina) {
    this.stamina = stamina;
  }

  public Ratings experience(String experience) {
    this.experience = experience;
    return this;
  }

   /**
   * Get experience
   * @return experience
  **/
  @ApiModelProperty(value = "")
  public String getExperience() {
    return experience;
  }

  public void setExperience(String experience) {
    this.experience = experience;
  }

  public Ratings landscape(String landscape) {
    this.landscape = landscape;
    return this;
  }

   /**
   * Get landscape
   * @return landscape
  **/
  @ApiModelProperty(value = "")
  public String getLandscape() {
    return landscape;
  }

  public void setLandscape(String landscape) {
    this.landscape = landscape;
  }

  public Ratings difficulty(String difficulty) {
    this.difficulty = difficulty;
    return this;
  }

   /**
   * Get difficulty
   * @return difficulty
  **/
  @ApiModelProperty(value = "")
  public String getDifficulty() {
    return difficulty;
  }

  public void setDifficulty(String difficulty) {
    this.difficulty = difficulty;
  }

  public Ratings technique(String technique) {
    this.technique = technique;
    return this;
  }

   /**
   * Get technique
   * @return technique
  **/
  @ApiModelProperty(value = "")
  public String getTechnique() {
    return technique;
  }

  public void setTechnique(String technique) {
    this.technique = technique;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ratings ratings = (Ratings) o;
    return Objects.equals(this.stamina, ratings.stamina) &&
        Objects.equals(this.experience, ratings.experience) &&
        Objects.equals(this.landscape, ratings.landscape) &&
        Objects.equals(this.difficulty, ratings.difficulty) &&
        Objects.equals(this.technique, ratings.technique);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stamina, experience, landscape, difficulty, technique);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ratings {\n");
    
    sb.append("    stamina: ").append(toIndentedString(stamina)).append("\n");
    sb.append("    experience: ").append(toIndentedString(experience)).append("\n");
    sb.append("    landscape: ").append(toIndentedString(landscape)).append("\n");
    sb.append("    difficulty: ").append(toIndentedString(difficulty)).append("\n");
    sb.append("    technique: ").append(toIndentedString(technique)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

