/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.hackthealps.codemates.staylocalpaylocal.opendata.model.EventShort;
import java.util.ArrayList;
import java.util.List;

/**
 * ResultEventShort
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class ResultEventShort {
  @JsonProperty("TotalResults")
  private Integer totalResults = null;

  @JsonProperty("TotalPages")
  private Integer totalPages = null;

  @JsonProperty("CurrentPage")
  private Integer currentPage = null;

  @JsonProperty("OnlineResults")
  private Integer onlineResults = null;

  @JsonProperty("ResultId")
  private String resultId = null;

  @JsonProperty("Seed")
  private String seed = null;

  @JsonProperty("Items")
  private List<EventShort> items = null;

  public ResultEventShort totalResults(Integer totalResults) {
    this.totalResults = totalResults;
    return this;
  }

   /**
   * Get totalResults
   * @return totalResults
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalResults() {
    return totalResults;
  }

  public void setTotalResults(Integer totalResults) {
    this.totalResults = totalResults;
  }

  public ResultEventShort totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }

  public ResultEventShort currentPage(Integer currentPage) {
    this.currentPage = currentPage;
    return this;
  }

   /**
   * Get currentPage
   * @return currentPage
  **/
  @ApiModelProperty(value = "")
  public Integer getCurrentPage() {
    return currentPage;
  }

  public void setCurrentPage(Integer currentPage) {
    this.currentPage = currentPage;
  }

  public ResultEventShort onlineResults(Integer onlineResults) {
    this.onlineResults = onlineResults;
    return this;
  }

   /**
   * Get onlineResults
   * @return onlineResults
  **/
  @ApiModelProperty(value = "")
  public Integer getOnlineResults() {
    return onlineResults;
  }

  public void setOnlineResults(Integer onlineResults) {
    this.onlineResults = onlineResults;
  }

  public ResultEventShort resultId(String resultId) {
    this.resultId = resultId;
    return this;
  }

   /**
   * Get resultId
   * @return resultId
  **/
  @ApiModelProperty(value = "")
  public String getResultId() {
    return resultId;
  }

  public void setResultId(String resultId) {
    this.resultId = resultId;
  }

  public ResultEventShort seed(String seed) {
    this.seed = seed;
    return this;
  }

   /**
   * Get seed
   * @return seed
  **/
  @ApiModelProperty(value = "")
  public String getSeed() {
    return seed;
  }

  public void setSeed(String seed) {
    this.seed = seed;
  }

  public ResultEventShort items(List<EventShort> items) {
    this.items = items;
    return this;
  }

  public ResultEventShort addItemsItem(EventShort itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(value = "")
  public List<EventShort> getItems() {
    return items;
  }

  public void setItems(List<EventShort> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultEventShort resultEventShort = (ResultEventShort) o;
    return Objects.equals(this.totalResults, resultEventShort.totalResults) &&
        Objects.equals(this.totalPages, resultEventShort.totalPages) &&
        Objects.equals(this.currentPage, resultEventShort.currentPage) &&
        Objects.equals(this.onlineResults, resultEventShort.onlineResults) &&
        Objects.equals(this.resultId, resultEventShort.resultId) &&
        Objects.equals(this.seed, resultEventShort.seed) &&
        Objects.equals(this.items, resultEventShort.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalResults, totalPages, currentPage, onlineResults, resultId, seed, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultEventShort {\n");
    
    sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("    onlineResults: ").append(toIndentedString(onlineResults)).append("\n");
    sb.append("    resultId: ").append(toIndentedString(resultId)).append("\n");
    sb.append("    seed: ").append(toIndentedString(seed)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

