/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * RoomBooked
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class RoomBooked {
  @JsonProperty("Space")
  private String space = null;

  @JsonProperty("SpaceDesc")
  private String spaceDesc = null;

  @JsonProperty("SpaceAbbrev")
  private String spaceAbbrev = null;

  @JsonProperty("SpaceType")
  private String spaceType = null;

  @JsonProperty("Subtitle")
  private String subtitle = null;

  @JsonProperty("Comment")
  private String comment = null;

  @JsonProperty("StartDate")
  private OffsetDateTime startDate = null;

  @JsonProperty("EndDate")
  private OffsetDateTime endDate = null;

  @JsonProperty("StartDateUTC")
  private Double startDateUTC = null;

  @JsonProperty("EndDateUTC")
  private Double endDateUTC = null;

  public RoomBooked space(String space) {
    this.space = space;
    return this;
  }

   /**
   * Get space
   * @return space
  **/
  @ApiModelProperty(value = "")
  public String getSpace() {
    return space;
  }

  public void setSpace(String space) {
    this.space = space;
  }

  public RoomBooked spaceDesc(String spaceDesc) {
    this.spaceDesc = spaceDesc;
    return this;
  }

   /**
   * Get spaceDesc
   * @return spaceDesc
  **/
  @ApiModelProperty(value = "")
  public String getSpaceDesc() {
    return spaceDesc;
  }

  public void setSpaceDesc(String spaceDesc) {
    this.spaceDesc = spaceDesc;
  }

  public RoomBooked spaceAbbrev(String spaceAbbrev) {
    this.spaceAbbrev = spaceAbbrev;
    return this;
  }

   /**
   * Get spaceAbbrev
   * @return spaceAbbrev
  **/
  @ApiModelProperty(value = "")
  public String getSpaceAbbrev() {
    return spaceAbbrev;
  }

  public void setSpaceAbbrev(String spaceAbbrev) {
    this.spaceAbbrev = spaceAbbrev;
  }

  public RoomBooked spaceType(String spaceType) {
    this.spaceType = spaceType;
    return this;
  }

   /**
   * Get spaceType
   * @return spaceType
  **/
  @ApiModelProperty(value = "")
  public String getSpaceType() {
    return spaceType;
  }

  public void setSpaceType(String spaceType) {
    this.spaceType = spaceType;
  }

  public RoomBooked subtitle(String subtitle) {
    this.subtitle = subtitle;
    return this;
  }

   /**
   * Get subtitle
   * @return subtitle
  **/
  @ApiModelProperty(value = "")
  public String getSubtitle() {
    return subtitle;
  }

  public void setSubtitle(String subtitle) {
    this.subtitle = subtitle;
  }

  public RoomBooked comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public RoomBooked startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public RoomBooked endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public RoomBooked startDateUTC(Double startDateUTC) {
    this.startDateUTC = startDateUTC;
    return this;
  }

   /**
   * Get startDateUTC
   * @return startDateUTC
  **/
  @ApiModelProperty(value = "")
  public Double getStartDateUTC() {
    return startDateUTC;
  }

  public void setStartDateUTC(Double startDateUTC) {
    this.startDateUTC = startDateUTC;
  }

  public RoomBooked endDateUTC(Double endDateUTC) {
    this.endDateUTC = endDateUTC;
    return this;
  }

   /**
   * Get endDateUTC
   * @return endDateUTC
  **/
  @ApiModelProperty(value = "")
  public Double getEndDateUTC() {
    return endDateUTC;
  }

  public void setEndDateUTC(Double endDateUTC) {
    this.endDateUTC = endDateUTC;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoomBooked roomBooked = (RoomBooked) o;
    return Objects.equals(this.space, roomBooked.space) &&
        Objects.equals(this.spaceDesc, roomBooked.spaceDesc) &&
        Objects.equals(this.spaceAbbrev, roomBooked.spaceAbbrev) &&
        Objects.equals(this.spaceType, roomBooked.spaceType) &&
        Objects.equals(this.subtitle, roomBooked.subtitle) &&
        Objects.equals(this.comment, roomBooked.comment) &&
        Objects.equals(this.startDate, roomBooked.startDate) &&
        Objects.equals(this.endDate, roomBooked.endDate) &&
        Objects.equals(this.startDateUTC, roomBooked.startDateUTC) &&
        Objects.equals(this.endDateUTC, roomBooked.endDateUTC);
  }

  @Override
  public int hashCode() {
    return Objects.hash(space, spaceDesc, spaceAbbrev, spaceType, subtitle, comment, startDate, endDate, startDateUTC, endDateUTC);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoomBooked {\n");
    
    sb.append("    space: ").append(toIndentedString(space)).append("\n");
    sb.append("    spaceDesc: ").append(toIndentedString(spaceDesc)).append("\n");
    sb.append("    spaceAbbrev: ").append(toIndentedString(spaceAbbrev)).append("\n");
    sb.append("    spaceType: ").append(toIndentedString(spaceType)).append("\n");
    sb.append("    subtitle: ").append(toIndentedString(subtitle)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    startDateUTC: ").append(toIndentedString(startDateUTC)).append("\n");
    sb.append("    endDateUTC: ").append(toIndentedString(endDateUTC)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

