/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * Stationdata
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class Stationdata {
  @JsonProperty("date")
  private OffsetDateTime date = null;

  @JsonProperty("Id")
  private Integer id = null;

  @JsonProperty("CityName")
  private String cityName = null;

  @JsonProperty("WeatherCode")
  private String weatherCode = null;

  @JsonProperty("WeatherDesc")
  private String weatherDesc = null;

  @JsonProperty("WeatherImgUrl")
  private String weatherImgUrl = null;

  @JsonProperty("MinTemp")
  private Integer minTemp = null;

  @JsonProperty("Maxtemp")
  private Integer maxtemp = null;

  public Stationdata date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public Stationdata id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Stationdata cityName(String cityName) {
    this.cityName = cityName;
    return this;
  }

   /**
   * Get cityName
   * @return cityName
  **/
  @ApiModelProperty(value = "")
  public String getCityName() {
    return cityName;
  }

  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  public Stationdata weatherCode(String weatherCode) {
    this.weatherCode = weatherCode;
    return this;
  }

   /**
   * Get weatherCode
   * @return weatherCode
  **/
  @ApiModelProperty(value = "")
  public String getWeatherCode() {
    return weatherCode;
  }

  public void setWeatherCode(String weatherCode) {
    this.weatherCode = weatherCode;
  }

  public Stationdata weatherDesc(String weatherDesc) {
    this.weatherDesc = weatherDesc;
    return this;
  }

   /**
   * Get weatherDesc
   * @return weatherDesc
  **/
  @ApiModelProperty(value = "")
  public String getWeatherDesc() {
    return weatherDesc;
  }

  public void setWeatherDesc(String weatherDesc) {
    this.weatherDesc = weatherDesc;
  }

  public Stationdata weatherImgUrl(String weatherImgUrl) {
    this.weatherImgUrl = weatherImgUrl;
    return this;
  }

   /**
   * Get weatherImgUrl
   * @return weatherImgUrl
  **/
  @ApiModelProperty(value = "")
  public String getWeatherImgUrl() {
    return weatherImgUrl;
  }

  public void setWeatherImgUrl(String weatherImgUrl) {
    this.weatherImgUrl = weatherImgUrl;
  }

  public Stationdata minTemp(Integer minTemp) {
    this.minTemp = minTemp;
    return this;
  }

   /**
   * Get minTemp
   * @return minTemp
  **/
  @ApiModelProperty(value = "")
  public Integer getMinTemp() {
    return minTemp;
  }

  public void setMinTemp(Integer minTemp) {
    this.minTemp = minTemp;
  }

  public Stationdata maxtemp(Integer maxtemp) {
    this.maxtemp = maxtemp;
    return this;
  }

   /**
   * Get maxtemp
   * @return maxtemp
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxtemp() {
    return maxtemp;
  }

  public void setMaxtemp(Integer maxtemp) {
    this.maxtemp = maxtemp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Stationdata stationdata = (Stationdata) o;
    return Objects.equals(this.date, stationdata.date) &&
        Objects.equals(this.id, stationdata.id) &&
        Objects.equals(this.cityName, stationdata.cityName) &&
        Objects.equals(this.weatherCode, stationdata.weatherCode) &&
        Objects.equals(this.weatherDesc, stationdata.weatherDesc) &&
        Objects.equals(this.weatherImgUrl, stationdata.weatherImgUrl) &&
        Objects.equals(this.minTemp, stationdata.minTemp) &&
        Objects.equals(this.maxtemp, stationdata.maxtemp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, id, cityName, weatherCode, weatherDesc, weatherImgUrl, minTemp, maxtemp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Stationdata {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    weatherCode: ").append(toIndentedString(weatherCode)).append("\n");
    sb.append("    weatherDesc: ").append(toIndentedString(weatherDesc)).append("\n");
    sb.append("    weatherImgUrl: ").append(toIndentedString(weatherImgUrl)).append("\n");
    sb.append("    minTemp: ").append(toIndentedString(minTemp)).append("\n");
    sb.append("    maxtemp: ").append(toIndentedString(maxtemp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

