/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Topic
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class Topic {
  @JsonProperty("TopicRID")
  private String topicRID = null;

  @JsonProperty("TopicInfo")
  private String topicInfo = null;

  public Topic topicRID(String topicRID) {
    this.topicRID = topicRID;
    return this;
  }

   /**
   * Get topicRID
   * @return topicRID
  **/
  @ApiModelProperty(value = "")
  public String getTopicRID() {
    return topicRID;
  }

  public void setTopicRID(String topicRID) {
    this.topicRID = topicRID;
  }

  public Topic topicInfo(String topicInfo) {
    this.topicInfo = topicInfo;
    return this;
  }

   /**
   * Get topicInfo
   * @return topicInfo
  **/
  @ApiModelProperty(value = "")
  public String getTopicInfo() {
    return topicInfo;
  }

  public void setTopicInfo(String topicInfo) {
    this.topicInfo = topicInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Topic topic = (Topic) o;
    return Objects.equals(this.topicRID, topic.topicRID) &&
        Objects.equals(this.topicInfo, topic.topicInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topicRID, topicInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Topic {\n");
    
    sb.append("    topicRID: ").append(toIndentedString(topicRID)).append("\n");
    sb.append("    topicInfo: ").append(toIndentedString(topicInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

