/*
 * Open Data Hub PostgreSQL Api Tourism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.hackthealps.codemates.staylocalpaylocal.opendata.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.hackthealps.codemates.staylocalpaylocal.opendata.model.GpsInfo;

/**
 * WebcamLocalized
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-22T03:00:41.182+02:00")
public class WebcamLocalized {
  @JsonProperty("WebcamId")
  private String webcamId = null;

  @JsonProperty("Webcamname")
  private String webcamname = null;

  @JsonProperty("Webcamurl")
  private String webcamurl = null;

  @JsonProperty("GpsInfo")
  private GpsInfo gpsInfo = null;

  public WebcamLocalized webcamId(String webcamId) {
    this.webcamId = webcamId;
    return this;
  }

   /**
   * Get webcamId
   * @return webcamId
  **/
  @ApiModelProperty(value = "")
  public String getWebcamId() {
    return webcamId;
  }

  public void setWebcamId(String webcamId) {
    this.webcamId = webcamId;
  }

  public WebcamLocalized webcamname(String webcamname) {
    this.webcamname = webcamname;
    return this;
  }

   /**
   * Get webcamname
   * @return webcamname
  **/
  @ApiModelProperty(value = "")
  public String getWebcamname() {
    return webcamname;
  }

  public void setWebcamname(String webcamname) {
    this.webcamname = webcamname;
  }

  public WebcamLocalized webcamurl(String webcamurl) {
    this.webcamurl = webcamurl;
    return this;
  }

   /**
   * Get webcamurl
   * @return webcamurl
  **/
  @ApiModelProperty(value = "")
  public String getWebcamurl() {
    return webcamurl;
  }

  public void setWebcamurl(String webcamurl) {
    this.webcamurl = webcamurl;
  }

  public WebcamLocalized gpsInfo(GpsInfo gpsInfo) {
    this.gpsInfo = gpsInfo;
    return this;
  }

   /**
   * Get gpsInfo
   * @return gpsInfo
  **/
  @ApiModelProperty(value = "")
  public GpsInfo getGpsInfo() {
    return gpsInfo;
  }

  public void setGpsInfo(GpsInfo gpsInfo) {
    this.gpsInfo = gpsInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebcamLocalized webcamLocalized = (WebcamLocalized) o;
    return Objects.equals(this.webcamId, webcamLocalized.webcamId) &&
        Objects.equals(this.webcamname, webcamLocalized.webcamname) &&
        Objects.equals(this.webcamurl, webcamLocalized.webcamurl) &&
        Objects.equals(this.gpsInfo, webcamLocalized.gpsInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webcamId, webcamname, webcamurl, gpsInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebcamLocalized {\n");
    
    sb.append("    webcamId: ").append(toIndentedString(webcamId)).append("\n");
    sb.append("    webcamname: ").append(toIndentedString(webcamname)).append("\n");
    sb.append("    webcamurl: ").append(toIndentedString(webcamurl)).append("\n");
    sb.append("    gpsInfo: ").append(toIndentedString(gpsInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

